// Code generated by tools/gen-aitasks from api/ai-tasks.yaml. DO NOT EDIT.

package ai

// Task names one V1 AI workload. Routing is over capability tiers per
// task (ai-operational-spec §1.2); code never names a vendor.
type Task string

const (
	TaskAgentLoop Task = "agent_loop"
	// TaskBriefRanking is the one Premium-frontier default (§1.2 RATIFY): genuinely multi-hop reasoning
	TaskBriefRanking    Task = "brief_ranking"
	TaskCaptureClassify Task = "capture_classify"
	// TaskCertJudge is the aicert quality judge — pinned to its own router in the cert lane, never the candidate's binding
	TaskCertJudge  Task = "cert_judge"
	TaskColdStart  Task = "cold_start"
	TaskDealHealth Task = "deal_health"
	TaskDraftReply Task = "draft_reply"
	TaskEnrich     Task = "enrich"
	TaskNlSearch   Task = "nl_search"
	TaskOfferDraft Task = "offer_draft"
	// TaskRateExtract is extract per-model AI pricing (per-MTok buckets) from a fetched pricing page, evidence-gated; feeds the model-cost refresh proposal producer
	TaskRateExtract Task = "rate_extract"
	// TaskSiteExtract is premium-only BY CONTRACT: the no-guess gate demands verbatim quotes cheap tiers paraphrase; no fallback rung
	TaskSiteExtract Task = "site_extract"
	// TaskSiteFactExtract is the deep read's page-parallel fact lane: tiny snippet-id-cited records a fast cheap tier serves reliably — its latency IS the read time, so the fast tier leads
	TaskSiteFactExtract Task = "site_fact_extract"
	TaskSummarize       Task = "summarize"
	TaskTranscript      Task = "transcript"
	// TaskVoiceBuild is owner-requested or automatic durable Voice DNA candidate build; own-authored corpus only, CompanyContext none (ADR-0066)
	TaskVoiceBuild Task = "voice_build"
)

// ExecutionMode distinguishes request-bound work from work carried by a
// durable background job. Budget exhaustion degrades the former and
// defers the latter.
type ExecutionMode string

const (
	ExecutionModeInteractive ExecutionMode = "interactive"
	ExecutionModeBackground  ExecutionMode = "background"
)

// Tier is a capability tier (§1.1); ai-routing.yaml binds each to a
// provider+model per deployment.
type Tier string

const (
	TierLocalSmall Tier = "local_small"
	TierCheapCloud Tier = "cheap_cloud"
	TierPremium    Tier = "premium"
	TierLocalLarge Tier = "local_large"
)

// TaskContractHash is the sha256 of api/ai-tasks.yaml at generation
// time: a build fingerprint the cert runner can compare against a
// freshly hashed contract file to catch a stale generated table.
const TaskContractHash = "8ed3fc2c0129f09b9b37e93d203e54bce1d41166a1ec721b9c57785f2aab7118"

// AllTasks returns every contract task, sorted — the completeness
// check a certification run walks to prove it covers every routed
// workload, not just the ones a test author remembered.
func AllTasks() []Task {
	return []Task{
		TaskAgentLoop,
		TaskBriefRanking,
		TaskCaptureClassify,
		TaskCertJudge,
		TaskColdStart,
		TaskDealHealth,
		TaskDraftReply,
		TaskEnrich,
		TaskNlSearch,
		TaskOfferDraft,
		TaskRateExtract,
		TaskSiteExtract,
		TaskSiteFactExtract,
		TaskSummarize,
		TaskTranscript,
		TaskVoiceBuild,
	}
}

// taskLadders is the §1.2 routing table: primary tier first, then the
// fallback rungs fired on provider error or schema-validation failure.
var taskLadders = map[Task][]Tier{
	TaskAgentLoop:       {TierCheapCloud, TierPremium},
	TaskBriefRanking:    {TierPremium, TierCheapCloud},
	TaskCaptureClassify: {TierLocalSmall, TierCheapCloud},
	TaskCertJudge:       {TierPremium, TierCheapCloud},
	TaskColdStart:       {TierCheapCloud, TierPremium},
	TaskDealHealth:      {TierCheapCloud, TierPremium},
	TaskDraftReply:      {TierCheapCloud, TierPremium},
	TaskEnrich:          {TierLocalSmall, TierCheapCloud},
	TaskNlSearch:        {TierCheapCloud, TierPremium},
	TaskOfferDraft:      {TierCheapCloud, TierPremium},
	TaskRateExtract:     {TierPremium, TierCheapCloud},
	TaskSiteExtract:     {TierPremium},
	TaskSiteFactExtract: {TierCheapCloud, TierPremium},
	TaskSummarize:       {TierCheapCloud, TierPremium},
	TaskTranscript:      {TierCheapCloud, TierPremium},
	TaskVoiceBuild:      {TierCheapCloud, TierPremium},
}

// degradeTo is the one-tier-down move economy mode applies at 80–100%
// budget utilization (§1.3).
var degradeTo = map[Tier]Tier{
	TierLocalSmall: TierLocalSmall,
	TierCheapCloud: TierLocalSmall,
	TierPremium:    TierCheapCloud,
	TierLocalLarge: TierLocalSmall,
}

// taskExecutionModes is the scheduling contract compiled from
// execution_mode. Every task is present by construction.
var taskExecutionModes = map[Task]ExecutionMode{
	TaskAgentLoop:       ExecutionModeBackground,
	TaskBriefRanking:    ExecutionModeBackground,
	TaskCaptureClassify: ExecutionModeBackground,
	TaskCertJudge:       ExecutionModeBackground,
	TaskColdStart:       ExecutionModeInteractive,
	TaskDealHealth:      ExecutionModeInteractive,
	TaskDraftReply:      ExecutionModeInteractive,
	TaskEnrich:          ExecutionModeBackground,
	TaskNlSearch:        ExecutionModeInteractive,
	TaskOfferDraft:      ExecutionModeInteractive,
	TaskRateExtract:     ExecutionModeBackground,
	TaskSiteExtract:     ExecutionModeBackground,
	TaskSiteFactExtract: ExecutionModeBackground,
	TaskSummarize:       ExecutionModeInteractive,
	TaskTranscript:      ExecutionModeInteractive,
	TaskVoiceBuild:      ExecutionModeBackground,
}

// knownTiers is the routing config's tier-name validation set: the
// contract is the one place tier names are declared, so LoadRoutingFile
// rejects any name this set doesn't contain.
var knownTiers = map[Tier]bool{
	TierLocalSmall: true,
	TierCheapCloud: true,
	TierPremium:    true,
	TierLocalLarge: true,
}
