// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

// schemaTemplate mirrors config/ai-routing.schema.json's structure
// exactly; %s is the tier enum (propertyNames.enum), the one part the
// contract drives. Keeping this as a literal template rather than
// round-tripping through encoding/json preserves the file's hand-tuned
// key order and formatting byte-for-byte across regenerations.
const schemaTemplate = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://margince.dev/schema/ai-routing.json",
  "title": "Margince AI routing config",
  "$comment": "GENERATED by tools/gen-aitasks from backend/api/ai-tasks.yaml — do not edit",
  "type": "object",
  "additionalProperties": false,
  "required": ["profile", "tiers", "embeddings"],
  "properties": {
    "profile": {
      "description": "Location ladder: eu_hosted (partner EU inference), sovereign (zero egress — cloud providers refused), cloud_frontier (BYOK cloud).",
      "enum": ["eu_hosted", "sovereign", "cloud_frontier"]
    },
    "tiers": {
      "description": "Capability tiers; bind each to one provider. An unbound tier is legal — the router degrades honestly.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "propertyNames": { "enum": [%s] },
      "patternProperties": { ".*": { "$ref": "#/$defs/binding" } }
    },
    "embeddings": {
      "description": "The embedding lane, bound separately from chat (retrieval must survive a chat-budget exhaustion). Required.",
      "$ref": "#/$defs/embeddingsBinding"
    }
  },
  "$defs": {
    "binding": {
      "type": "object",
      "additionalProperties": false,
      "required": ["provider"],
      "properties": {
        "provider": {
          "description": "fake | anthropic | ollama | vllm | openai_compatible | openai | gemini. The only place vendor names appear.",
          "enum": ["fake", "anthropic", "ollama", "vllm", "openai_compatible", "openai", "gemini"]
        },
        "model":    { "type": "string", "description": "Provider-native model id. ollama/vllm default to a Gemma-class model when omitted (A23)." },
        "base_url": { "type": "string", "description": "Endpoint override. REQUIRED for openai_compatible (the vendor host root, NO /v1). Empty ⇒ provider default." }
      },
      "allOf": [
        {
          "if":   { "properties": { "provider": { "const": "openai_compatible" } } },
          "then": { "required": ["base_url"] }
        }
      ]
    },
    "embeddingsBinding": {
      "description": "The embeddings-lane binding: same shape as $defs/binding plus dimensions — a field only this lane carries (chat tiers have no notion of output width), so it gets its own $def rather than widening the shared one's additionalProperties:false.",
      "type": "object",
      "additionalProperties": false,
      "required": ["provider"],
      "properties": {
        "provider": {
          "description": "fake | anthropic | ollama | vllm | openai_compatible | openai | gemini. The only place vendor names appear.",
          "enum": ["fake", "anthropic", "ollama", "vllm", "openai_compatible", "openai", "gemini"]
        },
        "model":    { "type": "string", "description": "Provider-native model id. ollama/vllm default to a Gemma-class model when omitted (A23)." },
        "base_url": { "type": "string", "description": "Endpoint override. REQUIRED for openai_compatible (the vendor host root, NO /v1). Empty ⇒ provider default." },
        "dimensions": { "type": "integer", "minimum": 0, "maximum": 2000, "description": "Vector width the provider is asked to emit. Optional; 0 or omitted defaults to 1536." }
      },
      "allOf": [
        {
          "if":   { "properties": { "provider": { "const": "openai_compatible" } } },
          "then": { "required": ["base_url"] }
        }
      ]
    }
  }
}
`

// emitSchema renders config/ai-routing.schema.json with its tier enum
// sourced from the contract's tiers list, in contract order. The result
// is validated as JSON before it is returned: a template substitution
// bug must fail generation, not ship a broken schema.
func emitSchema(tiers []string) (string, error) {
	quoted := make([]string, len(tiers))
	for i, t := range tiers {
		quoted[i] = fmt.Sprintf("%q", t)
	}
	schema := fmt.Sprintf(schemaTemplate, strings.Join(quoted, ", "))

	var v any
	if err := json.Unmarshal([]byte(schema), &v); err != nil {
		return "", fmt.Errorf("generated schema is not valid JSON: %w", err)
	}
	return schema, nil
}
