// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package static

import "testing"

// lintSource parses one in-memory file under the given name and returns its
// findings — the name drives the _test.go / domain-path flags, so a case can
// exercise those code paths without touching disk.
func lintSource(t *testing.T, name, src string) []Finding {
	t.Helper()
	fc, ok := newFileContext(name, []byte(src), "internal/modules/")
	if !ok {
		t.Fatalf("newFileContext(%s) failed to parse", name)
	}
	var out []Finding
	for _, chk := range checks {
		for _, f := range chk.run(fc, Config{}.withDefaults()) {
			if !fc.waived(f.Check, f.Line) {
				out = append(out, f)
			}
		}
	}
	return append(out, fc.waiverHygiene()...)
}

func counts(findings []Finding, check string) int {
	n := 0
	for _, f := range findings {
		if f.Check == check {
			n++
		}
	}
	return n
}

func TestSwallowedErrors_flagsBlankAssignedCall(t *testing.T) {
	src := `package p
func run() { _ = doThing() }
func doThing() error { return nil }`
	if got := counts(lintSource(t, "p.go", src), "swallowed-errors"); got != 1 {
		t.Fatalf("swallowed-errors = %d, want 1", got)
	}
}

func TestSwallowedErrors_ignoresNonCallAndWaived(t *testing.T) {
	src := `package p
func run() {
	_ = x
	_ = doThing() //craft:ignore swallowed-errors close is best-effort
}
var x int
func doThing() error { return nil }`
	if got := counts(lintSource(t, "p.go", src), "swallowed-errors"); got != 0 {
		t.Fatalf("swallowed-errors = %d, want 0 (ident discard + waived call)", got)
	}
}

func TestTestSleep_onlyInTestFiles(t *testing.T) {
	src := `package p
import "time"
func TestX(t *T) { time.Sleep(time.Second); t.Fatal("x") }
type T struct{}`
	if got := counts(lintSource(t, "p.go", src), "test-sleep"); got != 0 {
		t.Fatalf("non-test file flagged for sleep: %d", got)
	}
	if got := counts(lintSource(t, "p_test.go", src), "test-sleep"); got != 1 {
		t.Fatalf("test-sleep = %d, want 1", got)
	}
}

func TestAssertionFree(t *testing.T) {
	src := `package p
import "testing"
func TestReal(t *testing.T) { if 1 != 1 { t.Fatal("no") } }
func TestDelegates(t *testing.T) { check(t) }
func check(t *testing.T) {}
func TestEmpty(t *testing.T) { _ = 1 }`
	if got := counts(lintSource(t, "p_test.go", src), "assertion-free-test"); got != 1 {
		t.Fatalf("assertion-free-test = %d, want 1 (only TestEmpty)", got)
	}
}

func TestBooleanTrap(t *testing.T) {
	src := `package p
func good(a bool) {}
func bad(a, b bool) {}
func alsoBad(a bool, n int, b bool) {}`
	if got := counts(lintSource(t, "p.go", src), "boolean-trap"); got != 2 {
		t.Fatalf("boolean-trap = %d, want 2", got)
	}
}

func TestNakedAny_flagsSignatureNotTypeParam(t *testing.T) {
	src := `package p
func generic[T any](v T) {}
func loose(v any) {}
func alsoLoose() interface{} { return nil }`
	if got := counts(lintSource(t, "p.go", src), "naked-any"); got != 2 {
		t.Fatalf("naked-any = %d, want 2 (generic constraint must not count)", got)
	}
}

func TestPanicInDomain(t *testing.T) {
	src := `package deals
func Advance() { panic("boom") }
func MustLoad() { panic("ok in a Must constructor") }`
	if got := counts(lintSource(t, "internal/modules/deals/svc.go", src), "panic-in-domain"); got != 1 {
		t.Fatalf("panic-in-domain in module = %d, want 1", got)
	}
	if got := counts(lintSource(t, "internal/platform/x/svc.go", src), "panic-in-domain"); got != 0 {
		t.Fatalf("panic-in-domain outside module = %d, want 0", got)
	}
}

func TestTodoWithoutRef(t *testing.T) {
	src := `package p
// TODO fix this later
// TODO(#42) tracked
func f() {}`
	if got := counts(lintSource(t, "p.go", src), "todo-without-ref"); got != 1 {
		t.Fatalf("todo-without-ref = %d, want 1", got)
	}
}

func TestWaiverHygiene_flagsReasonlessDirective(t *testing.T) {
	src := `package p
func f() {
	_ = g() //craft:ignore swallowed-errors
}
func g() error { return nil }`
	f := lintSource(t, "p.go", src)
	if got := counts(f, "waiver-hygiene"); got != 1 {
		t.Fatalf("waiver-hygiene = %d, want 1 (reasonless waiver)", got)
	}
	if got := counts(f, "swallowed-errors"); got != 0 {
		t.Fatalf("swallowed-errors = %d, want 0 (directive still suppresses)", got)
	}
}

func TestVerdict_onlyBlockerBlocks(t *testing.T) {
	f := lintSource(t, "p.go", "package p\nfunc bad(a, b bool) {}")
	if v := verdict(f, false); v != "PASS" {
		t.Fatalf("verdict with only MAJOR = %q, want PASS", v)
	}
	if v := verdict(f, true); v != "BLOCK" {
		t.Fatalf("verdict -strict with MAJOR = %q, want BLOCK", v)
	}
}

func TestGeneratedFilesSkipped(t *testing.T) {
	src := "// Code generated by tool. DO NOT EDIT.\npackage p\nfunc f() { _ = g() }\nfunc g() error { return nil }"
	if _, ok := newFileContext("p_gen_like.go", []byte(src), "internal/modules/"); ok {
		t.Fatal("generated file should be skipped")
	}
}
