// Code generated by tools/gen-agentpolicy from api/crm.yaml. DO NOT EDIT.

package compose

// agentPolicy is one mutating contract operation's admission class for
// AGENT (Passport) principals (ADR-0055): either the MCP tool verb whose
// tier governs it on every transport, or an x-agent-access marker. The
// gate default-denies any mutating route absent from this table.
type agentPolicy struct {
	Op         string // crm.yaml operationId
	Access     string // "tool" | "human-only" | "auth-bootstrap"
	Tool       string // backing MCP tool verb (Access == "tool")
	RecordType string // the record type the operation targets
	Tier       string // contract-declared tier: green | yellow | dynamic
}

// agentPolicies is keyed by "METHOD <chi route pattern>" as the generated
// router registers it (BaseURL /v1 included).
var agentPolicies = map[string]agentPolicy{
	"DELETE /v1/activities/{id}":                 {Op: "archiveActivity", Access: "tool", Tool: "archive_record", RecordType: "activity", Tier: "yellow"},
	"DELETE /v1/automations/{id}":                {Op: "deleteAutomation", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"DELETE /v1/deals/{id}":                      {Op: "archiveDeal", Access: "tool", Tool: "archive_record", RecordType: "deal", Tier: "yellow"},
	"DELETE /v1/leads/{id}":                      {Op: "disqualifyLead", Access: "tool", Tool: "disqualify_lead", RecordType: "lead", Tier: "yellow"},
	"DELETE /v1/lists/{id}":                      {Op: "archiveList", Access: "tool", Tool: "archive_record", RecordType: "list", Tier: "yellow"},
	"DELETE /v1/organizations/{id}":              {Op: "archiveOrganization", Access: "tool", Tool: "archive_record", RecordType: "organization", Tier: "yellow"},
	"DELETE /v1/passports/{id}":                  {Op: "revokePassport", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"DELETE /v1/people/{id}":                     {Op: "archivePerson", Access: "tool", Tool: "archive_record", RecordType: "person", Tier: "yellow"},
	"DELETE /v1/record-grants/{id}":              {Op: "revokeRecordGrant", Access: "tool", Tool: "share_record", RecordType: "record_grant", Tier: "yellow"},
	"DELETE /v1/relationships/{id}":              {Op: "archiveRelationship", Access: "tool", Tool: "archive_record", RecordType: "relationship", Tier: "yellow"},
	"DELETE /v1/tags/{id}":                       {Op: "archiveTag", Access: "tool", Tool: "archive_record", RecordType: "tag", Tier: "yellow"},
	"PATCH /v1/activities/{id}":                  {Op: "updateActivity", Access: "tool", Tool: "update_record", RecordType: "activity", Tier: "dynamic"},
	"PATCH /v1/automations/{id}":                 {Op: "updateAutomation", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"PATCH /v1/data-subject-requests/{id}":       {Op: "updateDataSubjectRequest", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"PATCH /v1/deals/{id}":                       {Op: "updateDeal", Access: "tool", Tool: "update_record", RecordType: "deal", Tier: "dynamic"},
	"PATCH /v1/leads/{id}":                       {Op: "updateLead", Access: "tool", Tool: "update_record", RecordType: "lead", Tier: "dynamic"},
	"PATCH /v1/organizations/{id}":               {Op: "updateOrganization", Access: "tool", Tool: "update_record", RecordType: "organization", Tier: "dynamic"},
	"PATCH /v1/people/{id}":                      {Op: "updatePerson", Access: "tool", Tool: "update_record", RecordType: "person", Tier: "dynamic"},
	"PATCH /v1/pipelines/{id}":                   {Op: "updatePipeline", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"PATCH /v1/relationships/{id}":               {Op: "updateRelationship", Access: "tool", Tool: "update_record", RecordType: "relationship", Tier: "dynamic"},
	"PATCH /v1/stages/{id}":                      {Op: "updateStage", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/activities":                        {Op: "logActivity", Access: "tool", Tool: "log_activity", RecordType: "activity", Tier: "green"},
	"POST /v1/activities/{id}/draft-email":       {Op: "draftEmail", Access: "tool", Tool: "draft_email", RecordType: "activity", Tier: "green"},
	"POST /v1/activities/{id}/relink":            {Op: "relinkActivity", Access: "tool", Tool: "relink_activity", RecordType: "activity", Tier: "green"},
	"POST /v1/activities/{id}/send-email":        {Op: "sendEmail", Access: "tool", Tool: "send_email", RecordType: "activity", Tier: "yellow"},
	"POST /v1/approvals/{id}/approve":            {Op: "approveApproval", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/approvals/{id}/reject":             {Op: "rejectApproval", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/auth/login":                        {Op: "login", Access: "auth-bootstrap", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/auth/logout":                       {Op: "logout", Access: "auth-bootstrap", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/automations":                       {Op: "createAutomation", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/bookings":                          {Op: "bookMeeting", Access: "tool", Tool: "book_meeting", RecordType: "activity", Tier: "yellow"},
	"POST /v1/coldstart":                         {Op: "coldStartReadback", Access: "tool", Tool: "enrich", RecordType: "", Tier: "yellow"},
	"POST /v1/connectors/imap/connect":           {Op: "connectImap", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/consent-purposes":                  {Op: "createConsentPurpose", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/data-subject-requests":             {Op: "createDataSubjectRequest", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/deals":                             {Op: "createDeal", Access: "tool", Tool: "create_record", RecordType: "deal", Tier: "green"},
	"POST /v1/deals/{id}/advance":                {Op: "advanceDeal", Access: "tool", Tool: "advance_deal", RecordType: "deal", Tier: "dynamic"},
	"POST /v1/leads":                             {Op: "createLead", Access: "tool", Tool: "create_record", RecordType: "lead", Tier: "green"},
	"POST /v1/leads/{id}/promote":                {Op: "promoteLead", Access: "tool", Tool: "promote_lead", RecordType: "lead", Tier: "yellow"},
	"POST /v1/lists":                             {Op: "createList", Access: "tool", Tool: "create_record", RecordType: "list", Tier: "green"},
	"POST /v1/lists/{id}/members":                {Op: "addListMember", Access: "tool", Tool: "update_record", RecordType: "list", Tier: "dynamic"},
	"POST /v1/organizations":                     {Op: "createOrganization", Access: "tool", Tool: "create_record", RecordType: "organization", Tier: "green"},
	"POST /v1/organizations/{id}/enrich":         {Op: "scrapeCompany", Access: "tool", Tool: "enrich", RecordType: "", Tier: "yellow"},
	"POST /v1/organizations/{id}/merge":          {Op: "mergeOrganization", Access: "tool", Tool: "merge_records", RecordType: "organization", Tier: "yellow"},
	"POST /v1/passports":                         {Op: "issuePassport", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/people":                            {Op: "createPerson", Access: "tool", Tool: "create_record", RecordType: "person", Tier: "green"},
	"POST /v1/people/{id}/consent":               {Op: "recordConsent", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/people/{id}/consent/double-opt-in": {Op: "issueDoubleOptIn", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/people/{id}/merge":                 {Op: "mergePerson", Access: "tool", Tool: "merge_records", RecordType: "person", Tier: "yellow"},
	"POST /v1/pipelines":                         {Op: "createPipeline", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/public/booking/{host_slug}":        {Op: "bookPublicMeeting", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/record-grants":                     {Op: "createRecordGrant", Access: "tool", Tool: "share_record", RecordType: "record_grant", Tier: "yellow"},
	"POST /v1/relationships":                     {Op: "createRelationship", Access: "tool", Tool: "create_record", RecordType: "relationship", Tier: "green"},
	"POST /v1/reports/{report}":                  {Op: "runReport", Access: "tool", Tool: "run_report", RecordType: "", Tier: "green"},
	"POST /v1/stages":                            {Op: "createStage", Access: "human-only", Tool: "", RecordType: "", Tier: ""},
	"POST /v1/tags":                              {Op: "createTag", Access: "tool", Tool: "create_record", RecordType: "tag", Tier: "green"},
	"POST /v1/tags/{id}/apply":                   {Op: "applyTag", Access: "tool", Tool: "update_record", RecordType: "tag", Tier: "dynamic"},
	"POST /v1/workspaces":                        {Op: "bootstrapWorkspace", Access: "auth-bootstrap", Tool: "", RecordType: "", Tier: ""},
	"PUT /v1/organizations/{id}/partner":         {Op: "upsertPartner", Access: "tool", Tool: "update_record", RecordType: "partner", Tier: "dynamic"},
}
