// Code generated by tools/gen-jobs from api/jobs.yaml. DO NOT EDIT.

package compose

import (
	"github.com/riverqueue/river"

	"github.com/gradionhq/margince/backend/internal/platform/jobs"
)

// jobContractHash is the sha256 of api/jobs.yaml this file was generated
// from — the same fingerprint jobs.JobContractHash carries, so a stale
// half of the pair is visible without diffing the two tables.
const jobContractHash = "ca4e15c4e69932ea9dadfefe5aadf6fad7c2b7ab0c2a65d510a1f9f99f6bc757"

// declaredJobArgs is every args type api/jobs.yaml declares, and nothing
// else. A job kind the file has never heard of cannot satisfy it, so it
// cannot be passed to addDeclaredWorker below.
//
// Registration does not route through that function yet — the runner still
// calls river.AddWorker directly — so what the set buys today is a closed
// list the compiler checks, not a gate every registration has to pass. The
// commit that routes registration through it is what makes an undeclared
// kind unbuildable.
type declaredJobArgs interface {
	river.JobArgs

	AgentSchedulerArgs |
		AgentSchedulerWorkspaceArgs |
		AiModelRateRefreshArgs |
		CaptureAutoEnrichSweepArgs |
		CaptureAutoEnrichWorkspaceArgs |
		CaptureBackfillArgs |
		CaptureClassifyArgs |
		CaptureClassifyWorkspaceArgs |
		CounterpartyVerdictArgs |
		CounterpartyVerdictWorkspaceArgs |
		CaptureDigestArgs |
		CaptureDigestWorkspaceArgs |
		CaptureEnrichArgs |
		CaptureEnrichWorkspaceArgs |
		CaptureSyncArgs |
		CloseDateSweepArgs |
		CloseDateWorkspaceArgs |
		SendEmailArgs |
		EmbedDriftSweepArgs |
		EmbedDriftWorkspaceArgs |
		EmbedReindexArgs |
		EmbedReindexWorkspaceArgs |
		FollowUpReconcileArgs |
		FollowUpWorkspaceArgs |
		FxRateRefreshArgs |
		GmailSyncArgs |
		GmailWatchArgs |
		GmailWatchRenewArgs |
		GraphEdgeReconcileArgs |
		GraphEdgeWorkspaceArgs |
		IdempotencyRetentionArgs |
		IdempotencyRetentionWorkspaceArgs |
		LinkedInRematchArgs |
		LinkedInRematchWorkspaceArgs |
		OrgNamePromotionArgs |
		OrgNamePromotionWorkspaceArgs |
		OverlayReconcileArgs |
		OverlayReconcileWorkspaceArgs |
		OverlayRefetchArgs |
		ParticipantBackfillArgs |
		ParticipantBackfillWorkspaceArgs |
		PrivacyRetentionArgs |
		PrivacyRetentionWorkspaceArgs |
		SiteDeepReadArgs |
		TelegramIngestArgs |
		TelegramPollArgs |
		TelegramPollSweepArgs |
		TimeScanArgs |
		TimeScanWorkspaceArgs |
		VoiceBuildArgs |
		VoiceBuildRetryArgs |
		WebhookRetryArgs |
		WebhookRetryWorkspaceArgs
}

// addDeclaredWorker registers one worker for a DECLARED kind: its type
// parameter is constrained to the set above, so a kind api/jobs.yaml does
// not declare cannot be passed to it.
//
// It is not yet the only way in. The runner still calls river.AddWorker
// directly, so an undeclared kind can still be registered around this
// function; the commit that moves every registration onto it is what makes
// the declared set the set this build can actually work.
func addDeclaredWorker[T declaredJobArgs](workers *river.Workers, w river.Worker[T]) {
	river.AddWorker(workers, w)
}

// The declared dispatchers: each enumerates the fleet and enqueues, and does
// no tenant work of its own.
var (
	_ jobs.FleetWide = AgentSchedulerArgs{}
	_ jobs.FleetWide = CaptureAutoEnrichSweepArgs{}
	_ jobs.FleetWide = CaptureClassifyArgs{}
	_ jobs.FleetWide = CounterpartyVerdictArgs{}
	_ jobs.FleetWide = CaptureDigestArgs{}
	_ jobs.FleetWide = CaptureEnrichArgs{}
	_ jobs.FleetWide = CloseDateSweepArgs{}
	_ jobs.FleetWide = EmbedDriftSweepArgs{}
	_ jobs.FleetWide = EmbedReindexArgs{}
	_ jobs.FleetWide = FollowUpReconcileArgs{}
	_ jobs.FleetWide = GmailSyncArgs{}
	_ jobs.FleetWide = GmailWatchArgs{}
	_ jobs.FleetWide = GraphEdgeReconcileArgs{}
	_ jobs.FleetWide = IdempotencyRetentionArgs{}
	_ jobs.FleetWide = LinkedInRematchArgs{}
	_ jobs.FleetWide = OrgNamePromotionArgs{}
	_ jobs.FleetWide = OverlayReconcileArgs{}
	_ jobs.FleetWide = ParticipantBackfillArgs{}
	_ jobs.FleetWide = PrivacyRetentionArgs{}
	_ jobs.FleetWide = TelegramPollSweepArgs{}
	_ jobs.FleetWide = TimeScanArgs{}
	_ jobs.FleetWide = VoiceBuildRetryArgs{}
	_ jobs.FleetWide = WebhookRetryArgs{}
)

// The declared workspace-scoped kinds: each carries exactly one tenant's
// pass and says which in its own args.
var (
	_ jobs.WorkspaceScoped = AgentSchedulerWorkspaceArgs{}
	_ jobs.WorkspaceScoped = AiModelRateRefreshArgs{}
	_ jobs.WorkspaceScoped = CaptureAutoEnrichWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureBackfillArgs{}
	_ jobs.WorkspaceScoped = CaptureClassifyWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CounterpartyVerdictWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureDigestWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureEnrichWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureSyncArgs{}
	_ jobs.WorkspaceScoped = CloseDateWorkspaceArgs{}
	_ jobs.WorkspaceScoped = SendEmailArgs{}
	_ jobs.WorkspaceScoped = EmbedDriftWorkspaceArgs{}
	_ jobs.WorkspaceScoped = EmbedReindexWorkspaceArgs{}
	_ jobs.WorkspaceScoped = FollowUpWorkspaceArgs{}
	_ jobs.WorkspaceScoped = FxRateRefreshArgs{}
	_ jobs.WorkspaceScoped = GmailWatchRenewArgs{}
	_ jobs.WorkspaceScoped = GraphEdgeWorkspaceArgs{}
	_ jobs.WorkspaceScoped = IdempotencyRetentionWorkspaceArgs{}
	_ jobs.WorkspaceScoped = LinkedInRematchWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OrgNamePromotionWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OverlayReconcileWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OverlayRefetchArgs{}
	_ jobs.WorkspaceScoped = ParticipantBackfillWorkspaceArgs{}
	_ jobs.WorkspaceScoped = PrivacyRetentionWorkspaceArgs{}
	_ jobs.WorkspaceScoped = SiteDeepReadArgs{}
	_ jobs.WorkspaceScoped = TelegramIngestArgs{}
	_ jobs.WorkspaceScoped = TelegramPollArgs{}
	_ jobs.WorkspaceScoped = TimeScanWorkspaceArgs{}
	_ jobs.WorkspaceScoped = VoiceBuildArgs{}
	_ jobs.WorkspaceScoped = WebhookRetryWorkspaceArgs{}
)
