// Code generated by tools/gen-jobs from api/jobs.yaml. DO NOT EDIT.

package compose

import (
	"github.com/riverqueue/river"

	"github.com/gradionhq/margince/backend/internal/platform/jobs"
)

// jobContractHash is the sha256 of api/jobs.yaml this file was generated
// from — the same fingerprint jobs.JobContractHash carries, so a stale
// half of the pair is visible without diffing the two tables.
const jobContractHash = "daaff06fb1ad9a0927ad7b513bef40d174dbf7bb328f89b1bfe408e35c621f30"

// declaredJobArgs is every args type api/jobs.yaml declares, and nothing
// else. A new job kind that is not in the file cannot satisfy it, so it
// cannot reach addDeclaredWorker and cannot be registered — the failure is
// a compile error at the registration site rather than a job silently
// running on River's default timeout.
type declaredJobArgs interface {
	river.JobArgs

	AgentSchedulerArgs |
		AgentSchedulerWorkspaceArgs |
		AiModelRateRefreshArgs |
		CaptureAutoEnrichSweepArgs |
		CaptureAutoEnrichWorkspaceArgs |
		CaptureBackfillArgs |
		CaptureClassifyArgs |
		CaptureClassifyWorkspaceArgs |
		CounterpartyVerdictArgs |
		CounterpartyVerdictWorkspaceArgs |
		CaptureDigestArgs |
		CaptureDigestWorkspaceArgs |
		CaptureEnrichArgs |
		CaptureEnrichWorkspaceArgs |
		CaptureSyncArgs |
		CloseDateSweepArgs |
		CloseDateWorkspaceArgs |
		SendEmailArgs |
		EmbedDriftSweepArgs |
		EmbedDriftWorkspaceArgs |
		EmbedReindexArgs |
		EmbedReindexWorkspaceArgs |
		FollowUpReconcileArgs |
		FollowUpWorkspaceArgs |
		FxRateRefreshArgs |
		GmailSyncArgs |
		GmailWatchArgs |
		GmailWatchRenewArgs |
		GraphEdgeReconcileArgs |
		GraphEdgeWorkspaceArgs |
		IdempotencyRetentionArgs |
		IdempotencyRetentionWorkspaceArgs |
		LinkedInRematchArgs |
		LinkedInRematchWorkspaceArgs |
		OrgNamePromotionArgs |
		OrgNamePromotionWorkspaceArgs |
		OverlayReconcileArgs |
		OverlayReconcileWorkspaceArgs |
		OverlayRefetchArgs |
		ParticipantBackfillArgs |
		ParticipantBackfillWorkspaceArgs |
		PrivacyRetentionArgs |
		PrivacyRetentionWorkspaceArgs |
		SiteDeepReadArgs |
		TelegramIngestArgs |
		TelegramPollArgs |
		TelegramPollSweepArgs |
		TimeScanArgs |
		TimeScanWorkspaceArgs |
		VoiceBuildArgs |
		VoiceBuildRetryArgs |
		WebhookRetryArgs |
		WebhookRetryWorkspaceArgs
}

// addDeclaredWorker registers one worker for a DECLARED kind. Every worker
// the runner assembles goes through here, so the set of kinds this build
// can work is exactly the set api/jobs.yaml declares.
func addDeclaredWorker[T declaredJobArgs](workers *river.Workers, w river.Worker[T]) {
	river.AddWorker(workers, w)
}

// The declared dispatchers: each enumerates the fleet and enqueues, and does
// no tenant work of its own.
var (
	_ jobs.FleetWide = AgentSchedulerArgs{}
	_ jobs.FleetWide = CaptureAutoEnrichSweepArgs{}
	_ jobs.FleetWide = CaptureClassifyArgs{}
	_ jobs.FleetWide = CounterpartyVerdictArgs{}
	_ jobs.FleetWide = CaptureDigestArgs{}
	_ jobs.FleetWide = CaptureEnrichArgs{}
	_ jobs.FleetWide = CloseDateSweepArgs{}
	_ jobs.FleetWide = EmbedDriftSweepArgs{}
	_ jobs.FleetWide = EmbedReindexArgs{}
	_ jobs.FleetWide = FollowUpReconcileArgs{}
	_ jobs.FleetWide = GmailSyncArgs{}
	_ jobs.FleetWide = GmailWatchArgs{}
	_ jobs.FleetWide = GraphEdgeReconcileArgs{}
	_ jobs.FleetWide = IdempotencyRetentionArgs{}
	_ jobs.FleetWide = LinkedInRematchArgs{}
	_ jobs.FleetWide = OrgNamePromotionArgs{}
	_ jobs.FleetWide = OverlayReconcileArgs{}
	_ jobs.FleetWide = ParticipantBackfillArgs{}
	_ jobs.FleetWide = PrivacyRetentionArgs{}
	_ jobs.FleetWide = TelegramPollSweepArgs{}
	_ jobs.FleetWide = TimeScanArgs{}
	_ jobs.FleetWide = VoiceBuildRetryArgs{}
	_ jobs.FleetWide = WebhookRetryArgs{}
)

// The declared workspace-scoped kinds: each carries exactly one tenant's
// pass and says which in its own args.
var (
	_ jobs.WorkspaceScoped = AgentSchedulerWorkspaceArgs{}
	_ jobs.WorkspaceScoped = AiModelRateRefreshArgs{}
	_ jobs.WorkspaceScoped = CaptureAutoEnrichWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureBackfillArgs{}
	_ jobs.WorkspaceScoped = CaptureClassifyWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CounterpartyVerdictWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureDigestWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureEnrichWorkspaceArgs{}
	_ jobs.WorkspaceScoped = CaptureSyncArgs{}
	_ jobs.WorkspaceScoped = CloseDateWorkspaceArgs{}
	_ jobs.WorkspaceScoped = SendEmailArgs{}
	_ jobs.WorkspaceScoped = EmbedDriftWorkspaceArgs{}
	_ jobs.WorkspaceScoped = EmbedReindexWorkspaceArgs{}
	_ jobs.WorkspaceScoped = FollowUpWorkspaceArgs{}
	_ jobs.WorkspaceScoped = FxRateRefreshArgs{}
	_ jobs.WorkspaceScoped = GmailWatchRenewArgs{}
	_ jobs.WorkspaceScoped = GraphEdgeWorkspaceArgs{}
	_ jobs.WorkspaceScoped = IdempotencyRetentionWorkspaceArgs{}
	_ jobs.WorkspaceScoped = LinkedInRematchWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OrgNamePromotionWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OverlayReconcileWorkspaceArgs{}
	_ jobs.WorkspaceScoped = OverlayRefetchArgs{}
	_ jobs.WorkspaceScoped = ParticipantBackfillWorkspaceArgs{}
	_ jobs.WorkspaceScoped = PrivacyRetentionWorkspaceArgs{}
	_ jobs.WorkspaceScoped = SiteDeepReadArgs{}
	_ jobs.WorkspaceScoped = TelegramIngestArgs{}
	_ jobs.WorkspaceScoped = TelegramPollArgs{}
	_ jobs.WorkspaceScoped = TimeScanWorkspaceArgs{}
	_ jobs.WorkspaceScoped = VoiceBuildArgs{}
	_ jobs.WorkspaceScoped = WebhookRetryWorkspaceArgs{}
)
