// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extensions.gen.ts, through tsconfig's
// "@composition/extensions" alias; a composed lane repoints that alias at
// build/composition/frontend/ — the TypeScript mirror of what GOWORK does for
// the Go lane.
//
// Descriptors only. A unit ships no TSX: what an installation composes into the
// SPA is the set of governed operations its contract fragments publish, read out
// of the MERGED contracts at generation time — the same source the routes, the
// agent tools and the unit manifests derive from, so a screen cannot advertise an
// operation the server does not serve.

/** One governed operation an enabled unit's contract fragment publishes. */
export type ExtensionVerbDescriptor = {
  readonly operationId: string;
  readonly route: string;
  readonly method: string;
  readonly title: string;
  readonly version: string;
  /**
   * The RBAC object the operation gates on, or "" when it gates on none.
   *
   * A plain string, not a union: this file is generated, and the generator
   * cannot enumerate what a unit will declare. app/extensions.ts narrows it
   * into the capability vocabulary, which is where the ext_ grammar is
   * checked once.
   */
  readonly rbacObject: string;
};

/** One enabled extension unit, as the composed installation publishes it. */
export type ExtensionDescriptor = {
  readonly name: string;
  readonly verbs: readonly ExtensionVerbDescriptor[];
};

export const extensions: readonly ExtensionDescriptor[] = [];
