// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extlocales.gen.ts, through tsconfig's
// "@composition/copy" alias; a composed lane repoints that alias at
// build/composition/frontend/.
//
// Every enabled unit's own copy, per locale. A unit ships extensions/<name>/
// frontend/i18n/<locale>.json and this merges them, so there is still ONE
// catalogue, one lookup and one missing-key gate — and the strings travel with
// the unit rather than staying behind when it is removed. Core keys win on a
// collision, and a unit's keys are namespaced to the unit, so a unit cannot
// rewrite core copy even if that ordering were ever loosened.

export const extensionCopy = {};
