// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extscreens.gen.ts, through tsconfig's
// "@composition/screens" alias; a composed lane repoints that alias at
// build/composition/frontend/.
//
// Which unit package renders which unit. A unit ships its screen in its own
// frontend/ layer — a pnpm workspace package named @margince-ext/<unit> — and
// this registry is the only place the SPA learns it exists. A composed unit
// absent from this map is not an error: App.tsx falls through to the generic
// published-operations card, which is what a unit with no bespoke screen gets.

export const extensionScreens = {};
