// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (tools/gen-composition). Bare go builds resolve this module's
// committed vanilla stub (composition/ at the repo root) via backend/go.mod's replace;
// composed builds use the generated module under build/composition/ via its go.work.

package composition

import (
	"github.com/gradionhq/margince/backend/pkg/extension"
)

// Extensions returns the composed extension set for this installation;
// vanilla (an empty extensions/ tree) composes none.
func Extensions() []extension.Extension {
	return nil
}
