/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The closed set of domain events a webhook subscription can select. Phase 4 fills this out; today it carries the pilot event only.
         * @enum {string}
         */
        SubscribableEventType: "deal.stage_changed";
        /** @description Who or what caused the event, as exposed publicly. */
        WebhookActor: {
            /** @description Actor kind (e.g. human, agent, connector). */
            type: string;
        };
        /** @description The primary entity the event concerns. */
        WebhookEntityRef: {
            /** @description Entity kind (e.g. deal, person, organization). */
            type: string;
            /**
             * Format: uuid
             * @description Stable identifier of the entity.
             */
            id: string;
        };
        /** @description The public wrapper around every delivered event payload. This is the exact JSON shape a subscriber receives; it carries no internal metadata. */
        WebhookDeliveryEnvelope: {
            /**
             * Format: uuid
             * @description Unique id of this event occurrence.
             */
            event_id: string;
            /** @description The event type (a SubscribableEventType value). */
            type: string;
            /** @description Schema version of the payload in data. */
            version: number;
            /**
             * Format: date-time
             * @description When the event occurred (RFC 3339).
             */
            occurred_at: string;
            actor: components["schemas"]["WebhookActor"];
            entity: components["schemas"]["WebhookEntityRef"];
            /**
             * Format: uuid
             * @description Correlates all events emitted for one originating request.
             */
            correlation_id: string;
            /** @description The typed event payload (one of the WebhookPayload* schemas). */
            data: Record<string, never>;
        };
        /** @description Payload for deal.stage_changed — a deal advanced between stages. */
        WebhookPayloadDealStageChanged: {
            /**
             * Format: uuid
             * @description The deal that moved.
             */
            deal_id: string;
            /**
             * Format: uuid
             * @description Pipeline the deal belongs to.
             */
            pipeline_id: string;
            /**
             * Format: uuid
             * @description Stage the deal left (absent on first placement).
             */
            from_stage_id?: string;
            /**
             * Format: uuid
             * @description Stage the deal entered.
             */
            to_stage_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
