/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The closed set of domain event types a webhook subscription may select — every subscribable event across the deal, offer, pipeline/stage, person/organization, lead, activities, consent/privacy, signals, ai voice, identity, and overlay families. A subscription's event-type filter is validated against this set; an unlisted type cannot be subscribed to.
         * @enum {string}
         */
        SubscribableEventType: "deal.created" | "deal.owner_changed" | "deal.stage_changed" | "deal.archived" | "deal.updated" | "deal.restored" | "offer.created" | "offer.sent" | "offer.accepted" | "offer.rejected" | "offer.superseded" | "pipeline.created" | "pipeline.updated" | "pipeline.archived" | "stage.created" | "stage.updated" | "stage.archived" | "person.created" | "person.archived" | "person.merged" | "person.updated" | "person.restored" | "organization.created" | "organization.archived" | "organization.merged" | "organization.updated" | "lead.created" | "lead.disqualified" | "lead.promoted" | "lead.updated" | "activity.captured" | "activity.archived" | "activity.updated" | "engagement.reply" | "consent.changed" | "retention.applied" | "signal.detected" | "signal.resolved" | "voice.profile_created" | "voice.profile_updated" | "voice.profile_archived" | "voice.corpus_changed" | "voice.build_changed" | "voice.version_changed" | "voice.draft_outcome_recorded" | "user.invited" | "user.deactivated" | "user.reactivated" | "role.changed" | "passport.revoked" | "onboarding.state_changed" | "mirror.conflict" | "mirror.budget_degraded" | "mirror.deleted" | "mirror.write_rejected" | "incumbent.connected" | "incumbent.disconnected" | "approval.requested" | "approval.decided" | "coldstart.read_back_proposed" | "coldstart.accepted" | "coldstart.rejected" | "audit.appended";
        /** @description Who or what caused the event, as exposed publicly. */
        PublicEventActor: {
            /** @description Actor kind (e.g. human, agent, connector). */
            type: string;
        };
        /** @description The primary entity the event concerns. */
        PublicEventEntityRef: {
            /** @description Entity kind (e.g. deal, person, organization). */
            type: string;
            /**
             * Format: uuid
             * @description Stable identifier of the entity.
             */
            id: string;
        };
        /** @description The public wrapper around every delivered event payload. This is the exact JSON shape a subscriber receives; it carries no internal metadata. */
        PublicEventEnvelope: {
            /**
             * Format: uuid
             * @description Unique id of this event occurrence.
             */
            event_id: string;
            /** @description The event type (a SubscribableEventType value). */
            type: string;
            /** @description Schema version of the payload in data. */
            version: number;
            /**
             * Format: date-time
             * @description When the event occurred (RFC 3339).
             */
            occurred_at: string;
            actor: components["schemas"]["PublicEventActor"];
            entity: components["schemas"]["PublicEventEntityRef"];
            /**
             * Format: uuid
             * @description Correlates all events emitted for one originating request.
             */
            correlation_id: string;
            /** @description The typed event payload (one of the PublicEvent* schemas). */
            data: Record<string, never>;
        };
        /** @description Payload for deal.created — a deal was opened. */
        PublicEventDealCreated: {
            /** @description The deal's name at creation. */
            name: string;
        };
        /** @description Payload for deal.owner_changed — the deal's owner was reassigned. Emitted instead of (never alongside) deal.updated for the owner_id field (events.md §5.3). */
        PublicEventDealOwnerChanged: {
            /**
             * Format: uuid
             * @description The new owner.
             */
            to_owner_id: string;
            /**
             * Format: uuid
             * @description The previous owner (absent when the deal had none).
             */
            from_owner_id?: string;
        };
        /** @description Payload for deal.stage_changed — a deal advanced between stages. Carries the amount/win-probability snapshot frozen at the moment of the move so consumers (the trajectory view, the overnight stalled/forecast sweep, the automation trigger keyed on to_status) never need a read-back. */
        PublicEventDealStageChanged: {
            /**
             * Format: uuid
             * @description Stage the deal left (absent on first placement).
             */
            from_stage_id?: string;
            /**
             * Format: uuid
             * @description Stage the deal entered.
             */
            to_stage_id: string;
            /** @description Deal status before the move (open | won | lost). */
            from_status: string;
            /** @description Deal status after the move (open | won | lost) — the field the automation trigger keys on (automation/handlers_event.go). */
            to_status: string;
            /**
             * Format: int64
             * @description The deal's amount, frozen at the moment of the move.
             */
            amount_minor_at_change?: number;
            /** @description The deal's currency, frozen at the moment of the move. */
            currency_at_change?: string;
            /** @description The target stage's win probability, frozen at the moment of the move. */
            win_probability: number;
        };
        /** @description Payload for deal.archived — a deal was archived. Carries no data. */
        PublicEventDealArchived: Record<string, never>;
        /** @description Payload for deal.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, an accepted-offer amount sync, a close-date-correction note, a relationship delta), so the honest shape is a change-set map rather than a fixed field list. */
        PublicEventDealUpdated: {
            /** @description What this update touched, incl. runtime cf_* custom fields. The value shape depends on the emit site: a column patch carries a flat field → new-value entry, while the recompute/routing/relationship sites carry a `{delta: {...}}` sub-object (occasionally with a sibling `source`). Read a key's value as either form. */
            changed_fields: {
                [key: string]: unknown;
            };
        };
        /** @description Payload for deal.restored. Never emitted today (no restore path exists for deal); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it. */
        PublicEventDealRestored: Record<string, never>;
        /** @description Payload for offer.created — a new Angebot revision was opened (either the first revision, via CreateOffer, or a fresh draft revision minted by RegenerateOffer). */
        PublicEventOfferCreated: {
            /**
             * Format: uuid
             * @description The created offer revision.
             */
            offer_id: string;
            /**
             * Format: uuid
             * @description The deal this offer belongs to.
             */
            deal_id: string;
            /** @description This offer's revision number (1 for a first offer). */
            revision: number;
            /** @description The offer's currency. */
            currency: string;
            /** @description Where this offer originated (e.g. manual, ai). */
            source: string;
            /** @description The principal that created this revision. */
            captured_by: string;
        };
        /** @description Payload for offer.sent — a draft offer left the workspace. Carries the FX rate frozen at send time (RT-PR-C2) so consumers never need a read-back for the native-currency-to-base conversion. */
        PublicEventOfferSent: {
            /**
             * Format: uuid
             * @description The sent offer.
             */
            offer_id: string;
            /**
             * Format: uuid
             * @description The deal this offer belongs to.
             */
            deal_id: string;
            /** @description This offer's revision number. */
            revision?: number;
            /**
             * Format: int64
             * @description The offer's gross total at send time.
             */
            gross_minor?: number;
            /** @description Native→base rate frozen at send (RT-PR-C2). Decimal-as-string to avoid float rounding. */
            fx_rate_to_base: string;
            /**
             * Format: date
             * @description The offer's validity date (absent when unset).
             */
            valid_until?: string;
        };
        /** @description Payload for offer.accepted — a sent offer was accepted. The deal's headline amount is synced from this offer's gross in the same transaction (see deal.updated on the paired deal entity). */
        PublicEventOfferAccepted: {
            /**
             * Format: uuid
             * @description The accepted offer.
             */
            offer_id: string;
            /**
             * Format: uuid
             * @description The deal this offer belongs to.
             */
            deal_id: string;
            /** @description This offer's revision number. */
            revision?: number;
            /**
             * Format: int64
             * @description The offer's gross total, now also the deal's amount.
             */
            gross_minor?: number;
        };
        /** @description Payload for offer.rejected — a sent offer was rejected. */
        PublicEventOfferRejected: {
            /**
             * Format: uuid
             * @description The rejected offer.
             */
            offer_id: string;
            /**
             * Format: uuid
             * @description The deal this offer belongs to.
             */
            deal_id: string;
            /** @description This offer's revision number. */
            revision?: number;
            /** @description The optional rejection reason (absent when none was given). */
            reason?: string;
        };
        /** @description Payload for offer.superseded — a sent offer was regenerated into a fresh draft revision (B-E03.19) and marked superseded; the new revision arrives as its own offer.created event. */
        PublicEventOfferSuperseded: {
            /**
             * Format: uuid
             * @description The superseded (prior) offer revision.
             */
            offer_id: string;
            /**
             * Format: uuid
             * @description The deal this offer belongs to.
             */
            deal_id: string;
            /** @description The superseded revision number. */
            from_revision?: number;
            /** @description The new revision number minted by the regenerate. */
            to_revision: number;
        };
        /** @description One initial stage as declared on a pipeline.created event — the stage's own stage.created is NOT separately emitted for these (events.md §5.3b: one pipeline.created carries the whole set). */
        PublicEventPipelineCreatedStage: {
            /** @description The stage's name. */
            name: string;
            /** @description The stage's position within the pipeline. */
            position: number;
            /** @description The stage's semantic (open | won | lost). */
            semantic: string;
        };
        /** @description Payload for pipeline.created — a pipeline was created with its initial stage set in the same transaction. */
        PublicEventPipelineCreated: {
            /** @description The pipeline's name. */
            name: string;
            /** @description Whether this pipeline is the workspace default. */
            is_default: boolean;
            /** @description The pipeline's initial stages, in the order created. */
            stages: components["schemas"]["PublicEventPipelineCreatedStage"][];
        };
        /** @description Payload for pipeline.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat name/is_default/position patch from UpdatePipeline, or a stage_positions reorder map from UpdateStage when a stage's position changes), so the honest shape is a change-set map rather than a fixed field list. */
        PublicEventPipelineUpdated: {
            /** @description Field name → new value for whatever this update touched (name, is_default, position, or stage_positions). */
            changed_fields: {
                [key: string]: unknown;
            };
        };
        /** @description Payload for pipeline.archived. Never emitted today (no archive path exists for pipeline); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it. */
        PublicEventPipelineArchived: Record<string, never>;
        /** @description Payload for stage.created — a stage was added to a pipeline. */
        PublicEventStageCreated: {
            /**
             * Format: uuid
             * @description The pipeline this stage belongs to.
             */
            pipeline_id: string;
            /** @description The stage's name. */
            name: string;
            /** @description The stage's position within the pipeline. */
            position: number;
            /** @description The stage's semantic (open | won | lost). */
            semantic: string;
            /** @description The stage's win probability (won=100, lost=0, open=0..100). */
            win_probability: number;
        };
        /** @description Payload for stage.updated — a BOUNDED delta: UpdateStage's known mutable fields (name, semantic, win_probability) each carried only when this update touched them. A position change is instead published as ONE pipeline.updated with a stage_positions delta (never an N-way stage.updated), so position never appears here. */
        PublicEventStageUpdated: {
            /**
             * Format: uuid
             * @description The pipeline this stage belongs to.
             */
            pipeline_id: string;
            /** @description The stage's new name (absent when this update did not touch it). */
            name?: string;
            /** @description The stage's new semantic (absent when this update did not touch it). */
            semantic?: string;
            /** @description The stage's new win probability (absent when this update did not touch it). */
            win_probability?: number;
        };
        /** @description Payload for stage.archived. Never emitted today (no archive path exists for stage); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it. */
        PublicEventStageArchived: Record<string, never>;
        /** @description How many child rows on each side were repointed from the merged- away person onto the survivor (people/merge.go relinkCounts). */
        PublicEventPersonMergedRelinkCounts: {
            /**
             * Format: int64
             * @description person_email rows relinked.
             */
            emails: number;
            /**
             * Format: int64
             * @description person_phone rows relinked.
             */
            phones: number;
            /**
             * Format: int64
             * @description relationship edge rows relinked.
             */
            relationships: number;
            /**
             * Format: int64
             * @description activity_link rows relinked.
             */
            activity_links: number;
        };
        /** @description Payload for person.created — a person was created. */
        PublicEventPersonCreated: {
            /** @description The person's name at creation. */
            full_name: string;
        };
        /** @description Payload for person.archived — a person was archived. Carries no data. */
        PublicEventPersonArchived: Record<string, never>;
        /** @description Payload for person.merged — two person records collapsed into one (the §1.3 merge); neither person.updated nor person.archived can say this, so it is its own verb. */
        PublicEventPersonMerged: {
            /**
             * Format: uuid
             * @description The merged-away (source) person, retired but still fetchable by id.
             */
            merged_from_id: string;
            /**
             * Format: uuid
             * @description The survivor (target) person.
             */
            merged_into_id: string;
            relinked: components["schemas"]["PublicEventPersonMergedRelinkCounts"];
        };
        /** @description Payload for person.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, a lead-promotion conversion note, a signature-enrichment fill, a relationship delta), so the honest shape is a change-set map rather than a fixed field list. */
        PublicEventPersonUpdated: {
            /** @description What this update touched, incl. runtime cf_* custom fields. The value shape depends on the emit site: a column patch carries a flat field → new-value entry, while the recompute/routing/relationship sites carry a `{delta: {...}}` sub-object (occasionally with a sibling `source`). Read a key's value as either form. */
            changed_fields: {
                [key: string]: unknown;
            };
        };
        /** @description Payload for person.restored. Never emitted today (no restore path exists for person); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it. */
        PublicEventPersonRestored: Record<string, never>;
        /** @description Payload for organization.created — a UNION across five emit sites (a direct create, the capture auto-create engine, the anchor company save, the site-read confirmation, and the cold-start profile apply), each of which sets only its own subset; every field is therefore optional. */
        PublicEventOrganizationCreated: {
            /** @description The organization's display name at creation (absent when the site never set one). */
            display_name?: string;
            /** @description The organization's primary domain (cold-start apply only). */
            primary_domain?: string;
            /** @description The fields the creating site applied (company save / site-read confirmation only). */
            delta?: {
                [key: string]: unknown;
            };
            /** @description Where this organization originated (e.g. human, site_read). */
            source?: string;
            /** @description The source page this organization was read from (site-read confirmation only). */
            source_url?: string;
            /**
             * Format: uuid
             * @description The site-read that produced this organization (site-read confirmation only).
             */
            site_read_id?: string;
            /** @description Whether this is the installation's own anchor organization (company save only). */
            anchor?: boolean;
            /** @description The principal that created this organization. */
            captured_by?: string;
        };
        /** @description Payload for organization.archived — an organization was archived. Carries no data. */
        PublicEventOrganizationArchived: Record<string, never>;
        /** @description Payload for organization.merged — two organization records collapsed into one (the §1.3 merge); neither organization.updated nor organization.archived can say this, so it is its own verb. */
        PublicEventOrganizationMerged: {
            /**
             * Format: uuid
             * @description The merged-away (source) organization, retired but still fetchable by id.
             */
            merged_from_id: string;
            /**
             * Format: uuid
             * @description The survivor (target) organization.
             */
            merged_into_id: string;
        };
        /** @description Payload for organization.updated — an OPEN envelope: eight emit sites carry divergent shapes (a flat column patch, the anchor company save's field delta, the partner extension's nested delta, enrichment/deep-read applies, a relationship delta), so the honest shape is a change-set map rather than a fixed field list. */
        PublicEventOrganizationUpdated: {
            /** @description What this update touched, incl. runtime cf_* custom fields. The value shape depends on the emit site: a column patch carries a flat field → new-value entry, while the recompute/routing/relationship sites carry a `{delta: {...}}` sub-object (occasionally with a sibling `source`). Read a key's value as either form. */
            changed_fields: {
                [key: string]: unknown;
            };
        };
        /** @description Payload for lead.created — a lead was created. Two emit sites: a direct create (people/lead.go) that sets no fields, and the capture auto-create engine (capture/sink.go) that names its originating source system; source_system is therefore optional. */
        PublicEventLeadCreated: {
            /** @description The originating source system (capture auto-create only; absent on a direct create). */
            source_system?: string;
        };
        /** @description Payload for lead.disqualified — a lead was disqualified. Carries no data. */
        PublicEventLeadDisqualified: Record<string, never>;
        /** @description Payload for lead.promoted — the lead's genuine-engagement promotion into the context graph (events.md §5.5); its own verb, never a lead.updated, since neither person.created nor person.updated on its own says a lead crossed this line. */
        PublicEventLeadPromoted: {
            /**
             * Format: uuid
             * @description The person this lead promoted into (fresh or an existing survivor).
             */
            promoted_person_id: string;
            /** @description Whether promotion created a new person or merged into an existing one: created or merged. */
            dedupe_outcome: string;
            /** @description The genuine-engagement trigger that authorized promotion: inbound_reply, meeting_booked, meeting_held, or human_qualify. */
            trigger: string;
            /**
             * Format: uuid
             * @description The inbound activity that evidenced the trigger (absent for a human_qualify with no linked activity).
             */
            evidence_ref?: string;
        };
        /** @description Payload for lead.updated — an OPEN envelope: emit sites carry divergent shapes (a flat column patch that includes runtime cf_* custom-field columns, and behavioral-recompute/routing deltas), so the honest shape is a change-set map rather than a fixed field list. */
        PublicEventLeadUpdated: {
            /** @description What this update touched, incl. runtime cf_* custom fields. The value shape depends on the emit site: a column patch carries a flat field → new-value entry, while the recompute/routing/relationship sites carry a `{delta: {...}}` sub-object (occasionally with a sibling `source`). Read a key's value as either form. */
            changed_fields: {
                [key: string]: unknown;
            };
        };
        /** @description Payload for activity.captured — the first-class capture verb, emitted instead of (never alongside) a generic activity.created (events.md §1). Two emit sites: the direct-log path (activities/activity.go) that sets kind only, and the capture ingestion path (capture/sink.go) that also names its originating source system. */
        PublicEventActivityCaptured: {
            /** @description The activity kind (email | call | meeting | note | whatsapp | telegram). Decoded by automation/handlers_event.go's post_meeting_recap trigger — this field's JSON key is a binding contract, not just documentation. */
            kind: string;
            /** @description The originating source system (capture ingestion only; absent on a direct log). */
            source_system?: string;
        };
        /** @description Payload for activity.archived — an activity was archived. Carries no data. */
        PublicEventActivityArchived: Record<string, never>;
        /** @description The entity an activity was relinked onto (activities/lifecycle.go's RelinkActivity) — an association change, not a re-capture, so it travels as one changed_fields key rather than its own event verb. */
        PublicEventActivityRelinkedRef: {
            /** @description The relink target's kind (person | organization | deal | lead). */
            entity_type: string;
            /**
             * Format: uuid
             * @description The relink target's id.
             */
            entity_id: string;
        };
        /** @description activity.updated's BOUNDED delta: UpdateActivity's known mutable fields (subject, body, occurred_at, due_at, remind_at, assignee_id, is_done) each carried only when this update touched them, plus RelinkActivity's relinked target — a fixed, KNOWN key set (unlike person/organization/deal/lead.updated's genuinely open patch), so it is typed rather than an open map. */
        PublicEventActivityChangedFields: {
            /** @description The activity's new subject (absent when this update did not touch it). */
            subject?: string;
            /** @description Whether the body was touched (a presence flag, not the content — bodies can be large and are never echoed onto the wire). */
            body?: boolean;
            /**
             * Format: date-time
             * @description The activity's new occurred_at (absent when this update did not touch it).
             */
            occurred_at?: string;
            /**
             * Format: date-time
             * @description The activity's new due_at (absent when this update did not touch it).
             */
            due_at?: string;
            /**
             * Format: date-time
             * @description The activity's new remind_at (absent when this update did not touch it).
             */
            remind_at?: string;
            /**
             * Format: uuid
             * @description The activity's new assignee (absent when this update did not touch it).
             */
            assignee_id?: string;
            /** @description The activity's new completion state (absent when this update did not touch it). */
            is_done?: boolean;
            relinked?: components["schemas"]["PublicEventActivityRelinkedRef"];
        };
        /** @description Payload for activity.updated — a BOUNDED delta (unlike the person/organization/deal/lead family's genuinely open patch): UpdateActivity and RelinkActivity together cover a fixed, KNOWN set of inner keys, so changed_fields is a typed struct here, not an open map. */
        PublicEventActivityUpdated: {
            changed_fields: components["schemas"]["PublicEventActivityChangedFields"];
        };
        /** @description Payload for engagement.reply — CAP-FORMULA-1: an inbound message in a thread we previously wrote outbound in is a reply, feeding the engagement signal scoring (capture/sink.go's emitReply). */
        PublicEventEngagementReply: {
            /**
             * Format: uuid
             * @description The prior outbound activity this inbound message replies to.
             */
            matched_outbound_activity_id: string;
            /** @description The channel the reply arrived on (today always email). */
            channel: string;
            /**
             * Format: date-time
             * @description When the reply activity occurred.
             */
            occurred_at: string;
            /** @description The capture natural key (source_system:source_id) this reply was detected from. */
            idempotency_key: string;
            /**
             * Format: uuid
             * @description The already-known person behind the counterparty address (absent when the counterparty resolves only in a follow-up ensure).
             */
            contact_id?: string;
        };
        /** @description Payload for consent.changed — a subject's per-purpose consent state was recorded (consent/store.go's Record). The subject is a person XOR a lead (data-model §7, before promotion) — a RUNTIME choice Record resolves via consentSubject, not a fixed type this schema can name, so this is the first dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity. */
        PublicEventConsentChanged: {
            /**
             * Format: uuid
             * @description The consent purpose this state change applies to.
             */
            purpose_id: string;
            /** @description The purpose's key (e.g. marketing_email). */
            purpose: string;
            /** @description The state now on record (granted | withdrawn). */
            new_state: string;
        };
        /** @description Payload for retention.applied — a retention/erasure action ran against one record. Four emit sites, four different runtime subjects: the embed-call sweep (ai_call), the voice-learning-signal content sweep (voice_learning_signal), a workspace's configured retention policy's object type (activity | deal | lead | person | ai_call_payload), and Art. 17 erasure (person) — none fixed enough for this schema to name, so this is dynamic-entity (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and each emit site supplies its own runtime entity type through storekit.EmitEventForEntity. policy/reason are a union across the sites — both telemetry sweeps set neither, the policy-driven sweep sets policy only, Art. 17 erasure sets reason only. */
        PublicEventRetentionApplied: {
            /** @description The action that ran (archive | anonymize | erase). */
            action: string;
            /**
             * Format: uuid
             * @description The retention policy that drove this action (absent for the fixed embed-call sweep and for Art. 17 erasure, neither of which is policy-configured).
             */
            policy?: string;
            /** @description Why this action ran (Art. 17 erasure only — e.g. dsr_request; absent for both retention-sweep sites). */
            reason?: string;
        };
        /** @description Payload for signal.detected — a signal was created (signals/signal.go's CreateSignal). entity_type/entity_id are DATA fields naming the signal's subject (deal | organization | person) when one is already known at creation time — not the envelope's own entity ref, which is the signal itself (this event's entity type is the static "signal"). Both are absent on a raw signal (only a raw_ref), which enters unresolved and waits for the resolver; resolution_confidence is set only when the signal was created already resolved. */
        PublicEventSignalDetected: {
            /**
             * Format: uuid
             * @description The signal that was detected.
             */
            signal_id: string;
            /** @description The signal kind (stalled_deal | champion_left | reengagement | buying_intent | risk | other). */
            kind: string;
            /** @description Where the raw signal came from (derived | inbound | web | social | deal_room_engagement). */
            source_channel: string;
            /** @description The raw→entity match outcome at creation time (resolved | low_confidence | unresolved | dropped). */
            resolution_state: string;
            /** @description The signal's severity (info | warn | urgent). */
            severity: string;
            /** @description The subject record's type (deal | organization | person) — a payload data field, absent until a raw signal resolves (both entity fields set together). x-go-name avoids colliding with the generated EntityType() method, which names the ENVELOPE'S entity (always "signal"), not this data field. */
            entity_type?: string;
            /**
             * Format: uuid
             * @description The subject record's id — a payload data field, absent until a raw signal resolves.
             */
            entity_id?: string;
            /** @description The match confidence (0–1), set only when created already resolved. */
            resolution_confidence?: number;
        };
        /** @description Payload for signal.resolved — the resolver ran over a signal (signals/resolver.go's Resolve). The verdict IS the candidate count (P12): zero candidates drops the signal (resolved_org_id, resolved_person_id, matched_on, match_confidence all absent); exactly one resolves it to that org (resolved_org_id set, resolved_person_id set only under a recorded consent grant); several flags it low_confidence for review (matched_on/ match_confidence describe the top candidate, resolved_org_id stays absent). */
        PublicEventSignalResolved: {
            /**
             * Format: uuid
             * @description The signal the resolver ran over.
             */
            signal_id: string;
            /** @description The state after resolving (resolved | low_confidence | dropped). */
            resolution_state: string;
            /**
             * Format: uuid
             * @description The organization the signal resolved to (absent when dropped or ambiguous).
             */
            resolved_org_id?: string;
            /**
             * Format: uuid
             * @description The consent-gated person the signal resolved to (absent unless an existing person under a recorded consent grant matched).
             */
            resolved_person_id?: string;
            /** @description The match basis of the top candidate (domain | name | prior_interaction). */
            matched_on?: string;
            /** @description The top candidate's match confidence (0–1). */
            match_confidence?: number;
        };
        /** @description Payload for voice.profile_created — the admitted human opened their one personal Voice DNA profile (ai/voice.go's CreateProfile). Always starts collecting, at maturity zero, with automatic learning off. */
        PublicEventVoiceProfileCreated: {
            /**
             * Format: uuid
             * @description The created profile.
             */
            profile_id: string;
            /**
             * Format: uuid
             * @description The human who owns this profile.
             */
            owner_id: string;
            /** @description The corpus maturity band at creation (collecting, at zero words). */
            maturity: string;
            /** @description Whether automatic learning starts enabled (always false at creation). */
            auto_learning_enabled: boolean;
        };
        /** @description Payload for voice.profile_updated — the owner replaced their human-authored preferences and/or their automatic-learning opt-in (ai/voice.go's UpdateProfile). action names which of the two (or both) this update touched. */
        PublicEventVoiceProfileUpdated: {
            /**
             * Format: uuid
             * @description The updated profile.
             */
            profile_id: string;
            /** @description What this update did (preferences_replaced | learning_enabled | learning_disabled). */
            action: string;
            /**
             * Format: int64
             * @description The profile row's optimistic-concurrency version after this update.
             */
            version: number;
            /** @description The corpus maturity band as of this update. */
            maturity: string;
        };
        /** @description Payload for voice.profile_archived — the owner's profile was soft-deleted (ai/voice.go's ArchiveProfile). */
        PublicEventVoiceProfileArchived: {
            /**
             * Format: uuid
             * @description The archived profile.
             */
            profile_id: string;
            /**
             * Format: uuid
             * @description The human who owned this profile.
             */
            owner_id: string;
            /** @description The profile's derived-artifact version at the moment it was archived. */
            profile_version: number;
        };
        /** @description Payload for voice.corpus_changed — a UNION across four emit sites that all mutate the corpus feeding a profile's build: a source's inclusion/weight was updated (voice_source_mutations.go's recordSourceUpdate), a source was removed (RemoveSource), a source was ingested/re-ingested (voice_source_store.go's recordSourceIngest), or the whole corpus was cleared (voice_source_mutations.go's ClearCorpus). source_id/origin/register name the touched source and are therefore absent on the clear site, which acts on the corpus as a whole. */
        PublicEventVoiceCorpusChanged: {
            /**
             * Format: uuid
             * @description The profile whose corpus changed.
             */
            profile_id: string;
            /**
             * Format: uuid
             * @description The source this change touched (absent on the clear site, which has no single source).
             */
            source_id?: string;
            /** @description What happened to the corpus (included | excluded | removed | cleared). */
            action: string;
            /** @description The touched source's origin (manual | capture) (absent on the clear site). */
            origin?: string;
            /** @description The touched source's register (email | social | long_form | spoken | general) (absent on the clear site). */
            register?: string;
            /** @description The eligible-word-count change this action caused (may be negative). */
            word_delta: number;
            /** @description The corpus's eligible source count after this change. */
            source_count: number;
            /** @description The corpus's content hash after this change. */
            source_hash: string;
        };
        /** @description Payload for voice.build_changed — a Voice DNA build was queued or an already-pending one was returned in place of a duplicate request (ai/voice_lifecycle.go's RequestBuild). stage/result_version/ status_code/next_attempt_at describe an in-flight or deferred build and are therefore absent on a freshly-queued one. */
        PublicEventVoiceBuildChanged: {
            /**
             * Format: uuid
             * @description The profile this build belongs to.
             */
            profile_id: string;
            /**
             * Format: uuid
             * @description The build row.
             */
            build_id: string;
            /** @description The human-approved reason for this build (onboarding | manual). */
            reason: string;
            /** @description The build's status (queued | deferred | running | completed | failed). */
            status: string;
            /** @description The build's current pipeline stage (absent before it starts running). */
            stage?: string;
            /** @description The corpus content hash this build was requested against. */
            source_hash: string;
            /** @description The corpus's eligible source count this build was requested against. */
            source_count: number;
            /** @description The profile version this build produced (absent until the build completes). */
            result_version?: number;
            /** @description The recommended next step for this build's candidate. */
            candidate_action: string;
            /** @description A machine-readable status detail code (absent unless the build failed or deferred). */
            status_code?: string;
            /**
             * Format: date-time
             * @description When a deferred build will next be attempted (absent unless deferred).
             */
            next_attempt_at?: string;
        };
        /** @description Payload for voice.version_changed — a derived Voice DNA version's status changed: minted as a candidate, manually activated, rejected, or restored by rollback (ai/voice_versions.go). predecessor_version is absent for a profile's first version, which has none. */
        PublicEventVoiceVersionChanged: {
            /**
             * Format: uuid
             * @description The profile this version belongs to.
             */
            profile_id: string;
            /** @description This version's number. */
            profile_version: number;
            /** @description The version's status after this change (candidate | active | superseded | rejected). */
            status: string;
            /** @description Why this version was produced (e.g. build | rollback). */
            reason: string;
            /** @description The version this one supersedes (absent for a profile's first version). */
            predecessor_version?: number;
            /** @description The delta's classification against its predecessor (routine | material). */
            classification: string;
            /** @description What happened to this version (auto_activated | manually_activated | rejected | rollback). */
            activation_outcome: string;
        };
        /** @description Payload for voice.draft_outcome_recorded — a drafted-with-voice signal's outcome was recorded (ai/voice_history.go's RecordDraftOutcome), feeding the automatic-learning corpus. */
        PublicEventVoiceDraftOutcomeRecorded: {
            /**
             * Format: uuid
             * @description The profile this learning signal belongs to.
             */
            profile_id: string;
            /** @description The recorded outcome (drafted | sent_unedited | sent_edited | rejected). */
            outcome: string;
            /** @description Whether this draft's final text qualifies as a future corpus source. */
            qualifies_as_source: boolean;
            /** @description How many transformation edits were applied before send (0 for rejected). */
            transformation_count: number;
        };
        /** @description Payload for user.invited — an admin provisioned a new active member with a single-use set-password token (identity/users.go's InviteUser). */
        PublicEventUserInvited: {
            /**
             * Format: uuid
             * @description The invited member.
             */
            user_id: string;
            /** @description The single system role key granted to the new member. */
            role: string;
            /**
             * Format: uuid
             * @description The admin who issued the invite.
             */
            by: string;
        };
        /** @description Payload for user.deactivated — a member's sessions and passports were hard-revoked (identity/users.go's DeactivateUser). reason is the operator-supplied free text, absent when none was given. */
        PublicEventUserDeactivated: {
            /**
             * Format: uuid
             * @description The deactivated member.
             */
            user_id: string;
            /**
             * Format: uuid
             * @description The admin who deactivated the member.
             */
            by: string;
            /** @description The operator-supplied reason (absent when none was given). */
            reason?: string;
        };
        /** @description Payload for user.reactivated — a deactivated member was returned to active (identity/users.go's ReactivateUser). */
        PublicEventUserReactivated: {
            /**
             * Format: uuid
             * @description The reactivated member.
             */
            user_id: string;
            /**
             * Format: uuid
             * @description The admin who reactivated the member.
             */
            by: string;
        };
        /** @description Payload for role.changed — a member's role assignments were replaced with the single target system role (identity/users.go's ChangeUserRole). from_role rides the payload only when the previous state was a single role — a multi-role history has no one "from". */
        PublicEventRoleChanged: {
            /**
             * Format: uuid
             * @description The member whose role changed.
             */
            user_id: string;
            /** @description The role key assigned. */
            to_role: string;
            /**
             * Format: uuid
             * @description The admin who changed the role.
             */
            by: string;
            /** @description The single prior role key (absent when the member held more than one role before this change). */
            from_role?: string;
        };
        /** @description Payload for passport.revoked — an agent passport was hard-revoked (identity/passport.go's RevokePassport), so long-lived consumers drop it within one bus cycle. */
        PublicEventPassportRevoked: {
            /**
             * Format: uuid
             * @description The revoked passport.
             */
            passport_id: string;
            /**
             * Format: uuid
             * @description The human who revoked it (the granting user, or an admin).
             */
            by: string;
        };
        /** @description Payload for onboarding.state_changed — the admitted human's wizard checkpoint was created or advanced (identity/onboarding.go's auditOnboardingState). */
        PublicEventOnboardingStateChanged: {
            /**
             * Format: uuid
             * @description The human whose wizard state this is.
             */
            user_id: string;
            /** @description The chosen onboarding path. */
            path: string;
            /** @description The wizard step this checkpoint reached. */
            step: string;
            /**
             * Format: int64
             * @description The row's optimistic-concurrency version after this checkpoint.
             */
            version: number;
            /** @description Whether the voice-setup step was skipped. */
            voice_skipped: boolean;
            /** @description Whether the incumbent-connect step was skipped. */
            connect_skipped: boolean;
            /** @description Whether the wizard was completed as of this checkpoint. */
            completed: boolean;
        };
        /** @description Payload for mirror.conflict — the reconcile poller (overlay/ reconcile.go's emitMirrorConflict) observed the incumbent CRM had moved a record the mirror's own baseline still called current, an overwrite-worthy divergence (OVA-EVT-1). object_class is the RUNTIME canonical class of the record involved (e.g. "person", "deal") — not a fixed type this schema can name — so this is a dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity. */
        PublicEventMirrorConflict: {
            /** @description The canonical Margince class of the diverged record. */
            object_class: string;
            /** @description The record's incumbent-side natural key. */
            external_id: string;
            /**
             * Format: date-time
             * @description The mirror's prior stored baseline timestamp.
             */
            prior_updated_at: string;
            /**
             * Format: date-time
             * @description The incumbent's reported modification timestamp.
             */
            incumbent_updated_at: string;
        };
        /** @description Payload for mirror.budget_degraded — a force-fresh read fell back to the mirror because the workspace's shared OVB budget had shed to the "shed" band (overlay/freshness.go's emitBudgetDegraded, OVA-EVT-3). The event names the record the degraded read was about; that record's class is a RUNTIME value (the read's own entity ref), so this is a dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity. */
        PublicEventMirrorBudgetDegraded: {
            /** @description The budget band that forced the degrade (currently always "shed"). */
            band: string;
        };
        /** @description Payload for mirror.deleted — continuous sync observed the incumbent report a record deleted, and the mirror purged its cached row, association edges, and visibility projection (overlay/mirrordeletion.go). object_class is the RUNTIME canonical class of the purged record, not a fixed type this schema can name, so this is a dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity. */
        PublicEventMirrorDeleted: {
            /** @description The canonical Margince class of the purged record. */
            object_class: string;
            /** @description The record's incumbent-side natural key. */
            external_id: string;
            /**
             * Format: date-time
             * @description When the incumbent reported the deletion.
             */
            deleted_at: string;
        };
        /** @description Payload for mirror.write_rejected. Never emitted today — reserved for branch 2 (writes to an overlay-mode workspace's incumbent CRM, currently declared unsupported_by_sor); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it. */
        PublicEventMirrorWriteRejected: Record<string, never>;
        /** @description Payload for incumbent.connected — a workspace completed the overlay-mode incumbent-CRM connect flow (overlay/connection.go's insertConnection); the workspace flipped to x_sor_mode=overlay in the same transaction. Unlike the mirror.* events above, this event's subject is always the incumbent_connection row itself — a fixed type — so it is emitted via the plain storekit.EmitEvent. */
        PublicEventIncumbentConnected: {
            /** @description The incumbent CRM system connected (e.g. "hubspot"). */
            incumbent: string;
            /** @description The incumbent account's data-residency region. */
            region: string;
            /** @description The least-privilege OAuth scope set granted. */
            scopes: string[];
            /** @description The connection's status after this change (active). */
            status: string;
        };
        /** @description Payload for incumbent.disconnected — a workspace's active incumbent-CRM connection was revoked (overlay/teardown.go's Disconnect); mirror teardown and credential cleanup follow. This event's subject is always the incumbent_connection row itself — a fixed type — so it is emitted via the plain storekit.EmitEvent. */
        PublicEventIncumbentDisconnected: {
            /** @description The incumbent CRM system disconnected. */
            incumbent: string;
            /** @description The incumbent account's data-residency region. */
            region: string;
            /** @description The connection's status after this change (revoked). */
            status: string;
        };
        /** @description Payload for approval.requested — an agent's 🟡 call was staged pending a human decision (ADR-0036, approvals/staging.go's StageInTx). The staged approval row's own id is the event's entity ref; this payload names what was staged, its polymorphic target, and when the staging lapses into expired if undecided. */
        PublicEventApprovalRequested: {
            /** @description The staged tool/kind name (e.g. advance_deal). */
            kind: string;
            /** @description The human-readable summary the inbox shows. */
            summary: string;
            /** @description The polymorphic entity type the staged action targets. */
            target_entity_type: string;
            /**
             * Format: uuid
             * @description The polymorphic entity id the staged action targets; absent when the staging names no single target row.
             */
            target_entity_id?: string;
            /**
             * Format: date-time
             * @description When this staging lapses into expired if undecided.
             */
            expires_at: string;
        };
        /** @description Payload for approval.decided — a human approved or rejected a staged approval (approvals/decide.go). verdict and edited_change are decoded BY NAME outside this module — automation's blocked-run consumer matches verdict (automation/engine_blocked.go), the Surface-B runner's resume consumer reads edited_change (compose/runnerservice.go) — see the JSON-tag regression tests in internal/modules/webhooks. edited/diff_hash/edited_change are present only on the ADR-0036 §4 modify-then-approve arm, where the human's edited payload replaced the staged change under a freshly computed diff_hash. */
        PublicEventApprovalDecided: {
            /** @description The decided staging's kind. */
            kind: string;
            /** @description The decision outcome (approved | rejected). */
            verdict: string;
            /**
             * Format: uuid
             * @description The deciding human's user id.
             */
            decided_by: string;
            /** @description True when the human edited the proposed change before approving (present only on the modify-then-approve arm). */
            edited?: boolean;
            /** @description The edited change's freshly computed diff_hash (present only on the modify-then-approve arm). */
            diff_hash?: string;
            /** @description The human's edited version of the proposed change (present only on the modify-then-approve arm) — an OPEN object: its shape is whatever the staged kind's proposed_change carries, so it stays a raw map rather than a narrowly typed struct (the runner's resume consumer decodes it as json.RawMessage off the wire; a fixed struct here would drop fields a future staging kind adds). */
            edited_change?: {
                [key: string]: unknown;
            };
        };
        /** @description Payload for coldstart.read_back_proposed — a cold-start read-back was staged as a "coldstart" approval (compose/coldstart.go's stage, carried through approvals/staging.go's Announce alongside approval.requested on the same audit row). Carries only the read-back's shape, never the extracted field values or the pasted source text/statement — tenant data never rides an announced event. */
        PublicEventColdstartReadBackProposed: {
            /** @description How many fields the read-back grounded. */
            field_count: number;
            /** @description The read-back's source URL (url-kind read-backs only). */
            source_url?: string;
            /** @description The read-back's source kind (text | self_description); absent for a url-kind read-back, which sets source_url instead. */
            source_kind?: string;
        };
        /** @description Payload for coldstart.accepted — a human accepted a staged cold-start read-back (approvals/decide.go's kind-decided echo, emitted on the same audit row as approval.decided). */
        PublicEventColdstartAccepted: {
            /**
             * Format: uuid
             * @description The decided approval's id (same as the envelope's entity ref).
             */
            approval_id: string;
            /**
             * Format: uuid
             * @description The deciding human's user id.
             */
            decided_by: string;
        };
        /** @description Payload for coldstart.rejected — a human rejected a staged cold-start read-back (approvals/decide.go's kind-decided echo, emitted on the same audit row as approval.decided). */
        PublicEventColdstartRejected: {
            /**
             * Format: uuid
             * @description The decided approval's id (same as the envelope's entity ref).
             */
            approval_id: string;
            /**
             * Format: uuid
             * @description The deciding human's user id.
             */
            decided_by: string;
        };
        /** @description Payload for audit.appended — not currently delivered: there is no emit site for this type, and none is planned for V1. It exists so the §5 catalog (events.Types()) is completely covered by a payload schema (the whole-catalog coverage gate), never carrying a subscribable type with no contract. An empty payload by design — the audit ledger row it would announce is workspace-level (its subject is resolved back under the receiver's own scope), so no record detail rides the event. */
        PublicEventAuditAppended: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const subscribableEventTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SubscribableEventType"]> = ["deal.created", "deal.owner_changed", "deal.stage_changed", "deal.archived", "deal.updated", "deal.restored", "offer.created", "offer.sent", "offer.accepted", "offer.rejected", "offer.superseded", "pipeline.created", "pipeline.updated", "pipeline.archived", "stage.created", "stage.updated", "stage.archived", "person.created", "person.archived", "person.merged", "person.updated", "person.restored", "organization.created", "organization.archived", "organization.merged", "organization.updated", "lead.created", "lead.disqualified", "lead.promoted", "lead.updated", "activity.captured", "activity.archived", "activity.updated", "engagement.reply", "consent.changed", "retention.applied", "signal.detected", "signal.resolved", "voice.profile_created", "voice.profile_updated", "voice.profile_archived", "voice.corpus_changed", "voice.build_changed", "voice.version_changed", "voice.draft_outcome_recorded", "user.invited", "user.deactivated", "user.reactivated", "role.changed", "passport.revoked", "onboarding.state_changed", "mirror.conflict", "mirror.budget_degraded", "mirror.deleted", "mirror.write_rejected", "incumbent.connected", "incumbent.disconnected", "approval.requested", "approval.decided", "coldstart.read_back_proposed", "coldstart.accepted", "coldstart.rejected", "audit.appended"];
export type operations = Record<string, never>;
