// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// Command gen-recordfields derives the create_record / update_record `fields`
// documentation from the contract: for each record_type it renders the crm.yaml
// request body as a compact shape — key names, wire types, formats, enum
// VALUES, which keys are required, and the item shape of every array.
//
// It exists because a list of field NAMES is not enough to call the tool. Two
// reported failures came from exactly that gap: `domains` and `links` read as
// peers of `industry` and `subject` in a flat name list, and both are arrays of
// objects. A caller with no way to see that guesses, and the guess is refused.
//
// Generated from crm.yaml rather than reflected off the generated Go structs
// because reflection cannot see enum VALUES — Go constants are not reflectable —
// and `kind`, `entity_type`, `lifecycle`, `direction` and `status` are precisely
// the fields a caller gets wrong. The names are cross-checked against the Go
// structs by a fitness test in the agents package, so this file describing
// something the decoder does not accept fails the build rather than misleading
// an agent.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// recordBodies binds each record_type to the two crm.yaml schemas its writes
// decode into. The keys are the datasource EntityType vocabulary — record_type
// IS that vocabulary — and the order is the one the rendered text uses, so the
// description is byte-stable across processes.
var recordBodies = []struct{ recordType, create, update string }{
	{"person", "CreatePersonRequest", "UpdatePersonRequest"},
	{"organization", "CreateOrganizationRequest", "UpdateOrganizationRequest"},
	{"deal", "CreateDealRequest", "UpdateDealRequest"},
	{"lead", "CreateLeadRequest", "UpdateLeadRequest"},
	{"activity", "CreateActivityRequest", "UpdateActivityRequest"},
	{"project", "CreateProjectRequest", "UpdateProjectRequest"},
	{"relationship", "CreateRelationshipRequest", "UpdateRelationshipRequest"},
}

// schemas is the components/schemas map, kept whole so a $ref resolves against
// it. Only the record bodies and whatever they reference are ever rendered.
type schemas map[string]*node

// node is one JSON Schema, decoded loosely: OpenAPI 3.1 spells a nullable
// string as `type: [string, 'null']`, which no fixed Go type reads, so `type`
// stays a raw yaml.Node and typeNames normalizes it.
type node struct {
	Ref        string           `yaml:"$ref"`
	Type       yaml.Node        `yaml:"type"`
	Format     string           `yaml:"format"`
	Enum       []any            `yaml:"enum"`
	Items      *node            `yaml:"items"`
	Properties map[string]*node `yaml:"properties"`
	Required   []string         `yaml:"required"`
}

func main() {
	in := flag.String("in", "", "authoritative crm.yaml")
	out := flag.String("out", "", "generated Go shape table")
	flag.Parse()
	if *in == "" || *out == "" {
		log.Fatal("gen-recordfields: -in and -out are required")
	}
	raw, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("gen-recordfields: %v", err)
	}
	var doc struct {
		Components struct {
			Schemas schemas `yaml:"schemas"`
		} `yaml:"components"`
		// Paths carries the list operations list_records reads its filter
		// vocabulary off. The values stay raw because a path ITEM holds more
		// than operations — its own shared `parameters` sequence sits beside
		// the verbs — so only the verb keys are decoded as operations.
		Paths map[string]map[string]yaml.Node `yaml:"paths"`
	}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		log.Fatalf("gen-recordfields: parsing %s: %v", *in, err)
	}
	source, err := render(doc.Components.Schemas, doc.Paths)
	if err != nil {
		log.Fatalf("gen-recordfields: %v", err)
	}
	formatted, err := format.Source(source)
	if err != nil {
		log.Fatalf("gen-recordfields: formatting output: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		log.Fatalf("gen-recordfields: %v", err)
	}
}

func render(all schemas, paths map[string]map[string]yaml.Node) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by gen-recordfields; DO NOT EDIT.\n\n")
	b.WriteString("package agents\n\n")
	b.WriteString("// createRecordShapes and updateRecordShapes render each record_type's crm.yaml\n")
	b.WriteString("// request body as a compact shape, keyed by record_type. A key with no `?` is\n")
	b.WriteString("// REQUIRED by the contract; `?` marks one the body may omit.\n")
	for _, table := range []struct {
		name  string
		pick  func(entry struct{ recordType, create, update string }) string
		which string
	}{
		{"createRecordShapes", func(e struct{ recordType, create, update string }) string { return e.create }, "create"},
		{"updateRecordShapes", func(e struct{ recordType, create, update string }) string { return e.update }, "update"},
	} {
		b.WriteString("\nvar " + table.name + " = map[string]string{\n")
		for _, entry := range recordBodies {
			name := table.pick(entry)
			schema, ok := all[name]
			if !ok {
				return nil, fmt.Errorf("crm.yaml declares no %s (the %s body for %s)", name, table.which, entry.recordType)
			}
			shape, err := objectShape(schema, all)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", name, err)
			}
			b.WriteString("\t" + strconv.Quote(entry.recordType) + ": " + strconv.Quote(shape) + ",\n")
		}
		b.WriteString("}\n")
	}
	if err := renderEnums(&b, all); err != nil {
		return nil, err
	}
	if err := renderListFilters(&b, paths); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}

// contractEnums are the closed vocabularies a hand-written tool schema would
// otherwise re-spell. Each is emitted as a ready-to-splice JSON array so the
// schema literal that uses it cannot hold a stale copy.
//
// They are here because both hand-written copies had already drifted, in
// opposite directions: log_activity omitted `whatsapp` and `telegram`, so a
// message the server stores could not be logged through the tool; and both
// log_activity and book_meeting advertised a `project` link the contract does
// not accept, so an agent following the schema was refused. A vocabulary spelled
// twice is a vocabulary that disagrees with itself.
var contractEnums = []struct{ name, schema, path string }{
	{"activityKindEnum", "CreateActivityRequest", "kind"},
	{"activityLinkEntityTypeEnum", "CreateActivityRequest", "links.items.entity_type"},
}

func renderEnums(b *strings.Builder, all schemas) error {
	b.WriteString("\n// The contract's own closed vocabularies, as JSON arrays a tool's InputSchema\n")
	b.WriteString("// splices in place of a hand-written enum literal.\n")
	for _, want := range contractEnums {
		schema, ok := all[want.schema]
		if !ok {
			return fmt.Errorf("crm.yaml declares no %s", want.schema)
		}
		target, err := walk(schema, want.path, all)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", want.schema, want.path, err)
		}
		values := enumValues(target)
		if len(values) == 0 {
			return fmt.Errorf("%s.%s declares no enum", want.schema, want.path)
		}
		b.WriteString("\nconst " + want.name + " = `[" + strings.Join(values, ",") + "]`\n")
	}
	return nil
}

// walk follows a dotted path through properties, using the literal segment
// `items` to step into an array's element schema.
func walk(from *node, path string, all schemas) (*node, error) {
	current, err := resolve(from, all)
	if err != nil {
		return nil, err
	}
	for _, segment := range strings.Split(path, ".") {
		if segment == "items" {
			if current.Items == nil {
				return nil, fmt.Errorf("no items under %q", segment)
			}
			current, err = resolve(current.Items, all)
		} else {
			next, ok := current.Properties[segment]
			if !ok {
				return nil, fmt.Errorf("no property %q", segment)
			}
			current, err = resolve(next, all)
		}
		if err != nil {
			return nil, err
		}
	}
	return current, nil
}

// surfaceStamped names the keys the crm.yaml body REQUIRES and the MCP tool
// supplies itself, so a caller must never be told to send one.
//
// `source` is the whole set today: the write tools stamp their own provenance
// and every provider overwrites whatever arrived. Rendering it as required
// would make an agent invent a mandatory value that is then discarded — a
// sentence that is wrong in exactly the way this generator exists to prevent,
// and the description already carries an advisory saying it is overwritten. Two
// statements, one of them false, is worse than the name list it replaced.
var surfaceStamped = map[string]bool{"source": true}

// objectShape renders a request body: `{key: shape, optional?: shape}`, keys
// sorted so the text is byte-stable and a reshuffle is never mistaken for a
// contract change by a client that caches tool descriptions.
func objectShape(schema *node, all schemas) (string, error) {
	resolved, err := resolve(schema, all)
	if err != nil {
		return "", err
	}
	required := make(map[string]bool, len(resolved.Required))
	for _, name := range resolved.Required {
		required[name] = !surfaceStamped[name]
	}
	return renderProperties(resolved, required, all, 0)
}

// maxShapeDepth stops the render one level inside an array item or a nested
// object. A shape that recurses to the leaves is a schema, and the reader asked
// for the field they are about to send — deeper structure is what the contract
// is for.
const maxShapeDepth = 2

// valueShape names ONE property's wire shape: its enum values where it has
// them, its format where the format is what a caller gets wrong, its item shape
// where it is an array.
func valueShape(prop *node, all schemas, depth int) (string, error) {
	resolved, err := resolve(prop, all)
	if err != nil {
		return "", err
	}
	// `|` rather than a JSON array: the shape is prose a model reads, and
	// alternation is how a reader spells "one of these". The schema-literal
	// spelling is renderEnums' job, and the two must not be confused — a JSON
	// enum joined by pipes is not JSON.
	if values := enumValues(resolved); len(values) > 0 {
		return strings.Join(values, "|"), nil
	}
	kinds := typeNames(resolved)
	switch {
	case kinds["array"]:
		if resolved.Items == nil || depth >= maxShapeDepth {
			return "array", nil
		}
		item, err := valueShape(resolved.Items, all, depth+1)
		if err != nil {
			return "", err
		}
		return "[" + item + "]", nil
	case kinds["object"] || len(resolved.Properties) > 0:
		if len(resolved.Properties) == 0 || depth >= maxShapeDepth {
			return "object", nil
		}
		nested, err := nestedShape(resolved, all, depth)
		if err != nil {
			return "", err
		}
		return nested, nil
	case kinds["string"]:
		return stringShape(resolved.Format), nil
	case kinds["integer"]:
		return "integer", nil
	case kinds["number"]:
		return "number", nil
	case kinds["boolean"]:
		return "boolean", nil
	default:
		// A property with no type keyword accepts anything the contract allows;
		// naming a shape here would narrow it in the description only.
		return "value", nil
	}
}

// nestedShape renders an inline object one level down, marking optional keys the
// same way the top level does — the pairing of `domain` with `is_primary?` is
// the whole answer to "what goes in this array". A nested key is never
// surface-stamped: the tools stamp the body, not what is inside its arrays.
func nestedShape(resolved *node, all schemas, depth int) (string, error) {
	required := make(map[string]bool, len(resolved.Required))
	for _, name := range resolved.Required {
		required[name] = true
	}
	return renderProperties(resolved, required, all, depth+1)
}

// renderProperties is the one renderer both levels use, so the top-level body
// and an array's item shape cannot come to spell optionality differently.
func renderProperties(resolved *node, required map[string]bool, all schemas, depth int) (string, error) {
	names := make([]string, 0, len(resolved.Properties))
	for name := range resolved.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	parts := make([]string, 0, len(names))
	for _, name := range names {
		value, err := valueShape(resolved.Properties[name], all, depth)
		if err != nil {
			return "", fmt.Errorf("%s: %w", name, err)
		}
		key := name
		if !required[name] {
			key += "?"
		}
		parts = append(parts, key+": "+value)
	}
	return "{" + strings.Join(parts, ", ") + "}", nil
}

// stringShape names the FORMAT where the format is the thing a caller gets
// wrong. A bare string needs no elaboration; a uuid, a timestamp and a date all
// look like strings and are all refused when guessed.
func stringShape(format string) string {
	switch format {
	case "uuid":
		return "uuid"
	case "date-time":
		return "rfc3339"
	case "date":
		return "YYYY-MM-DD"
	case "email":
		return "email"
	default:
		return "string"
	}
}

// enumValues renders a closed vocabulary as the caller must spell it. This is
// the half reflection cannot reach — Go renders these as a named string type
// whose values live in constants — and it is the half a caller guesses wrong
// most often, because a plausible spelling (`Customer`, `Email`) is refused by
// a field whose declared type is merely "string".
//
// The `null` member is dropped: it is how OpenAPI 3.1 spells nullable, not a
// value anyone types.
func enumValues(resolved *node) []string {
	values := make([]string, 0, len(resolved.Enum))
	for _, value := range resolved.Enum {
		if value == nil {
			continue
		}
		values = append(values, strconv.Quote(fmt.Sprint(value)))
	}
	return values
}

// typeNames normalizes OpenAPI 3.1's two spellings of `type` — a scalar and a
// sequence, where the sequence is how a nullable field is declared — into the
// set of type names, with `null` dropped. Reading only the scalar form is how a
// nullable enum field silently renders as an untyped value.
func typeNames(resolved *node) map[string]bool {
	names := map[string]bool{}
	switch resolved.Type.Kind {
	case yaml.ScalarNode:
		names[resolved.Type.Value] = true
	case yaml.SequenceNode:
		for _, item := range resolved.Type.Content {
			if item.Value != "null" {
				names[item.Value] = true
			}
		}
	}
	delete(names, "null")
	return names
}

// resolve follows a local $ref into components/schemas. A ref that names
// anything else is an error rather than a silently empty shape: the description
// would then promise a field takes "value" where the contract pins a structure.
func resolve(prop *node, all schemas) (*node, error) {
	seen := 0
	for prop != nil && prop.Ref != "" {
		const prefix = "#/components/schemas/"
		if !strings.HasPrefix(prop.Ref, prefix) {
			return nil, fmt.Errorf("unsupported $ref %q", prop.Ref)
		}
		target, ok := all[strings.TrimPrefix(prop.Ref, prefix)]
		if !ok {
			return nil, fmt.Errorf("$ref %q resolves to nothing", prop.Ref)
		}
		prop = target
		if seen++; seen > len(all) {
			return nil, fmt.Errorf("$ref %q cycles", prop.Ref)
		}
	}
	if prop == nil {
		return &node{}, nil
	}
	return prop, nil
}

// ---- list_records' filter vocabulary, derived from the list operations ----

// listOperations binds each enumerable record_type to the crm.yaml operation
// that lists it. A139 pins the rule this implements: `list_records` accepts
// "exactly those the REST list operation already declares — owner,
// stage/status, updated_since, cursor — read off the contract rather than
// authored". So this file reads the operation's own parameters; it never
// carries a filter name of its own.
var listOperations = []struct{ recordType, operationID string }{
	{"person", "listPeople"},
	{"organization", "listOrganizations"},
	{"deal", "listDeals"},
	{"lead", "listLeads"},
	{"project", "listProjects"},
}

// notAFieldFilter names the inline parameters that are NOT filters on the
// record's own fields, with the reason each is out. They are excluded here
// rather than in the tool so the exclusion is one list with one rationale,
// visible beside the derivation it modifies.
var notAFieldFilter = map[string]string{
	// `q` is a text query, and search_records is the verb that owns it. #576
	// exists because the two were conflated; carrying `q` here would rebuild
	// that conflation inside the tool meant to end it.
	"q": "text search is search_records' verb",
	// `include_anchor` toggles the discovery narrowing every read of an
	// organization carries. It widens what is visible rather than filtering it,
	// which is a governance question and not a caller's filter.
	"include_anchor": "widens discovery rather than filtering",
}

// listFilter is one derived filter: the parameter name, the JSON type its
// operand takes, and the closed vocabulary when the contract declares one.
type listFilter struct {
	Name string
	Type string
	Enum []string
}

// operation is one path item's operation, decoded for its id and parameters.
type operation struct {
	OperationID string       `yaml:"operationId"`
	Parameters  []*parameter `yaml:"parameters"`
}

type parameter struct {
	Ref    string `yaml:"$ref"`
	Name   string `yaml:"name"`
	In     string `yaml:"in"`
	Schema *node  `yaml:"schema"`
}

// operationsByID indexes every declared operation by its operationId. Only the
// HTTP verb keys are decoded: a path item's own `parameters` sequence shares the
// map with them and is not an operation.
func operationsByID(paths map[string]map[string]yaml.Node) (map[string]*operation, error) {
	verbs := map[string]bool{"get": true, "post": true, "put": true, "patch": true, "delete": true}
	byID := map[string]*operation{}
	for path, item := range paths {
		for key, raw := range item {
			if !verbs[key] {
				continue
			}
			var op operation
			if err := raw.Decode(&op); err != nil {
				return nil, fmt.Errorf("decoding %s %s: %w", strings.ToUpper(key), path, err)
			}
			if op.OperationID != "" {
				byID[op.OperationID] = &op
			}
		}
	}
	return byID, nil
}

// listFiltersFor reads one operation's INLINE query parameters. The $ref'd ones
// (cursor, limit, sort, include_archived, captured_by_kind, ai_written) are the
// contract's shared REST affordances rather than per-type filters: the tool
// declares cursor and limit itself, and the rest are human list controls whose
// meaning on an agent surface is a separate question from this one.
func listFiltersFor(op *operation) []listFilter {
	var filters []listFilter
	for _, p := range op.Parameters {
		if p.Ref != "" || p.In != "query" || p.Schema == nil {
			continue
		}
		if _, excluded := notAFieldFilter[p.Name]; excluded {
			continue
		}
		filters = append(filters, listFilter{
			Name: p.Name,
			Type: firstTypeName(p.Schema),
			Enum: enumValues(p.Schema),
		})
	}
	sort.Slice(filters, func(i, j int) bool { return filters[i].Name < filters[j].Name })
	return filters
}

// firstTypeName reduces a parameter's declared type to the one JSON type name
// its operand takes, ignoring an OpenAPI 3.1 nullable union's 'null' member.
func firstTypeName(schema *node) string {
	for name := range typeNames(schema) {
		if name != "null" {
			return name
		}
	}
	return "string"
}

// renderListFilters emits the per-record_type filter table list_records builds
// its InputSchema from.
func renderListFilters(b *strings.Builder, paths map[string]map[string]yaml.Node) error {
	byID, err := operationsByID(paths)
	if err != nil {
		return err
	}
	b.WriteString("\n// listRecordFilters is what list_records may be asked to filter by, per\n")
	b.WriteString("// record_type, read off each list operation's OWN declared query parameters\n")
	b.WriteString("// (A139). A filter here that the record's store cannot answer fails\n")
	b.WriteString("// TestEveryAdvertisedListFilterReachesTheStore.\n")
	b.WriteString("var listRecordFilters = map[string][]listFilter{\n")
	for _, entry := range listOperations {
		op, ok := byID[entry.operationID]
		if !ok {
			return fmt.Errorf("crm.yaml declares no operation %s (the list operation for %s)",
				entry.operationID, entry.recordType)
		}
		filters := listFiltersFor(op)
		if len(filters) == 0 {
			return fmt.Errorf("%s declares no inline query parameters, so %s could only be enumerated unfiltered",
				entry.operationID, entry.recordType)
		}
		b.WriteString("\t" + strconv.Quote(entry.recordType) + ": {\n")
		for _, f := range filters {
			b.WriteString("\t\t{Name: " + strconv.Quote(f.Name) + ", Type: " + strconv.Quote(f.Type))
			if len(f.Enum) > 0 {
				b.WriteString(", Enum: []string{")
				for i, v := range f.Enum {
					if i > 0 {
						b.WriteString(", ")
					}
					b.WriteString(v)
				}
				b.WriteString("}")
			}
			b.WriteString("},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return nil
}
