// Code generated by gen-payloads; DO NOT EDIT.

package crmcontracts

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SubscribableEventType.
const (
	ActivityArchived          SubscribableEventType = "activity.archived"
	ActivityCaptured          SubscribableEventType = "activity.captured"
	ActivityUpdated           SubscribableEventType = "activity.updated"
	ApprovalDecided           SubscribableEventType = "approval.decided"
	ApprovalRequested         SubscribableEventType = "approval.requested"
	AuditAppended             SubscribableEventType = "audit.appended"
	ColdstartAccepted         SubscribableEventType = "coldstart.accepted"
	ColdstartReadBackProposed SubscribableEventType = "coldstart.read_back_proposed"
	ColdstartRejected         SubscribableEventType = "coldstart.rejected"
	ConsentChanged            SubscribableEventType = "consent.changed"
	DealArchived              SubscribableEventType = "deal.archived"
	DealCreated               SubscribableEventType = "deal.created"
	DealOwnerChanged          SubscribableEventType = "deal.owner_changed"
	DealRestored              SubscribableEventType = "deal.restored"
	DealStageChanged          SubscribableEventType = "deal.stage_changed"
	DealUpdated               SubscribableEventType = "deal.updated"
	EngagementReply           SubscribableEventType = "engagement.reply"
	IncumbentConnected        SubscribableEventType = "incumbent.connected"
	IncumbentDisconnected     SubscribableEventType = "incumbent.disconnected"
	LeadCreated               SubscribableEventType = "lead.created"
	LeadDisqualified          SubscribableEventType = "lead.disqualified"
	LeadPromoted              SubscribableEventType = "lead.promoted"
	LeadUpdated               SubscribableEventType = "lead.updated"
	MirrorBudgetDegraded      SubscribableEventType = "mirror.budget_degraded"
	MirrorConflict            SubscribableEventType = "mirror.conflict"
	MirrorDeleted             SubscribableEventType = "mirror.deleted"
	MirrorWriteRejected       SubscribableEventType = "mirror.write_rejected"
	OfferAccepted             SubscribableEventType = "offer.accepted"
	OfferCreated              SubscribableEventType = "offer.created"
	OfferRejected             SubscribableEventType = "offer.rejected"
	OfferSent                 SubscribableEventType = "offer.sent"
	OfferSuperseded           SubscribableEventType = "offer.superseded"
	OnboardingStateChanged    SubscribableEventType = "onboarding.state_changed"
	OrganizationArchived      SubscribableEventType = "organization.archived"
	OrganizationCreated       SubscribableEventType = "organization.created"
	OrganizationMerged        SubscribableEventType = "organization.merged"
	OrganizationUpdated       SubscribableEventType = "organization.updated"
	PassportRevoked           SubscribableEventType = "passport.revoked"
	PersonArchived            SubscribableEventType = "person.archived"
	PersonCreated             SubscribableEventType = "person.created"
	PersonMerged              SubscribableEventType = "person.merged"
	PersonRestored            SubscribableEventType = "person.restored"
	PersonUpdated             SubscribableEventType = "person.updated"
	PipelineArchived          SubscribableEventType = "pipeline.archived"
	PipelineCreated           SubscribableEventType = "pipeline.created"
	PipelineUpdated           SubscribableEventType = "pipeline.updated"
	RetentionApplied          SubscribableEventType = "retention.applied"
	RoleChanged               SubscribableEventType = "role.changed"
	SignalDetected            SubscribableEventType = "signal.detected"
	SignalResolved            SubscribableEventType = "signal.resolved"
	StageArchived             SubscribableEventType = "stage.archived"
	StageCreated              SubscribableEventType = "stage.created"
	StageUpdated              SubscribableEventType = "stage.updated"
	UserDeactivated           SubscribableEventType = "user.deactivated"
	UserInvited               SubscribableEventType = "user.invited"
	UserReactivated           SubscribableEventType = "user.reactivated"
	VoiceBuildChanged         SubscribableEventType = "voice.build_changed"
	VoiceCorpusChanged        SubscribableEventType = "voice.corpus_changed"
	VoiceDraftOutcomeRecorded SubscribableEventType = "voice.draft_outcome_recorded"
	VoiceProfileArchived      SubscribableEventType = "voice.profile_archived"
	VoiceProfileCreated       SubscribableEventType = "voice.profile_created"
	VoiceProfileUpdated       SubscribableEventType = "voice.profile_updated"
	VoiceVersionChanged       SubscribableEventType = "voice.version_changed"
)

// Valid indicates whether the value is a known member of the SubscribableEventType enum.
func (e SubscribableEventType) Valid() bool {
	switch e {
	case ActivityArchived:
		return true
	case ActivityCaptured:
		return true
	case ActivityUpdated:
		return true
	case ApprovalDecided:
		return true
	case ApprovalRequested:
		return true
	case AuditAppended:
		return true
	case ColdstartAccepted:
		return true
	case ColdstartReadBackProposed:
		return true
	case ColdstartRejected:
		return true
	case ConsentChanged:
		return true
	case DealArchived:
		return true
	case DealCreated:
		return true
	case DealOwnerChanged:
		return true
	case DealRestored:
		return true
	case DealStageChanged:
		return true
	case DealUpdated:
		return true
	case EngagementReply:
		return true
	case IncumbentConnected:
		return true
	case IncumbentDisconnected:
		return true
	case LeadCreated:
		return true
	case LeadDisqualified:
		return true
	case LeadPromoted:
		return true
	case LeadUpdated:
		return true
	case MirrorBudgetDegraded:
		return true
	case MirrorConflict:
		return true
	case MirrorDeleted:
		return true
	case MirrorWriteRejected:
		return true
	case OfferAccepted:
		return true
	case OfferCreated:
		return true
	case OfferRejected:
		return true
	case OfferSent:
		return true
	case OfferSuperseded:
		return true
	case OnboardingStateChanged:
		return true
	case OrganizationArchived:
		return true
	case OrganizationCreated:
		return true
	case OrganizationMerged:
		return true
	case OrganizationUpdated:
		return true
	case PassportRevoked:
		return true
	case PersonArchived:
		return true
	case PersonCreated:
		return true
	case PersonMerged:
		return true
	case PersonRestored:
		return true
	case PersonUpdated:
		return true
	case PipelineArchived:
		return true
	case PipelineCreated:
		return true
	case PipelineUpdated:
		return true
	case RetentionApplied:
		return true
	case RoleChanged:
		return true
	case SignalDetected:
		return true
	case SignalResolved:
		return true
	case StageArchived:
		return true
	case StageCreated:
		return true
	case StageUpdated:
		return true
	case UserDeactivated:
		return true
	case UserInvited:
		return true
	case UserReactivated:
		return true
	case VoiceBuildChanged:
		return true
	case VoiceCorpusChanged:
		return true
	case VoiceDraftOutcomeRecorded:
		return true
	case VoiceProfileArchived:
		return true
	case VoiceProfileCreated:
		return true
	case VoiceProfileUpdated:
		return true
	case VoiceVersionChanged:
		return true
	default:
		return false
	}
}

// PublicEventActivityArchived Payload for activity.archived — an activity was archived. Carries no data.
type PublicEventActivityArchived struct{}

// PublicEventActivityCaptured Payload for activity.captured — the first-class capture verb, emitted instead of (never alongside) a generic activity.created (events.md §1). Two emit sites: the direct-log path (activities/activity.go) that sets kind only, and the capture ingestion path (capture/sink.go) that also names its originating source system.
type PublicEventActivityCaptured struct {
	// Kind The activity kind (email | call | meeting | note | whatsapp | telegram). Decoded by automation/handlers_event.go's post_meeting_recap trigger — this field's JSON key is a binding contract, not just documentation.
	Kind string `json:"kind"`

	// SourceSystem The originating source system (capture ingestion only; absent on a direct log).
	SourceSystem *string `json:"source_system,omitempty"`
}

// PublicEventActivityChangedFields activity.updated's BOUNDED delta: UpdateActivity's known mutable fields (subject, body, occurred_at, due_at, remind_at, assignee_id, is_done) each carried only when this update touched them, plus RelinkActivity's relinked target — a fixed, KNOWN key set (unlike person/organization/deal/lead.updated's genuinely open patch), so it is typed rather than an open map.
type PublicEventActivityChangedFields struct {
	// AssigneeId The activity's new assignee (absent when this update did not touch it).
	AssigneeId *openapi_types.UUID `json:"assignee_id,omitempty"`

	// Body Whether the body was touched (a presence flag, not the content — bodies can be large and are never echoed onto the wire).
	Body *bool `json:"body,omitempty"`

	// DueAt The activity's new due_at (absent when this update did not touch it).
	DueAt *time.Time `json:"due_at,omitempty"`

	// IsDone The activity's new completion state (absent when this update did not touch it).
	IsDone *bool `json:"is_done,omitempty"`

	// OccurredAt The activity's new occurred_at (absent when this update did not touch it).
	OccurredAt *time.Time `json:"occurred_at,omitempty"`

	// Relinked The entity an activity was relinked onto (activities/lifecycle.go's RelinkActivity) — an association change, not a re-capture, so it travels as one changed_fields key rather than its own event verb.
	Relinked *PublicEventActivityRelinkedRef `json:"relinked,omitempty"`

	// RemindAt The activity's new remind_at (absent when this update did not touch it).
	RemindAt *time.Time `json:"remind_at,omitempty"`

	// Subject The activity's new subject (absent when this update did not touch it).
	Subject *string `json:"subject,omitempty"`
}

// PublicEventActivityRelinkedRef The entity an activity was relinked onto (activities/lifecycle.go's RelinkActivity) — an association change, not a re-capture, so it travels as one changed_fields key rather than its own event verb.
type PublicEventActivityRelinkedRef struct {
	// EntityId The relink target's id.
	EntityId openapi_types.UUID `json:"entity_id"`

	// EntityType The relink target's kind (person | organization | deal | lead).
	EntityType string `json:"entity_type"`
}

// PublicEventActivityUpdated Payload for activity.updated — a BOUNDED delta (unlike the person/organization/deal/lead family's genuinely open patch): UpdateActivity and RelinkActivity together cover a fixed, KNOWN set of inner keys, so changed_fields is a typed struct here, not an open map.
type PublicEventActivityUpdated struct {
	// ChangedFields activity.updated's BOUNDED delta: UpdateActivity's known mutable fields (subject, body, occurred_at, due_at, remind_at, assignee_id, is_done) each carried only when this update touched them, plus RelinkActivity's relinked target — a fixed, KNOWN key set (unlike person/organization/deal/lead.updated's genuinely open patch), so it is typed rather than an open map.
	ChangedFields PublicEventActivityChangedFields `json:"changed_fields"`
}

// PublicEventActor Who or what caused the event, as exposed publicly.
type PublicEventActor struct {
	// Type Actor kind (e.g. human, agent, connector).
	Type string `json:"type"`
}

// PublicEventApprovalDecided Payload for approval.decided — a human approved or rejected a staged approval (approvals/decide.go). verdict and edited_change are decoded BY NAME outside this module — automation's blocked-run consumer matches verdict (automation/engine_blocked.go), the Surface-B runner's resume consumer reads edited_change (compose/runnerservice.go) — see the JSON-tag regression tests in internal/modules/webhooks. edited/diff_hash/edited_change are present only on the ADR-0036 §4 modify-then-approve arm, where the human's edited payload replaced the staged change under a freshly computed diff_hash.
type PublicEventApprovalDecided struct {
	// DecidedBy The deciding human's user id.
	DecidedBy openapi_types.UUID `json:"decided_by"`

	// DiffHash The edited change's freshly computed diff_hash (present only on the modify-then-approve arm).
	DiffHash *string `json:"diff_hash,omitempty"`

	// Edited True when the human edited the proposed change before approving (present only on the modify-then-approve arm).
	Edited *bool `json:"edited,omitempty"`

	// EditedChange The human's edited version of the proposed change (present only on the modify-then-approve arm) — an OPEN object: its shape is whatever the staged kind's proposed_change carries, so it stays a raw map rather than a narrowly typed struct (the runner's resume consumer decodes it as json.RawMessage off the wire; a fixed struct here would drop fields a future staging kind adds).
	EditedChange *map[string]interface{} `json:"edited_change,omitempty"`

	// Kind The decided staging's kind.
	Kind string `json:"kind"`

	// Verdict The decision outcome (approved | rejected).
	Verdict string `json:"verdict"`
}

// PublicEventApprovalRequested Payload for approval.requested — an agent's 🟡 call was staged pending a human decision (ADR-0036, approvals/staging.go's StageInTx). The staged approval row's own id is the event's entity ref; this payload names what was staged, its polymorphic target, and when the staging lapses into expired if undecided.
type PublicEventApprovalRequested struct {
	// ExpiresAt When this staging lapses into expired if undecided.
	ExpiresAt time.Time `json:"expires_at"`

	// Kind The staged tool/kind name (e.g. advance_deal).
	Kind string `json:"kind"`

	// Summary The human-readable summary the inbox shows.
	Summary string `json:"summary"`

	// TargetEntityId The polymorphic entity id the staged action targets; absent when the staging names no single target row.
	TargetEntityId *openapi_types.UUID `json:"target_entity_id,omitempty"`

	// TargetEntityType The polymorphic entity type the staged action targets.
	TargetEntityType string `json:"target_entity_type"`
}

// PublicEventAuditAppended Payload for audit.appended — not currently delivered: there is no emit site for this type, and none is planned for V1. It exists so the §5 catalog (events.Types()) is completely covered by a payload schema (the whole-catalog coverage gate), never carrying a subscribable type with no contract. An empty payload by design — the audit ledger row it would announce is workspace-level (its subject is resolved back under the receiver's own scope), so no record detail rides the event.
type PublicEventAuditAppended struct{}

// PublicEventColdstartAccepted Payload for coldstart.accepted — a human accepted a staged cold-start read-back (approvals/decide.go's kind-decided echo, emitted on the same audit row as approval.decided).
type PublicEventColdstartAccepted struct {
	// ApprovalId The decided approval's id (same as the envelope's entity ref).
	ApprovalId openapi_types.UUID `json:"approval_id"`

	// DecidedBy The deciding human's user id.
	DecidedBy openapi_types.UUID `json:"decided_by"`
}

// PublicEventColdstartReadBackProposed Payload for coldstart.read_back_proposed — a cold-start read-back was staged as a "coldstart" approval (compose/coldstart.go's stage, carried through approvals/staging.go's Announce alongside approval.requested on the same audit row). Carries only the read-back's shape, never the extracted field values or the pasted source text/statement — tenant data never rides an announced event.
type PublicEventColdstartReadBackProposed struct {
	// FieldCount How many fields the read-back grounded.
	FieldCount int `json:"field_count"`

	// SourceKind The read-back's source kind (text | self_description); absent for a url-kind read-back, which sets source_url instead.
	SourceKind *string `json:"source_kind,omitempty"`

	// SourceUrl The read-back's source URL (url-kind read-backs only).
	SourceUrl *string `json:"source_url,omitempty"`
}

// PublicEventColdstartRejected Payload for coldstart.rejected — a human rejected a staged cold-start read-back (approvals/decide.go's kind-decided echo, emitted on the same audit row as approval.decided).
type PublicEventColdstartRejected struct {
	// ApprovalId The decided approval's id (same as the envelope's entity ref).
	ApprovalId openapi_types.UUID `json:"approval_id"`

	// DecidedBy The deciding human's user id.
	DecidedBy openapi_types.UUID `json:"decided_by"`
}

// PublicEventConsentChanged Payload for consent.changed — a subject's per-purpose consent state was recorded (consent/store.go's Record). The subject is a person XOR a lead (data-model §7, before promotion) — a RUNTIME choice Record resolves via consentSubject, not a fixed type this schema can name, so this is the first dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity.
type PublicEventConsentChanged struct {
	// NewState The state now on record (granted | withdrawn).
	NewState string `json:"new_state"`

	// Purpose The purpose's key (e.g. marketing_email).
	Purpose string `json:"purpose"`

	// PurposeId The consent purpose this state change applies to.
	PurposeId openapi_types.UUID `json:"purpose_id"`
}

// PublicEventDealArchived Payload for deal.archived — a deal was archived. Carries no data.
type PublicEventDealArchived struct{}

// PublicEventDealCreated Payload for deal.created — a deal was opened.
type PublicEventDealCreated struct {
	// Name The deal's name at creation.
	Name string `json:"name"`
}

// PublicEventDealOwnerChanged Payload for deal.owner_changed — the deal's owner was reassigned. Emitted instead of (never alongside) deal.updated for the owner_id field (events.md §5.3).
type PublicEventDealOwnerChanged struct {
	// FromOwnerId The previous owner (absent when the deal had none).
	FromOwnerId *openapi_types.UUID `json:"from_owner_id,omitempty"`

	// ToOwnerId The new owner.
	ToOwnerId openapi_types.UUID `json:"to_owner_id"`
}

// PublicEventDealRestored Payload for deal.restored. Never emitted today (no restore path exists for deal); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type PublicEventDealRestored struct{}

// PublicEventDealStageChanged Payload for deal.stage_changed — a deal advanced between stages. Carries the amount/win-probability snapshot frozen at the moment of the move so consumers (the trajectory view, the overnight stalled/forecast sweep, the automation trigger keyed on to_status) never need a read-back.
type PublicEventDealStageChanged struct {
	// AmountMinorAtChange The deal's amount, frozen at the moment of the move.
	AmountMinorAtChange *int64 `json:"amount_minor_at_change,omitempty"`

	// CurrencyAtChange The deal's currency, frozen at the moment of the move.
	CurrencyAtChange *string `json:"currency_at_change,omitempty"`

	// FromStageId Stage the deal left (absent on first placement).
	FromStageId *openapi_types.UUID `json:"from_stage_id,omitempty"`

	// FromStatus Deal status before the move (open | won | lost).
	FromStatus string `json:"from_status"`

	// ToStageId Stage the deal entered.
	ToStageId openapi_types.UUID `json:"to_stage_id"`

	// ToStatus Deal status after the move (open | won | lost) — the field the automation trigger keys on (automation/handlers_event.go).
	ToStatus string `json:"to_status"`

	// WinProbability The target stage's win probability, frozen at the moment of the move.
	WinProbability int `json:"win_probability"`
}

// PublicEventDealUpdated Payload for deal.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, an accepted-offer amount sync, a close-date-correction note, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type PublicEventDealUpdated struct {
	// ChangedFields What this update touched, incl. runtime cf_* custom fields. The value shape depends on the emit site: a column patch carries a flat field → new-value entry, while the recompute/routing/relationship sites carry a `{delta: {...}}` sub-object (occasionally with a sibling `source`). Read a key's value as either form.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// PublicEventEngagementReply Payload for engagement.reply — CAP-FORMULA-1: an inbound message in a thread we previously wrote outbound in is a reply, feeding the engagement signal scoring (capture/sink.go's emitReply).
type PublicEventEngagementReply struct {
	// Channel The channel the reply arrived on (today always email).
	Channel string `json:"channel"`

	// ContactId The already-known person behind the counterparty address (absent when the counterparty resolves only in a follow-up ensure).
	ContactId *openapi_types.UUID `json:"contact_id,omitempty"`

	// IdempotencyKey The capture natural key (source_system:source_id) this reply was detected from.
	IdempotencyKey string `json:"idempotency_key"`

	// MatchedOutboundActivityId The prior outbound activity this inbound message replies to.
	MatchedOutboundActivityId openapi_types.UUID `json:"matched_outbound_activity_id"`

	// OccurredAt When the reply activity occurred.
	OccurredAt time.Time `json:"occurred_at"`
}

// PublicEventEntityRef The primary entity the event concerns.
type PublicEventEntityRef struct {
	// Id Stable identifier of the entity.
	Id openapi_types.UUID `json:"id"`

	// Type Entity kind (e.g. deal, person, organization).
	Type string `json:"type"`
}

// PublicEventEnvelope The public wrapper around every delivered event payload. This is the exact JSON shape a subscriber receives; it carries no internal metadata.
type PublicEventEnvelope struct {
	// Actor Who or what caused the event, as exposed publicly.
	Actor PublicEventActor `json:"actor"`

	// CorrelationId Correlates all events emitted for one originating request.
	CorrelationId openapi_types.UUID `json:"correlation_id"`

	// Data The typed event payload (one of the PublicEvent* schemas).
	Data map[string]interface{} `json:"data"`

	// Entity The primary entity the event concerns.
	Entity PublicEventEntityRef `json:"entity"`

	// EventId Unique id of this event occurrence.
	EventId openapi_types.UUID `json:"event_id"`

	// OccurredAt When the event occurred (RFC 3339).
	OccurredAt time.Time `json:"occurred_at"`

	// Type The event type (a SubscribableEventType value).
	Type string `json:"type"`

	// Version Schema version of the payload in data.
	Version int `json:"version"`
}

// PublicEventIncumbentConnected Payload for incumbent.connected — a workspace completed the overlay-mode incumbent-CRM connect flow (overlay/connection.go's insertConnection); the workspace flipped to x_sor_mode=overlay in the same transaction. Unlike the mirror.* events above, this event's subject is always the incumbent_connection row itself — a fixed type — so it is emitted via the plain storekit.EmitEvent.
type PublicEventIncumbentConnected struct {
	// Incumbent The incumbent CRM system connected (e.g. "hubspot").
	Incumbent string `json:"incumbent"`

	// Region The incumbent account's data-residency region.
	Region string `json:"region"`

	// Scopes The least-privilege OAuth scope set granted.
	Scopes []string `json:"scopes"`

	// Status The connection's status after this change (active).
	Status string `json:"status"`
}

// PublicEventIncumbentDisconnected Payload for incumbent.disconnected — a workspace's active incumbent-CRM connection was revoked (overlay/teardown.go's Disconnect); mirror teardown and credential cleanup follow. This event's subject is always the incumbent_connection row itself — a fixed type — so it is emitted via the plain storekit.EmitEvent.
type PublicEventIncumbentDisconnected struct {
	// Incumbent The incumbent CRM system disconnected.
	Incumbent string `json:"incumbent"`

	// Region The incumbent account's data-residency region.
	Region string `json:"region"`

	// Status The connection's status after this change (revoked).
	Status string `json:"status"`
}

// PublicEventLeadCreated Payload for lead.created — a lead was created. Two emit sites: a direct create (people/lead.go) that sets no fields, and the capture auto-create engine (capture/sink.go) that names its originating source system; source_system is therefore optional.
type PublicEventLeadCreated struct {
	// SourceSystem The originating source system (capture auto-create only; absent on a direct create).
	SourceSystem *string `json:"source_system,omitempty"`
}

// PublicEventLeadDisqualified Payload for lead.disqualified — a lead was disqualified. Carries no data.
type PublicEventLeadDisqualified struct{}

// PublicEventLeadPromoted Payload for lead.promoted — the lead's genuine-engagement promotion into the context graph (events.md §5.5); its own verb, never a lead.updated, since neither person.created nor person.updated on its own says a lead crossed this line.
type PublicEventLeadPromoted struct {
	// DedupeOutcome Whether promotion created a new person or merged into an existing one: created or merged.
	DedupeOutcome string `json:"dedupe_outcome"`

	// EvidenceRef The inbound activity that evidenced the trigger (absent for a human_qualify with no linked activity).
	EvidenceRef *openapi_types.UUID `json:"evidence_ref,omitempty"`

	// PromotedPersonId The person this lead promoted into (fresh or an existing survivor).
	PromotedPersonId openapi_types.UUID `json:"promoted_person_id"`

	// Trigger The genuine-engagement trigger that authorized promotion: inbound_reply, meeting_booked, meeting_held, or human_qualify.
	Trigger string `json:"trigger"`
}

// PublicEventLeadUpdated Payload for lead.updated — an OPEN envelope: emit sites carry divergent shapes (a flat column patch that includes runtime cf_* custom-field columns, and behavioral-recompute/routing deltas), so the honest shape is a change-set map rather than a fixed field list.
type PublicEventLeadUpdated struct {
	// ChangedFields What this update touched, incl. runtime cf_* custom fields. The value shape depends on the emit site: a column patch carries a flat field → new-value entry, while the recompute/routing/relationship sites carry a `{delta: {...}}` sub-object (occasionally with a sibling `source`). Read a key's value as either form.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// PublicEventMirrorBudgetDegraded Payload for mirror.budget_degraded — a force-fresh read fell back to the mirror because the workspace's shared OVB budget had shed to the "shed" band (overlay/freshness.go's emitBudgetDegraded, OVA-EVT-3). The event names the record the degraded read was about; that record's class is a RUNTIME value (the read's own entity ref), so this is a dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity.
type PublicEventMirrorBudgetDegraded struct {
	// Band The budget band that forced the degrade (currently always "shed").
	Band string `json:"band"`
}

// PublicEventMirrorConflict Payload for mirror.conflict — the reconcile poller (overlay/ reconcile.go's emitMirrorConflict) observed the incumbent CRM had moved a record the mirror's own baseline still called current, an overwrite-worthy divergence (OVA-EVT-1). object_class is the RUNTIME canonical class of the record involved (e.g. "person", "deal") — not a fixed type this schema can name — so this is a dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity.
type PublicEventMirrorConflict struct {
	// ExternalId The record's incumbent-side natural key.
	ExternalId string `json:"external_id"`

	// IncumbentUpdatedAt The incumbent's reported modification timestamp.
	IncumbentUpdatedAt time.Time `json:"incumbent_updated_at"`

	// ObjectClass The canonical Margince class of the diverged record.
	ObjectClass string `json:"object_class"`

	// PriorUpdatedAt The mirror's prior stored baseline timestamp.
	PriorUpdatedAt time.Time `json:"prior_updated_at"`
}

// PublicEventMirrorDeleted Payload for mirror.deleted — continuous sync observed the incumbent report a record deleted, and the mirror purged its cached row, association edges, and visibility projection (overlay/mirrordeletion.go). object_class is the RUNTIME canonical class of the purged record, not a fixed type this schema can name, so this is a dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity.
type PublicEventMirrorDeleted struct {
	// DeletedAt When the incumbent reported the deletion.
	DeletedAt time.Time `json:"deleted_at"`

	// ExternalId The record's incumbent-side natural key.
	ExternalId string `json:"external_id"`

	// ObjectClass The canonical Margince class of the purged record.
	ObjectClass string `json:"object_class"`
}

// PublicEventMirrorWriteRejected Payload for mirror.write_rejected. Never emitted today — reserved for branch 2 (writes to an overlay-mode workspace's incumbent CRM, currently declared unsupported_by_sor); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type PublicEventMirrorWriteRejected struct{}

// PublicEventOfferAccepted Payload for offer.accepted — a sent offer was accepted. The deal's headline amount is synced from this offer's gross in the same transaction (see deal.updated on the paired deal entity).
type PublicEventOfferAccepted struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// GrossMinor The offer's gross total, now also the deal's amount.
	GrossMinor *int64 `json:"gross_minor,omitempty"`

	// OfferId The accepted offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`
}

// PublicEventOfferCreated Payload for offer.created — a new Angebot revision was opened (either the first revision, via CreateOffer, or a fresh draft revision minted by RegenerateOffer).
type PublicEventOfferCreated struct {
	// CapturedBy The principal that created this revision.
	CapturedBy string `json:"captured_by"`

	// Currency The offer's currency.
	Currency string `json:"currency"`

	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// OfferId The created offer revision.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number (1 for a first offer).
	Revision int `json:"revision"`

	// Source Where this offer originated (e.g. manual, ai).
	Source string `json:"source"`
}

// PublicEventOfferRejected Payload for offer.rejected — a sent offer was rejected.
type PublicEventOfferRejected struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// OfferId The rejected offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Reason The optional rejection reason (absent when none was given).
	Reason *string `json:"reason,omitempty"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`
}

// PublicEventOfferSent Payload for offer.sent — a draft offer left the workspace. Carries the FX rate frozen at send time (RT-PR-C2) so consumers never need a read-back for the native-currency-to-base conversion.
type PublicEventOfferSent struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// FxRateToBase Native→base rate frozen at send (RT-PR-C2). Decimal-as-string to avoid float rounding.
	FxRateToBase string `json:"fx_rate_to_base"`

	// GrossMinor The offer's gross total at send time.
	GrossMinor *int64 `json:"gross_minor,omitempty"`

	// OfferId The sent offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`

	// ValidUntil The offer's validity date (absent when unset).
	ValidUntil *openapi_types.Date `json:"valid_until,omitempty"`
}

// PublicEventOfferSuperseded Payload for offer.superseded — a sent offer was regenerated into a fresh draft revision (B-E03.19) and marked superseded; the new revision arrives as its own offer.created event.
type PublicEventOfferSuperseded struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// FromRevision The superseded revision number.
	FromRevision *int `json:"from_revision,omitempty"`

	// OfferId The superseded (prior) offer revision.
	OfferId openapi_types.UUID `json:"offer_id"`

	// ToRevision The new revision number minted by the regenerate.
	ToRevision int `json:"to_revision"`
}

// PublicEventOnboardingStateChanged Payload for onboarding.state_changed — the admitted human's wizard checkpoint was created or advanced (identity/onboarding.go's auditOnboardingState).
type PublicEventOnboardingStateChanged struct {
	// Completed Whether the wizard was completed as of this checkpoint.
	Completed bool `json:"completed"`

	// ConnectSkipped Whether the incumbent-connect step was skipped.
	ConnectSkipped bool `json:"connect_skipped"`

	// Path The chosen onboarding path.
	Path string `json:"path"`

	// Step The wizard step this checkpoint reached.
	Step string `json:"step"`

	// UserId The human whose wizard state this is.
	UserId openapi_types.UUID `json:"user_id"`

	// Version The row's optimistic-concurrency version after this checkpoint.
	Version int64 `json:"version"`

	// VoiceSkipped Whether the voice-setup step was skipped.
	VoiceSkipped bool `json:"voice_skipped"`
}

// PublicEventOrganizationArchived Payload for organization.archived — an organization was archived. Carries no data.
type PublicEventOrganizationArchived struct{}

// PublicEventOrganizationCreated Payload for organization.created — a UNION across five emit sites (a direct create, the capture auto-create engine, the anchor company save, the site-read confirmation, and the cold-start profile apply), each of which sets only its own subset; every field is therefore optional.
type PublicEventOrganizationCreated struct {
	// Anchor Whether this is the installation's own anchor organization (company save only).
	Anchor *bool `json:"anchor,omitempty"`

	// CapturedBy The principal that created this organization.
	CapturedBy *string `json:"captured_by,omitempty"`

	// Delta The fields the creating site applied (company save / site-read confirmation only).
	Delta *map[string]interface{} `json:"delta,omitempty"`

	// DisplayName The organization's display name at creation (absent when the site never set one).
	DisplayName *string `json:"display_name,omitempty"`

	// PrimaryDomain The organization's primary domain (cold-start apply only).
	PrimaryDomain *string `json:"primary_domain,omitempty"`

	// SiteReadId The site-read that produced this organization (site-read confirmation only).
	SiteReadId *openapi_types.UUID `json:"site_read_id,omitempty"`

	// Source Where this organization originated (e.g. human, site_read).
	Source *string `json:"source,omitempty"`

	// SourceUrl The source page this organization was read from (site-read confirmation only).
	SourceUrl *string `json:"source_url,omitempty"`
}

// PublicEventOrganizationMerged Payload for organization.merged — two organization records collapsed into one (the §1.3 merge); neither organization.updated nor organization.archived can say this, so it is its own verb.
type PublicEventOrganizationMerged struct {
	// MergedFromId The merged-away (source) organization, retired but still fetchable by id.
	MergedFromId openapi_types.UUID `json:"merged_from_id"`

	// MergedIntoId The survivor (target) organization.
	MergedIntoId openapi_types.UUID `json:"merged_into_id"`
}

// PublicEventOrganizationUpdated Payload for organization.updated — an OPEN envelope: eight emit sites carry divergent shapes (a flat column patch, the anchor company save's field delta, the partner extension's nested delta, enrichment/deep-read applies, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type PublicEventOrganizationUpdated struct {
	// ChangedFields What this update touched, incl. runtime cf_* custom fields. The value shape depends on the emit site: a column patch carries a flat field → new-value entry, while the recompute/routing/relationship sites carry a `{delta: {...}}` sub-object (occasionally with a sibling `source`). Read a key's value as either form.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// PublicEventPassportRevoked Payload for passport.revoked — an agent passport was hard-revoked (identity/passport.go's RevokePassport), so long-lived consumers drop it within one bus cycle.
type PublicEventPassportRevoked struct {
	// By The human who revoked it (the granting user, or an admin).
	By openapi_types.UUID `json:"by"`

	// PassportId The revoked passport.
	PassportId openapi_types.UUID `json:"passport_id"`
}

// PublicEventPersonArchived Payload for person.archived — a person was archived. Carries no data.
type PublicEventPersonArchived struct{}

// PublicEventPersonCreated Payload for person.created — a person was created.
type PublicEventPersonCreated struct {
	// FullName The person's name at creation.
	FullName string `json:"full_name"`
}

// PublicEventPersonMerged Payload for person.merged — two person records collapsed into one (the §1.3 merge); neither person.updated nor person.archived can say this, so it is its own verb.
type PublicEventPersonMerged struct {
	// MergedFromId The merged-away (source) person, retired but still fetchable by id.
	MergedFromId openapi_types.UUID `json:"merged_from_id"`

	// MergedIntoId The survivor (target) person.
	MergedIntoId openapi_types.UUID `json:"merged_into_id"`

	// Relinked How many child rows on each side were repointed from the merged- away person onto the survivor (people/merge.go relinkCounts).
	Relinked PublicEventPersonMergedRelinkCounts `json:"relinked"`
}

// PublicEventPersonMergedRelinkCounts How many child rows on each side were repointed from the merged- away person onto the survivor (people/merge.go relinkCounts).
type PublicEventPersonMergedRelinkCounts struct {
	// ActivityLinks activity_link rows relinked.
	ActivityLinks int64 `json:"activity_links"`

	// Emails person_email rows relinked.
	Emails int64 `json:"emails"`

	// Phones person_phone rows relinked.
	Phones int64 `json:"phones"`

	// Relationships relationship edge rows relinked.
	Relationships int64 `json:"relationships"`
}

// PublicEventPersonRestored Payload for person.restored. Never emitted today (no restore path exists for person); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type PublicEventPersonRestored struct{}

// PublicEventPersonUpdated Payload for person.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, a lead-promotion conversion note, a signature-enrichment fill, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type PublicEventPersonUpdated struct {
	// ChangedFields What this update touched, incl. runtime cf_* custom fields. The value shape depends on the emit site: a column patch carries a flat field → new-value entry, while the recompute/routing/relationship sites carry a `{delta: {...}}` sub-object (occasionally with a sibling `source`). Read a key's value as either form.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// PublicEventPipelineArchived Payload for pipeline.archived. Never emitted today (no archive path exists for pipeline); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type PublicEventPipelineArchived struct{}

// PublicEventPipelineCreated Payload for pipeline.created — a pipeline was created with its initial stage set in the same transaction.
type PublicEventPipelineCreated struct {
	// IsDefault Whether this pipeline is the workspace default.
	IsDefault bool `json:"is_default"`

	// Name The pipeline's name.
	Name string `json:"name"`

	// Stages The pipeline's initial stages, in the order created.
	Stages []PublicEventPipelineCreatedStage `json:"stages"`
}

// PublicEventPipelineCreatedStage One initial stage as declared on a pipeline.created event — the stage's own stage.created is NOT separately emitted for these (events.md §5.3b: one pipeline.created carries the whole set).
type PublicEventPipelineCreatedStage struct {
	// Name The stage's name.
	Name string `json:"name"`

	// Position The stage's position within the pipeline.
	Position int `json:"position"`

	// Semantic The stage's semantic (open | won | lost).
	Semantic string `json:"semantic"`
}

// PublicEventPipelineUpdated Payload for pipeline.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat name/is_default/position patch from UpdatePipeline, or a stage_positions reorder map from UpdateStage when a stage's position changes), so the honest shape is a change-set map rather than a fixed field list.
type PublicEventPipelineUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched (name, is_default, position, or stage_positions).
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// PublicEventRetentionApplied Payload for retention.applied — a retention/erasure action ran against one record. Four emit sites, four different runtime subjects: the embed-call sweep (ai_call), the voice-learning-signal content sweep (voice_learning_signal), a workspace's configured retention policy's object type (activity | deal | lead | person | ai_call_payload), and Art. 17 erasure (person) — none fixed enough for this schema to name, so this is dynamic-entity (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and each emit site supplies its own runtime entity type through storekit.EmitEventForEntity. policy/reason are a union across the sites — both telemetry sweeps set neither, the policy-driven sweep sets policy only, Art. 17 erasure sets reason only.
type PublicEventRetentionApplied struct {
	// Action The action that ran (archive | anonymize | erase).
	Action string `json:"action"`

	// Policy The retention policy that drove this action (absent for the fixed embed-call sweep and for Art. 17 erasure, neither of which is policy-configured).
	Policy *openapi_types.UUID `json:"policy,omitempty"`

	// Reason Why this action ran (Art. 17 erasure only — e.g. dsr_request; absent for both retention-sweep sites).
	Reason *string `json:"reason,omitempty"`
}

// PublicEventRoleChanged Payload for role.changed — a member's role assignments were replaced with the single target system role (identity/users.go's ChangeUserRole). from_role rides the payload only when the previous state was a single role — a multi-role history has no one "from".
type PublicEventRoleChanged struct {
	// By The admin who changed the role.
	By openapi_types.UUID `json:"by"`

	// FromRole The single prior role key (absent when the member held more than one role before this change).
	FromRole *string `json:"from_role,omitempty"`

	// ToRole The role key assigned.
	ToRole string `json:"to_role"`

	// UserId The member whose role changed.
	UserId openapi_types.UUID `json:"user_id"`
}

// PublicEventSignalDetected Payload for signal.detected — a signal was created (signals/signal.go's CreateSignal). entity_type/entity_id are DATA fields naming the signal's subject (deal | organization | person) when one is already known at creation time — not the envelope's own entity ref, which is the signal itself (this event's entity type is the static "signal"). Both are absent on a raw signal (only a raw_ref), which enters unresolved and waits for the resolver; resolution_confidence is set only when the signal was created already resolved.
type PublicEventSignalDetected struct {
	// SubjectEntityId The subject record's id — a payload data field, absent until a raw signal resolves.
	SubjectEntityId *openapi_types.UUID `json:"entity_id,omitempty"`

	// SubjectEntityType The subject record's type (deal | organization | person) — a payload data field, absent until a raw signal resolves (both entity fields set together). x-go-name avoids colliding with the generated EntityType() method, which names the ENVELOPE'S entity (always "signal"), not this data field.
	SubjectEntityType *string `json:"entity_type,omitempty"`

	// Kind The signal kind (stalled_deal | champion_left | reengagement | buying_intent | risk | other).
	Kind string `json:"kind"`

	// ResolutionConfidence The match confidence (0–1), set only when created already resolved.
	ResolutionConfidence *float32 `json:"resolution_confidence,omitempty"`

	// ResolutionState The raw→entity match outcome at creation time (resolved | low_confidence | unresolved | dropped).
	ResolutionState string `json:"resolution_state"`

	// Severity The signal's severity (info | warn | urgent).
	Severity string `json:"severity"`

	// SignalId The signal that was detected.
	SignalId openapi_types.UUID `json:"signal_id"`

	// SourceChannel Where the raw signal came from (derived | inbound | web | social | deal_room_engagement).
	SourceChannel string `json:"source_channel"`
}

// PublicEventSignalResolved Payload for signal.resolved — the resolver ran over a signal (signals/resolver.go's Resolve). The verdict IS the candidate count (P12): zero candidates drops the signal (resolved_org_id, resolved_person_id, matched_on, match_confidence all absent); exactly one resolves it to that org (resolved_org_id set, resolved_person_id set only under a recorded consent grant); several flags it low_confidence for review (matched_on/ match_confidence describe the top candidate, resolved_org_id stays absent).
type PublicEventSignalResolved struct {
	// MatchConfidence The top candidate's match confidence (0–1).
	MatchConfidence *float32 `json:"match_confidence,omitempty"`

	// MatchedOn The match basis of the top candidate (domain | name | prior_interaction).
	MatchedOn *string `json:"matched_on,omitempty"`

	// ResolutionState The state after resolving (resolved | low_confidence | dropped).
	ResolutionState string `json:"resolution_state"`

	// ResolvedOrgId The organization the signal resolved to (absent when dropped or ambiguous).
	ResolvedOrgId *openapi_types.UUID `json:"resolved_org_id,omitempty"`

	// ResolvedPersonId The consent-gated person the signal resolved to (absent unless an existing person under a recorded consent grant matched).
	ResolvedPersonId *openapi_types.UUID `json:"resolved_person_id,omitempty"`

	// SignalId The signal the resolver ran over.
	SignalId openapi_types.UUID `json:"signal_id"`
}

// PublicEventStageArchived Payload for stage.archived. Never emitted today (no archive path exists for stage); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type PublicEventStageArchived struct{}

// PublicEventStageCreated Payload for stage.created — a stage was added to a pipeline.
type PublicEventStageCreated struct {
	// Name The stage's name.
	Name string `json:"name"`

	// PipelineId The pipeline this stage belongs to.
	PipelineId openapi_types.UUID `json:"pipeline_id"`

	// Position The stage's position within the pipeline.
	Position int `json:"position"`

	// Semantic The stage's semantic (open | won | lost).
	Semantic string `json:"semantic"`

	// WinProbability The stage's win probability (won=100, lost=0, open=0..100).
	WinProbability int `json:"win_probability"`
}

// PublicEventStageUpdated Payload for stage.updated — a BOUNDED delta: UpdateStage's known mutable fields (name, semantic, win_probability) each carried only when this update touched them. A position change is instead published as ONE pipeline.updated with a stage_positions delta (never an N-way stage.updated), so position never appears here.
type PublicEventStageUpdated struct {
	// Name The stage's new name (absent when this update did not touch it).
	Name *string `json:"name,omitempty"`

	// PipelineId The pipeline this stage belongs to.
	PipelineId openapi_types.UUID `json:"pipeline_id"`

	// Semantic The stage's new semantic (absent when this update did not touch it).
	Semantic *string `json:"semantic,omitempty"`

	// WinProbability The stage's new win probability (absent when this update did not touch it).
	WinProbability *int `json:"win_probability,omitempty"`
}

// PublicEventUserDeactivated Payload for user.deactivated — a member's sessions and passports were hard-revoked (identity/users.go's DeactivateUser). reason is the operator-supplied free text, absent when none was given.
type PublicEventUserDeactivated struct {
	// By The admin who deactivated the member.
	By openapi_types.UUID `json:"by"`

	// Reason The operator-supplied reason (absent when none was given).
	Reason *string `json:"reason,omitempty"`

	// UserId The deactivated member.
	UserId openapi_types.UUID `json:"user_id"`
}

// PublicEventUserInvited Payload for user.invited — an admin provisioned a new active member with a single-use set-password token (identity/users.go's InviteUser).
type PublicEventUserInvited struct {
	// By The admin who issued the invite.
	By openapi_types.UUID `json:"by"`

	// Role The single system role key granted to the new member.
	Role string `json:"role"`

	// UserId The invited member.
	UserId openapi_types.UUID `json:"user_id"`
}

// PublicEventUserReactivated Payload for user.reactivated — a deactivated member was returned to active (identity/users.go's ReactivateUser).
type PublicEventUserReactivated struct {
	// By The admin who reactivated the member.
	By openapi_types.UUID `json:"by"`

	// UserId The reactivated member.
	UserId openapi_types.UUID `json:"user_id"`
}

// PublicEventVoiceBuildChanged Payload for voice.build_changed — a Voice DNA build was queued or an already-pending one was returned in place of a duplicate request (ai/voice_lifecycle.go's RequestBuild). stage/result_version/ status_code/next_attempt_at describe an in-flight or deferred build and are therefore absent on a freshly-queued one.
type PublicEventVoiceBuildChanged struct {
	// BuildId The build row.
	BuildId openapi_types.UUID `json:"build_id"`

	// CandidateAction The recommended next step for this build's candidate.
	CandidateAction string `json:"candidate_action"`

	// NextAttemptAt When a deferred build will next be attempted (absent unless deferred).
	NextAttemptAt *time.Time `json:"next_attempt_at,omitempty"`

	// ProfileId The profile this build belongs to.
	ProfileId openapi_types.UUID `json:"profile_id"`

	// Reason The human-approved reason for this build (onboarding | manual).
	Reason string `json:"reason"`

	// ResultVersion The profile version this build produced (absent until the build completes).
	ResultVersion *int `json:"result_version,omitempty"`

	// SourceCount The corpus's eligible source count this build was requested against.
	SourceCount int `json:"source_count"`

	// SourceHash The corpus content hash this build was requested against.
	SourceHash string `json:"source_hash"`

	// Stage The build's current pipeline stage (absent before it starts running).
	Stage *string `json:"stage,omitempty"`

	// Status The build's status (queued | deferred | running | completed | failed).
	Status string `json:"status"`

	// StatusCode A machine-readable status detail code (absent unless the build failed or deferred).
	StatusCode *string `json:"status_code,omitempty"`
}

// PublicEventVoiceCorpusChanged Payload for voice.corpus_changed — a UNION across four emit sites that all mutate the corpus feeding a profile's build: a source's inclusion/weight was updated (voice_source_mutations.go's recordSourceUpdate), a source was removed (RemoveSource), a source was ingested/re-ingested (voice_source_store.go's recordSourceIngest), or the whole corpus was cleared (voice_source_mutations.go's ClearCorpus). source_id/origin/register name the touched source and are therefore absent on the clear site, which acts on the corpus as a whole.
type PublicEventVoiceCorpusChanged struct {
	// Action What happened to the corpus (included | excluded | removed | cleared).
	Action string `json:"action"`

	// Origin The touched source's origin (manual | capture) (absent on the clear site).
	Origin *string `json:"origin,omitempty"`

	// ProfileId The profile whose corpus changed.
	ProfileId openapi_types.UUID `json:"profile_id"`

	// Register The touched source's register (email | social | long_form | spoken | general) (absent on the clear site).
	Register *string `json:"register,omitempty"`

	// SourceCount The corpus's eligible source count after this change.
	SourceCount int `json:"source_count"`

	// SourceHash The corpus's content hash after this change.
	SourceHash string `json:"source_hash"`

	// SourceId The source this change touched (absent on the clear site, which has no single source).
	SourceId *openapi_types.UUID `json:"source_id,omitempty"`

	// WordDelta The eligible-word-count change this action caused (may be negative).
	WordDelta int `json:"word_delta"`
}

// PublicEventVoiceDraftOutcomeRecorded Payload for voice.draft_outcome_recorded — a drafted-with-voice signal's outcome was recorded (ai/voice_history.go's RecordDraftOutcome), feeding the automatic-learning corpus.
type PublicEventVoiceDraftOutcomeRecorded struct {
	// Outcome The recorded outcome (drafted | sent_unedited | sent_edited | rejected).
	Outcome string `json:"outcome"`

	// ProfileId The profile this learning signal belongs to.
	ProfileId openapi_types.UUID `json:"profile_id"`

	// QualifiesAsSource Whether this draft's final text qualifies as a future corpus source.
	QualifiesAsSource bool `json:"qualifies_as_source"`

	// TransformationCount How many transformation edits were applied before send (0 for rejected).
	TransformationCount int `json:"transformation_count"`
}

// PublicEventVoiceProfileArchived Payload for voice.profile_archived — the owner's profile was soft-deleted (ai/voice.go's ArchiveProfile).
type PublicEventVoiceProfileArchived struct {
	// OwnerId The human who owned this profile.
	OwnerId openapi_types.UUID `json:"owner_id"`

	// ProfileId The archived profile.
	ProfileId openapi_types.UUID `json:"profile_id"`

	// ProfileVersion The profile's derived-artifact version at the moment it was archived.
	ProfileVersion int `json:"profile_version"`
}

// PublicEventVoiceProfileCreated Payload for voice.profile_created — the admitted human opened their one personal Voice DNA profile (ai/voice.go's CreateProfile). Always starts collecting, at maturity zero, with automatic learning off.
type PublicEventVoiceProfileCreated struct {
	// AutoLearningEnabled Whether automatic learning starts enabled (always false at creation).
	AutoLearningEnabled bool `json:"auto_learning_enabled"`

	// Maturity The corpus maturity band at creation (collecting, at zero words).
	Maturity string `json:"maturity"`

	// OwnerId The human who owns this profile.
	OwnerId openapi_types.UUID `json:"owner_id"`

	// ProfileId The created profile.
	ProfileId openapi_types.UUID `json:"profile_id"`
}

// PublicEventVoiceProfileUpdated Payload for voice.profile_updated — the owner replaced their human-authored preferences and/or their automatic-learning opt-in (ai/voice.go's UpdateProfile). action names which of the two (or both) this update touched.
type PublicEventVoiceProfileUpdated struct {
	// Action What this update did (preferences_replaced | learning_enabled | learning_disabled).
	Action string `json:"action"`

	// Maturity The corpus maturity band as of this update.
	Maturity string `json:"maturity"`

	// ProfileId The updated profile.
	ProfileId openapi_types.UUID `json:"profile_id"`

	// Version The profile row's optimistic-concurrency version after this update.
	Version int64 `json:"version"`
}

// PublicEventVoiceVersionChanged Payload for voice.version_changed — a derived Voice DNA version's status changed: minted as a candidate, manually activated, rejected, or restored by rollback (ai/voice_versions.go). predecessor_version is absent for a profile's first version, which has none.
type PublicEventVoiceVersionChanged struct {
	// ActivationOutcome What happened to this version (auto_activated | manually_activated | rejected | rollback).
	ActivationOutcome string `json:"activation_outcome"`

	// Classification The delta's classification against its predecessor (routine | material).
	Classification string `json:"classification"`

	// PredecessorVersion The version this one supersedes (absent for a profile's first version).
	PredecessorVersion *int `json:"predecessor_version,omitempty"`

	// ProfileId The profile this version belongs to.
	ProfileId openapi_types.UUID `json:"profile_id"`

	// ProfileVersion This version's number.
	ProfileVersion int `json:"profile_version"`

	// Reason Why this version was produced (e.g. build | rollback).
	Reason string `json:"reason"`

	// Status The version's status after this change (candidate | active | superseded | rejected).
	Status string `json:"status"`
}

// SubscribableEventType The closed set of domain event types a webhook subscription may select — every subscribable event across the deal, offer, pipeline/stage, person/organization, lead, activities, consent/privacy, signals, ai voice, identity, and overlay families. A subscription's event-type filter is validated against this set; an unlisted type cannot be subscribed to.
type SubscribableEventType string

func (PublicEventActivityArchived) EventType() string { return "activity.archived" }

func (PublicEventActivityArchived) EntityType() string { return "activity" }

func (PublicEventActivityCaptured) EventType() string { return "activity.captured" }

func (PublicEventActivityCaptured) EntityType() string { return "activity" }

func (PublicEventActivityUpdated) EventType() string { return "activity.updated" }

func (PublicEventActivityUpdated) EntityType() string { return "activity" }

func (PublicEventApprovalDecided) EventType() string { return "approval.decided" }

func (PublicEventApprovalDecided) EntityType() string { return "approval" }

func (PublicEventApprovalRequested) EventType() string { return "approval.requested" }

func (PublicEventApprovalRequested) EntityType() string { return "approval" }

func (PublicEventAuditAppended) EventType() string { return "audit.appended" }

func (PublicEventAuditAppended) EntityType() string { return "audit" }

func (PublicEventColdstartAccepted) EventType() string { return "coldstart.accepted" }

func (PublicEventColdstartAccepted) EntityType() string { return "approval" }

func (PublicEventColdstartReadBackProposed) EventType() string { return "coldstart.read_back_proposed" }

func (PublicEventColdstartReadBackProposed) EntityType() string { return "approval" }

func (PublicEventColdstartRejected) EventType() string { return "coldstart.rejected" }

func (PublicEventColdstartRejected) EntityType() string { return "approval" }

func (PublicEventConsentChanged) EventType() string { return "consent.changed" }

func (PublicEventConsentChanged) EntityType() string { return "dynamic" }

func (PublicEventDealArchived) EventType() string { return "deal.archived" }

func (PublicEventDealArchived) EntityType() string { return "deal" }

func (PublicEventDealCreated) EventType() string { return "deal.created" }

func (PublicEventDealCreated) EntityType() string { return "deal" }

func (PublicEventDealOwnerChanged) EventType() string { return "deal.owner_changed" }

func (PublicEventDealOwnerChanged) EntityType() string { return "deal" }

func (PublicEventDealRestored) EventType() string { return "deal.restored" }

func (PublicEventDealRestored) EntityType() string { return "deal" }

func (PublicEventDealStageChanged) EventType() string { return "deal.stage_changed" }

func (PublicEventDealStageChanged) EntityType() string { return "deal" }

func (PublicEventDealUpdated) EventType() string { return "deal.updated" }

func (PublicEventDealUpdated) EntityType() string { return "deal" }

func (PublicEventEngagementReply) EventType() string { return "engagement.reply" }

func (PublicEventEngagementReply) EntityType() string { return "activity" }

func (PublicEventIncumbentConnected) EventType() string { return "incumbent.connected" }

func (PublicEventIncumbentConnected) EntityType() string { return "incumbent_connection" }

func (PublicEventIncumbentDisconnected) EventType() string { return "incumbent.disconnected" }

func (PublicEventIncumbentDisconnected) EntityType() string { return "incumbent_connection" }

func (PublicEventLeadCreated) EventType() string { return "lead.created" }

func (PublicEventLeadCreated) EntityType() string { return "lead" }

func (PublicEventLeadDisqualified) EventType() string { return "lead.disqualified" }

func (PublicEventLeadDisqualified) EntityType() string { return "lead" }

func (PublicEventLeadPromoted) EventType() string { return "lead.promoted" }

func (PublicEventLeadPromoted) EntityType() string { return "lead" }

func (PublicEventLeadUpdated) EventType() string { return "lead.updated" }

func (PublicEventLeadUpdated) EntityType() string { return "lead" }

func (PublicEventMirrorBudgetDegraded) EventType() string { return "mirror.budget_degraded" }

func (PublicEventMirrorBudgetDegraded) EntityType() string { return "dynamic" }

func (PublicEventMirrorConflict) EventType() string { return "mirror.conflict" }

func (PublicEventMirrorConflict) EntityType() string { return "dynamic" }

func (PublicEventMirrorDeleted) EventType() string { return "mirror.deleted" }

func (PublicEventMirrorDeleted) EntityType() string { return "dynamic" }

func (PublicEventMirrorWriteRejected) EventType() string { return "mirror.write_rejected" }

func (PublicEventMirrorWriteRejected) EntityType() string { return "dynamic" }

func (PublicEventOfferAccepted) EventType() string { return "offer.accepted" }

func (PublicEventOfferAccepted) EntityType() string { return "offer" }

func (PublicEventOfferCreated) EventType() string { return "offer.created" }

func (PublicEventOfferCreated) EntityType() string { return "offer" }

func (PublicEventOfferRejected) EventType() string { return "offer.rejected" }

func (PublicEventOfferRejected) EntityType() string { return "offer" }

func (PublicEventOfferSent) EventType() string { return "offer.sent" }

func (PublicEventOfferSent) EntityType() string { return "offer" }

func (PublicEventOfferSuperseded) EventType() string { return "offer.superseded" }

func (PublicEventOfferSuperseded) EntityType() string { return "offer" }

func (PublicEventOnboardingStateChanged) EventType() string { return "onboarding.state_changed" }

func (PublicEventOnboardingStateChanged) EntityType() string { return "onboarding_wizard_state" }

func (PublicEventOrganizationArchived) EventType() string { return "organization.archived" }

func (PublicEventOrganizationArchived) EntityType() string { return "organization" }

func (PublicEventOrganizationCreated) EventType() string { return "organization.created" }

func (PublicEventOrganizationCreated) EntityType() string { return "organization" }

func (PublicEventOrganizationMerged) EventType() string { return "organization.merged" }

func (PublicEventOrganizationMerged) EntityType() string { return "organization" }

func (PublicEventOrganizationUpdated) EventType() string { return "organization.updated" }

func (PublicEventOrganizationUpdated) EntityType() string { return "organization" }

func (PublicEventPassportRevoked) EventType() string { return "passport.revoked" }

func (PublicEventPassportRevoked) EntityType() string { return "passport" }

func (PublicEventPersonArchived) EventType() string { return "person.archived" }

func (PublicEventPersonArchived) EntityType() string { return "person" }

func (PublicEventPersonCreated) EventType() string { return "person.created" }

func (PublicEventPersonCreated) EntityType() string { return "person" }

func (PublicEventPersonMerged) EventType() string { return "person.merged" }

func (PublicEventPersonMerged) EntityType() string { return "person" }

func (PublicEventPersonRestored) EventType() string { return "person.restored" }

func (PublicEventPersonRestored) EntityType() string { return "person" }

func (PublicEventPersonUpdated) EventType() string { return "person.updated" }

func (PublicEventPersonUpdated) EntityType() string { return "person" }

func (PublicEventPipelineArchived) EventType() string { return "pipeline.archived" }

func (PublicEventPipelineArchived) EntityType() string { return "pipeline" }

func (PublicEventPipelineCreated) EventType() string { return "pipeline.created" }

func (PublicEventPipelineCreated) EntityType() string { return "pipeline" }

func (PublicEventPipelineUpdated) EventType() string { return "pipeline.updated" }

func (PublicEventPipelineUpdated) EntityType() string { return "pipeline" }

func (PublicEventRetentionApplied) EventType() string { return "retention.applied" }

func (PublicEventRetentionApplied) EntityType() string { return "dynamic" }

func (PublicEventRoleChanged) EventType() string { return "role.changed" }

func (PublicEventRoleChanged) EntityType() string { return "user" }

func (PublicEventSignalDetected) EventType() string { return "signal.detected" }

func (PublicEventSignalDetected) EntityType() string { return "signal" }

func (PublicEventSignalResolved) EventType() string { return "signal.resolved" }

func (PublicEventSignalResolved) EntityType() string { return "signal" }

func (PublicEventStageArchived) EventType() string { return "stage.archived" }

func (PublicEventStageArchived) EntityType() string { return "stage" }

func (PublicEventStageCreated) EventType() string { return "stage.created" }

func (PublicEventStageCreated) EntityType() string { return "stage" }

func (PublicEventStageUpdated) EventType() string { return "stage.updated" }

func (PublicEventStageUpdated) EntityType() string { return "stage" }

func (PublicEventUserDeactivated) EventType() string { return "user.deactivated" }

func (PublicEventUserDeactivated) EntityType() string { return "user" }

func (PublicEventUserInvited) EventType() string { return "user.invited" }

func (PublicEventUserInvited) EntityType() string { return "user" }

func (PublicEventUserReactivated) EventType() string { return "user.reactivated" }

func (PublicEventUserReactivated) EntityType() string { return "user" }

func (PublicEventVoiceBuildChanged) EventType() string { return "voice.build_changed" }

func (PublicEventVoiceBuildChanged) EntityType() string { return "voice_profile" }

func (PublicEventVoiceCorpusChanged) EventType() string { return "voice.corpus_changed" }

func (PublicEventVoiceCorpusChanged) EntityType() string { return "voice_profile" }

func (PublicEventVoiceDraftOutcomeRecorded) EventType() string { return "voice.draft_outcome_recorded" }

func (PublicEventVoiceDraftOutcomeRecorded) EntityType() string { return "voice_profile" }

func (PublicEventVoiceProfileArchived) EventType() string { return "voice.profile_archived" }

func (PublicEventVoiceProfileArchived) EntityType() string { return "voice_profile" }

func (PublicEventVoiceProfileCreated) EventType() string { return "voice.profile_created" }

func (PublicEventVoiceProfileCreated) EntityType() string { return "voice_profile" }

func (PublicEventVoiceProfileUpdated) EventType() string { return "voice.profile_updated" }

func (PublicEventVoiceProfileUpdated) EntityType() string { return "voice_profile" }

func (PublicEventVoiceVersionChanged) EventType() string { return "voice.version_changed" }

func (PublicEventVoiceVersionChanged) EntityType() string { return "voice_profile" }

// PublicEventVersions maps every subscribable event type carrying a
// PublicEvent<Event> schema to that schema's x-version extension
// (default 1 when absent). It is the single generated source of truth for
// both the coverage gate (every subscribable event type must be a key here)
// and the version gate (VersionOf(type) must equal this map's value).
var PublicEventVersions = map[string]int{
	"activity.archived":            1,
	"activity.captured":            1,
	"activity.updated":             1,
	"approval.decided":             1,
	"approval.requested":           1,
	"audit.appended":               1,
	"coldstart.accepted":           1,
	"coldstart.read_back_proposed": 1,
	"coldstart.rejected":           1,
	"consent.changed":              1,
	"deal.archived":                1,
	"deal.created":                 1,
	"deal.owner_changed":           1,
	"deal.restored":                1,
	"deal.stage_changed":           1,
	"deal.updated":                 1,
	"engagement.reply":             1,
	"incumbent.connected":          1,
	"incumbent.disconnected":       1,
	"lead.created":                 1,
	"lead.disqualified":            1,
	"lead.promoted":                1,
	"lead.updated":                 1,
	"mirror.budget_degraded":       1,
	"mirror.conflict":              1,
	"mirror.deleted":               1,
	"mirror.write_rejected":        1,
	"offer.accepted":               1,
	"offer.created":                1,
	"offer.rejected":               1,
	"offer.sent":                   1,
	"offer.superseded":             1,
	"onboarding.state_changed":     1,
	"organization.archived":        1,
	"organization.created":         1,
	"organization.merged":          1,
	"organization.updated":         1,
	"passport.revoked":             1,
	"person.archived":              1,
	"person.created":               1,
	"person.merged":                1,
	"person.restored":              1,
	"person.updated":               1,
	"pipeline.archived":            1,
	"pipeline.created":             1,
	"pipeline.updated":             1,
	"retention.applied":            1,
	"role.changed":                 1,
	"signal.detected":              1,
	"signal.resolved":              1,
	"stage.archived":               1,
	"stage.created":                1,
	"stage.updated":                1,
	"user.deactivated":             1,
	"user.invited":                 1,
	"user.reactivated":             1,
	"voice.build_changed":          1,
	"voice.corpus_changed":         1,
	"voice.draft_outcome_recorded": 1,
	"voice.profile_archived":       1,
	"voice.profile_created":        1,
	"voice.profile_updated":        1,
	"voice.version_changed":        1,
}
