// Code generated by gen-payloads; DO NOT EDIT.

package crmcontracts

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SubscribableEventType.
const (
	ActivityArchived     SubscribableEventType = "activity.archived"
	ActivityCaptured     SubscribableEventType = "activity.captured"
	ActivityUpdated      SubscribableEventType = "activity.updated"
	ConsentChanged       SubscribableEventType = "consent.changed"
	DealArchived         SubscribableEventType = "deal.archived"
	DealCreated          SubscribableEventType = "deal.created"
	DealOwnerChanged     SubscribableEventType = "deal.owner_changed"
	DealRestored         SubscribableEventType = "deal.restored"
	DealStageChanged     SubscribableEventType = "deal.stage_changed"
	DealUpdated          SubscribableEventType = "deal.updated"
	EngagementReply      SubscribableEventType = "engagement.reply"
	LeadCreated          SubscribableEventType = "lead.created"
	LeadDisqualified     SubscribableEventType = "lead.disqualified"
	LeadPromoted         SubscribableEventType = "lead.promoted"
	LeadUpdated          SubscribableEventType = "lead.updated"
	OfferAccepted        SubscribableEventType = "offer.accepted"
	OfferCreated         SubscribableEventType = "offer.created"
	OfferRejected        SubscribableEventType = "offer.rejected"
	OfferSent            SubscribableEventType = "offer.sent"
	OfferSuperseded      SubscribableEventType = "offer.superseded"
	OrganizationArchived SubscribableEventType = "organization.archived"
	OrganizationCreated  SubscribableEventType = "organization.created"
	OrganizationMerged   SubscribableEventType = "organization.merged"
	OrganizationUpdated  SubscribableEventType = "organization.updated"
	PersonArchived       SubscribableEventType = "person.archived"
	PersonCreated        SubscribableEventType = "person.created"
	PersonMerged         SubscribableEventType = "person.merged"
	PersonRestored       SubscribableEventType = "person.restored"
	PersonUpdated        SubscribableEventType = "person.updated"
	PipelineArchived     SubscribableEventType = "pipeline.archived"
	PipelineCreated      SubscribableEventType = "pipeline.created"
	PipelineUpdated      SubscribableEventType = "pipeline.updated"
	RetentionApplied     SubscribableEventType = "retention.applied"
	SignalDetected       SubscribableEventType = "signal.detected"
	SignalResolved       SubscribableEventType = "signal.resolved"
	StageArchived        SubscribableEventType = "stage.archived"
	StageCreated         SubscribableEventType = "stage.created"
	StageUpdated         SubscribableEventType = "stage.updated"
)

// Valid indicates whether the value is a known member of the SubscribableEventType enum.
func (e SubscribableEventType) Valid() bool {
	switch e {
	case ActivityArchived:
		return true
	case ActivityCaptured:
		return true
	case ActivityUpdated:
		return true
	case ConsentChanged:
		return true
	case DealArchived:
		return true
	case DealCreated:
		return true
	case DealOwnerChanged:
		return true
	case DealRestored:
		return true
	case DealStageChanged:
		return true
	case DealUpdated:
		return true
	case EngagementReply:
		return true
	case LeadCreated:
		return true
	case LeadDisqualified:
		return true
	case LeadPromoted:
		return true
	case LeadUpdated:
		return true
	case OfferAccepted:
		return true
	case OfferCreated:
		return true
	case OfferRejected:
		return true
	case OfferSent:
		return true
	case OfferSuperseded:
		return true
	case OrganizationArchived:
		return true
	case OrganizationCreated:
		return true
	case OrganizationMerged:
		return true
	case OrganizationUpdated:
		return true
	case PersonArchived:
		return true
	case PersonCreated:
		return true
	case PersonMerged:
		return true
	case PersonRestored:
		return true
	case PersonUpdated:
		return true
	case PipelineArchived:
		return true
	case PipelineCreated:
		return true
	case PipelineUpdated:
		return true
	case RetentionApplied:
		return true
	case SignalDetected:
		return true
	case SignalResolved:
		return true
	case StageArchived:
		return true
	case StageCreated:
		return true
	case StageUpdated:
		return true
	default:
		return false
	}
}

// SubscribableEventType The closed set of domain events a webhook subscription can select. Phase 4 fills this out family by family; today it carries the pilot event plus the deal family (Task 5a-i), the offer family (Task 5a-ii), the pipeline/stage config family (Task 5a-iii), and the person/organization family (Task 5b-personorg), the lead family (Task 5b-lead), the activities family (Task 5c), the consent/privacy family (Task 5d), and the signals family (Task 5e).
type SubscribableEventType string

// WebhookActivityChangedFields activity.updated's BOUNDED delta: UpdateActivity's known mutable fields (subject, body, occurred_at, due_at, remind_at, assignee_id, is_done) each carried only when this update touched them, plus RelinkActivity's relinked target — a fixed, KNOWN key set (unlike person/organization/deal/lead.updated's genuinely open patch), so it is typed rather than an open map.
type WebhookActivityChangedFields struct {
	// AssigneeId The activity's new assignee (absent when this update did not touch it).
	AssigneeId *openapi_types.UUID `json:"assignee_id,omitempty"`

	// Body Whether the body was touched (a presence flag, not the content — bodies can be large and are never echoed onto the wire).
	Body *bool `json:"body,omitempty"`

	// DueAt The activity's new due_at (absent when this update did not touch it).
	DueAt *time.Time `json:"due_at,omitempty"`

	// IsDone The activity's new completion state (absent when this update did not touch it).
	IsDone *bool `json:"is_done,omitempty"`

	// OccurredAt The activity's new occurred_at (absent when this update did not touch it).
	OccurredAt *time.Time `json:"occurred_at,omitempty"`

	// Relinked The entity an activity was relinked onto (activities/lifecycle.go's RelinkActivity) — an association change, not a re-capture, so it travels as one changed_fields key rather than its own event verb.
	Relinked *WebhookActivityRelinkedRef `json:"relinked,omitempty"`

	// RemindAt The activity's new remind_at (absent when this update did not touch it).
	RemindAt *time.Time `json:"remind_at,omitempty"`

	// Subject The activity's new subject (absent when this update did not touch it).
	Subject *string `json:"subject,omitempty"`
}

// WebhookActivityRelinkedRef The entity an activity was relinked onto (activities/lifecycle.go's RelinkActivity) — an association change, not a re-capture, so it travels as one changed_fields key rather than its own event verb.
type WebhookActivityRelinkedRef struct {
	// EntityId The relink target's id.
	EntityId openapi_types.UUID `json:"entity_id"`

	// EntityType The relink target's kind (person | organization | deal | lead).
	EntityType string `json:"entity_type"`
}

// WebhookActor Who or what caused the event, as exposed publicly.
type WebhookActor struct {
	// Type Actor kind (e.g. human, agent, connector).
	Type string `json:"type"`
}

// WebhookDeliveryEnvelope The public wrapper around every delivered event payload. This is the exact JSON shape a subscriber receives; it carries no internal metadata.
type WebhookDeliveryEnvelope struct {
	// Actor Who or what caused the event, as exposed publicly.
	Actor WebhookActor `json:"actor"`

	// CorrelationId Correlates all events emitted for one originating request.
	CorrelationId openapi_types.UUID `json:"correlation_id"`

	// Data The typed event payload (one of the WebhookPayload* schemas).
	Data map[string]interface{} `json:"data"`

	// Entity The primary entity the event concerns.
	Entity WebhookEntityRef `json:"entity"`

	// EventId Unique id of this event occurrence.
	EventId openapi_types.UUID `json:"event_id"`

	// OccurredAt When the event occurred (RFC 3339).
	OccurredAt time.Time `json:"occurred_at"`

	// Type The event type (a SubscribableEventType value).
	Type string `json:"type"`

	// Version Schema version of the payload in data.
	Version int `json:"version"`
}

// WebhookEntityRef The primary entity the event concerns.
type WebhookEntityRef struct {
	// Id Stable identifier of the entity.
	Id openapi_types.UUID `json:"id"`

	// Type Entity kind (e.g. deal, person, organization).
	Type string `json:"type"`
}

// WebhookPayloadActivityArchived Payload for activity.archived — an activity was archived. Carries no data.
type WebhookPayloadActivityArchived struct{}

// WebhookPayloadActivityCaptured Payload for activity.captured — the first-class capture verb, emitted instead of (never alongside) a generic activity.created (events.md §1). Two emit sites: the direct-log path (activities/activity.go) that sets kind only, and the capture ingestion path (capture/sink.go) that also names its originating source system.
type WebhookPayloadActivityCaptured struct {
	// Kind The activity kind (email | call | meeting | note | whatsapp | telegram). Decoded by automation/handlers_event.go's post_meeting_recap trigger — this field's JSON key is a binding contract, not just documentation.
	Kind string `json:"kind"`

	// SourceSystem The originating source system (capture ingestion only; absent on a direct log).
	SourceSystem *string `json:"source_system,omitempty"`
}

// WebhookPayloadActivityUpdated Payload for activity.updated — a BOUNDED delta (unlike the person/organization/deal/lead family's genuinely open patch): UpdateActivity and RelinkActivity together cover a fixed, KNOWN set of inner keys, so changed_fields is a typed struct here, not an open map.
type WebhookPayloadActivityUpdated struct {
	// ChangedFields activity.updated's BOUNDED delta: UpdateActivity's known mutable fields (subject, body, occurred_at, due_at, remind_at, assignee_id, is_done) each carried only when this update touched them, plus RelinkActivity's relinked target — a fixed, KNOWN key set (unlike person/organization/deal/lead.updated's genuinely open patch), so it is typed rather than an open map.
	ChangedFields WebhookActivityChangedFields `json:"changed_fields"`
}

// WebhookPayloadConsentChanged Payload for consent.changed — a subject's per-purpose consent state was recorded (consent/store.go's Record). The subject is a person XOR a lead (data-model §7, before promotion) — a RUNTIME choice Record resolves via consentSubject, not a fixed type this schema can name, so this is the first dynamic-entity event (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and the emit site supplies the real entity type through storekit.EmitEventForEntity.
type WebhookPayloadConsentChanged struct {
	// NewState The state now on record (granted | withdrawn).
	NewState string `json:"new_state"`

	// Purpose The purpose's key (e.g. marketing_email).
	Purpose string `json:"purpose"`

	// PurposeId The consent purpose this state change applies to.
	PurposeId openapi_types.UUID `json:"purpose_id"`
}

// WebhookPayloadDealArchived Payload for deal.archived — a deal was archived. Carries no data.
type WebhookPayloadDealArchived struct{}

// WebhookPayloadDealCreated Payload for deal.created — a deal was opened.
type WebhookPayloadDealCreated struct {
	// Name The deal's name at creation.
	Name string `json:"name"`
}

// WebhookPayloadDealOwnerChanged Payload for deal.owner_changed — the deal's owner was reassigned. Emitted instead of (never alongside) deal.updated for the owner_id field (events.md §5.3).
type WebhookPayloadDealOwnerChanged struct {
	// FromOwnerId The previous owner (absent when the deal had none).
	FromOwnerId *openapi_types.UUID `json:"from_owner_id,omitempty"`

	// ToOwnerId The new owner.
	ToOwnerId openapi_types.UUID `json:"to_owner_id"`
}

// WebhookPayloadDealRestored Payload for deal.restored. Never emitted today (no restore path exists for deal); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadDealRestored struct{}

// WebhookPayloadDealStageChanged Payload for deal.stage_changed — a deal advanced between stages. Carries the amount/win-probability snapshot frozen at the moment of the move so consumers (the trajectory view, the overnight stalled/forecast sweep, the automation trigger keyed on to_status) never need a read-back.
type WebhookPayloadDealStageChanged struct {
	// AmountMinorAtChange The deal's amount, frozen at the moment of the move.
	AmountMinorAtChange *int64 `json:"amount_minor_at_change,omitempty"`

	// CurrencyAtChange The deal's currency, frozen at the moment of the move.
	CurrencyAtChange *string `json:"currency_at_change,omitempty"`

	// FromStageId Stage the deal left (absent on first placement).
	FromStageId *openapi_types.UUID `json:"from_stage_id,omitempty"`

	// FromStatus Deal status before the move (open | won | lost).
	FromStatus string `json:"from_status"`

	// ToStageId Stage the deal entered.
	ToStageId openapi_types.UUID `json:"to_stage_id"`

	// ToStatus Deal status after the move (open | won | lost) — the field the automation trigger keys on (automation/handlers_event.go).
	ToStatus string `json:"to_status"`

	// WinProbability The target stage's win probability, frozen at the moment of the move.
	WinProbability int `json:"win_probability"`
}

// WebhookPayloadDealUpdated Payload for deal.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, an accepted-offer amount sync, a close-date-correction note, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadDealUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadEngagementReply Payload for engagement.reply — CAP-FORMULA-1: an inbound message in a thread we previously wrote outbound in is a reply, feeding the engagement signal scoring (capture/sink.go's emitReply).
type WebhookPayloadEngagementReply struct {
	// Channel The channel the reply arrived on (today always email).
	Channel string `json:"channel"`

	// ContactId The already-known person behind the counterparty address (absent when the counterparty resolves only in a follow-up ensure).
	ContactId *openapi_types.UUID `json:"contact_id,omitempty"`

	// IdempotencyKey The capture natural key (source_system:source_id) this reply was detected from.
	IdempotencyKey string `json:"idempotency_key"`

	// MatchedOutboundActivityId The prior outbound activity this inbound message replies to.
	MatchedOutboundActivityId openapi_types.UUID `json:"matched_outbound_activity_id"`

	// OccurredAt When the reply activity occurred.
	OccurredAt time.Time `json:"occurred_at"`
}

// WebhookPayloadLeadCreated Payload for lead.created — a lead was created. Two emit sites: a direct create (people/lead.go) that sets no fields, and the capture auto-create engine (capture/sink.go) that names its originating source system; source_system is therefore optional.
type WebhookPayloadLeadCreated struct {
	// SourceSystem The originating source system (capture auto-create only; absent on a direct create).
	SourceSystem *string `json:"source_system,omitempty"`
}

// WebhookPayloadLeadDisqualified Payload for lead.disqualified — a lead was disqualified. Carries no data.
type WebhookPayloadLeadDisqualified struct{}

// WebhookPayloadLeadPromoted Payload for lead.promoted — the lead's genuine-engagement promotion into the context graph (events.md §5.5); its own verb, never a lead.updated, since neither person.created nor person.updated on its own says a lead crossed this line.
type WebhookPayloadLeadPromoted struct {
	// DedupeOutcome Whether promotion created a new person or merged into an existing one: created or merged.
	DedupeOutcome string `json:"dedupe_outcome"`

	// EvidenceRef The inbound activity that evidenced the trigger (absent for a human_qualify with no linked activity).
	EvidenceRef *openapi_types.UUID `json:"evidence_ref,omitempty"`

	// PromotedPersonId The person this lead promoted into (fresh or an existing survivor).
	PromotedPersonId openapi_types.UUID `json:"promoted_person_id"`

	// Trigger The genuine-engagement trigger that authorized promotion: inbound_reply, meeting_booked, meeting_held, or human_qualify.
	Trigger string `json:"trigger"`
}

// WebhookPayloadLeadUpdated Payload for lead.updated — an OPEN envelope: emit sites carry divergent shapes (a flat column patch that includes runtime cf_* custom-field columns, and behavioral-recompute/routing deltas), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadLeadUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadOfferAccepted Payload for offer.accepted — a sent offer was accepted. The deal's headline amount is synced from this offer's gross in the same transaction (see deal.updated on the paired deal entity).
type WebhookPayloadOfferAccepted struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// GrossMinor The offer's gross total, now also the deal's amount.
	GrossMinor *int64 `json:"gross_minor,omitempty"`

	// OfferId The accepted offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`
}

// WebhookPayloadOfferCreated Payload for offer.created — a new Angebot revision was opened (either the first revision, via CreateOffer, or a fresh draft revision minted by RegenerateOffer).
type WebhookPayloadOfferCreated struct {
	// CapturedBy The principal that created this revision.
	CapturedBy string `json:"captured_by"`

	// Currency The offer's currency.
	Currency string `json:"currency"`

	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// OfferId The created offer revision.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number (1 for a first offer).
	Revision int `json:"revision"`

	// Source Where this offer originated (e.g. manual, ai).
	Source string `json:"source"`
}

// WebhookPayloadOfferRejected Payload for offer.rejected — a sent offer was rejected.
type WebhookPayloadOfferRejected struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// OfferId The rejected offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Reason The optional rejection reason (absent when none was given).
	Reason *string `json:"reason,omitempty"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`
}

// WebhookPayloadOfferSent Payload for offer.sent — a draft offer left the workspace. Carries the FX rate frozen at send time (RT-PR-C2) so consumers never need a read-back for the native-currency-to-base conversion.
type WebhookPayloadOfferSent struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// FxRateToBase Native→base rate frozen at send (RT-PR-C2). Decimal-as-string to avoid float rounding.
	FxRateToBase string `json:"fx_rate_to_base"`

	// GrossMinor The offer's gross total at send time.
	GrossMinor *int64 `json:"gross_minor,omitempty"`

	// OfferId The sent offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`

	// ValidUntil The offer's validity date (absent when unset).
	ValidUntil *openapi_types.Date `json:"valid_until,omitempty"`
}

// WebhookPayloadOfferSuperseded Payload for offer.superseded — a sent offer was regenerated into a fresh draft revision (B-E03.19) and marked superseded; the new revision arrives as its own offer.created event.
type WebhookPayloadOfferSuperseded struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// FromRevision The superseded revision number.
	FromRevision *int `json:"from_revision,omitempty"`

	// OfferId The superseded (prior) offer revision.
	OfferId openapi_types.UUID `json:"offer_id"`

	// ToRevision The new revision number minted by the regenerate.
	ToRevision int `json:"to_revision"`
}

// WebhookPayloadOrganizationArchived Payload for organization.archived — an organization was archived. Carries no data.
type WebhookPayloadOrganizationArchived struct{}

// WebhookPayloadOrganizationCreated Payload for organization.created — a UNION across five emit sites (a direct create, the capture auto-create engine, the anchor company save, the site-read confirmation, and the cold-start profile apply), each of which sets only its own subset; every field is therefore optional.
type WebhookPayloadOrganizationCreated struct {
	// Anchor Whether this is the installation's own anchor organization (company save only).
	Anchor *bool `json:"anchor,omitempty"`

	// CapturedBy The principal that created this organization.
	CapturedBy *string `json:"captured_by,omitempty"`

	// Delta The fields the creating site applied (company save / site-read confirmation only).
	Delta *map[string]interface{} `json:"delta,omitempty"`

	// DisplayName The organization's display name at creation (absent when the site never set one).
	DisplayName *string `json:"display_name,omitempty"`

	// PrimaryDomain The organization's primary domain (cold-start apply only).
	PrimaryDomain *string `json:"primary_domain,omitempty"`

	// SiteReadId The site-read that produced this organization (site-read confirmation only).
	SiteReadId *openapi_types.UUID `json:"site_read_id,omitempty"`

	// Source Where this organization originated (e.g. human, site_read).
	Source *string `json:"source,omitempty"`

	// SourceUrl The source page this organization was read from (site-read confirmation only).
	SourceUrl *string `json:"source_url,omitempty"`
}

// WebhookPayloadOrganizationMerged Payload for organization.merged — two organization records collapsed into one (the §1.3 merge); neither organization.updated nor organization.archived can say this, so it is its own verb.
type WebhookPayloadOrganizationMerged struct {
	// MergedFromId The merged-away (source) organization, retired but still fetchable by id.
	MergedFromId openapi_types.UUID `json:"merged_from_id"`

	// MergedIntoId The survivor (target) organization.
	MergedIntoId openapi_types.UUID `json:"merged_into_id"`
}

// WebhookPayloadOrganizationUpdated Payload for organization.updated — an OPEN envelope: eight emit sites carry divergent shapes (a flat column patch, the anchor company save's field delta, the partner extension's nested delta, enrichment/deep-read applies, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadOrganizationUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadPersonArchived Payload for person.archived — a person was archived. Carries no data.
type WebhookPayloadPersonArchived struct{}

// WebhookPayloadPersonCreated Payload for person.created — a person was created.
type WebhookPayloadPersonCreated struct {
	// FullName The person's name at creation.
	FullName string `json:"full_name"`
}

// WebhookPayloadPersonMerged Payload for person.merged — two person records collapsed into one (the §1.3 merge); neither person.updated nor person.archived can say this, so it is its own verb.
type WebhookPayloadPersonMerged struct {
	// MergedFromId The merged-away (source) person, retired but still fetchable by id.
	MergedFromId openapi_types.UUID `json:"merged_from_id"`

	// MergedIntoId The survivor (target) person.
	MergedIntoId openapi_types.UUID `json:"merged_into_id"`

	// Relinked How many child rows on each side were repointed from the merged- away person onto the survivor (people/merge.go relinkCounts).
	Relinked WebhookPersonMergedRelinkCounts `json:"relinked"`
}

// WebhookPayloadPersonRestored Payload for person.restored. Never emitted today (no restore path exists for person); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadPersonRestored struct{}

// WebhookPayloadPersonUpdated Payload for person.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, a lead-promotion conversion note, a signature-enrichment fill, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadPersonUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadPipelineArchived Payload for pipeline.archived. Never emitted today (no archive path exists for pipeline); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadPipelineArchived struct{}

// WebhookPayloadPipelineCreated Payload for pipeline.created — a pipeline was created with its initial stage set in the same transaction.
type WebhookPayloadPipelineCreated struct {
	// IsDefault Whether this pipeline is the workspace default.
	IsDefault bool `json:"is_default"`

	// Name The pipeline's name.
	Name string `json:"name"`

	// Stages The pipeline's initial stages, in the order created.
	Stages []WebhookPipelineCreatedStage `json:"stages"`
}

// WebhookPayloadPipelineUpdated Payload for pipeline.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat name/is_default/position patch from UpdatePipeline, or a stage_positions reorder map from UpdateStage when a stage's position changes), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadPipelineUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched (name, is_default, position, or stage_positions).
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadRetentionApplied Payload for retention.applied — a retention/erasure action ran against one record. Three emit sites, three different runtime subjects: the embed-call sweep (ai_call), a workspace's configured retention policy's object type (activity | deal | lead | person | ai_call_payload), and Art. 17 erasure (person) — none fixed enough for this schema to name, so this is dynamic-entity (contract `x-entity-type: dynamic`): the generated EntityType() is unused, and each emit site supplies its own runtime entity type through storekit.EmitEventForEntity. policy/reason are a union across the three sites — the embed-call sweep sets neither, the policy-driven sweep sets policy only, Art. 17 erasure sets reason only.
type WebhookPayloadRetentionApplied struct {
	// Action The action that ran (archive | anonymize | erase).
	Action string `json:"action"`

	// Policy The retention policy that drove this action (absent for the fixed embed-call sweep and for Art. 17 erasure, neither of which is policy-configured).
	Policy *openapi_types.UUID `json:"policy,omitempty"`

	// Reason Why this action ran (Art. 17 erasure only — e.g. dsr_request; absent for both retention-sweep sites).
	Reason *string `json:"reason,omitempty"`
}

// WebhookPayloadSignalDetected Payload for signal.detected — a signal was created (signals/signal.go's CreateSignal). entity_type/entity_id are DATA fields naming the signal's subject (deal | organization | person) when one is already known at creation time — not the envelope's own entity ref, which is the signal itself (this event's entity type is the static "signal"). Both are absent on a raw signal (only a raw_ref), which enters unresolved and waits for the resolver; resolution_confidence is set only when the signal was created already resolved.
type WebhookPayloadSignalDetected struct {
	// SubjectEntityId The subject record's id — a payload data field, absent until a raw signal resolves.
	SubjectEntityId *openapi_types.UUID `json:"entity_id,omitempty"`

	// SubjectEntityType The subject record's type (deal | organization | person) — a payload data field, absent until a raw signal resolves (both entity fields set together). x-go-name avoids colliding with the generated EntityType() method, which names the ENVELOPE'S entity (always "signal"), not this data field.
	SubjectEntityType *string `json:"entity_type,omitempty"`

	// Kind The signal kind (stalled_deal | champion_left | reengagement | buying_intent | risk | other).
	Kind string `json:"kind"`

	// ResolutionConfidence The match confidence (0–1), set only when created already resolved.
	ResolutionConfidence *float32 `json:"resolution_confidence,omitempty"`

	// ResolutionState The raw→entity match outcome at creation time (resolved | low_confidence | unresolved | dropped).
	ResolutionState string `json:"resolution_state"`

	// Severity The signal's severity (info | warn | urgent).
	Severity string `json:"severity"`

	// SignalId The signal that was detected.
	SignalId openapi_types.UUID `json:"signal_id"`

	// SourceChannel Where the raw signal came from (derived | inbound | web | social | deal_room_engagement).
	SourceChannel string `json:"source_channel"`
}

// WebhookPayloadSignalResolved Payload for signal.resolved — the resolver ran over a signal (signals/resolver.go's Resolve). The verdict IS the candidate count (P12): zero candidates drops the signal (resolved_org_id, resolved_person_id, matched_on, match_confidence all absent); exactly one resolves it to that org (resolved_org_id set, resolved_person_id set only under a recorded consent grant); several flags it low_confidence for review (matched_on/ match_confidence describe the top candidate, resolved_org_id stays absent).
type WebhookPayloadSignalResolved struct {
	// MatchConfidence The top candidate's match confidence (0–1).
	MatchConfidence *float32 `json:"match_confidence,omitempty"`

	// MatchedOn The match basis of the top candidate (domain | name | prior_interaction).
	MatchedOn *string `json:"matched_on,omitempty"`

	// ResolutionState The state after resolving (resolved | low_confidence | dropped).
	ResolutionState string `json:"resolution_state"`

	// ResolvedOrgId The organization the signal resolved to (absent when dropped or ambiguous).
	ResolvedOrgId *openapi_types.UUID `json:"resolved_org_id,omitempty"`

	// ResolvedPersonId The consent-gated person the signal resolved to (absent unless an existing person under a recorded consent grant matched).
	ResolvedPersonId *openapi_types.UUID `json:"resolved_person_id,omitempty"`

	// SignalId The signal the resolver ran over.
	SignalId openapi_types.UUID `json:"signal_id"`
}

// WebhookPayloadStageArchived Payload for stage.archived. Never emitted today (no archive path exists for stage); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadStageArchived struct{}

// WebhookPayloadStageCreated Payload for stage.created — a stage was added to a pipeline.
type WebhookPayloadStageCreated struct {
	// Name The stage's name.
	Name string `json:"name"`

	// PipelineId The pipeline this stage belongs to.
	PipelineId openapi_types.UUID `json:"pipeline_id"`

	// Position The stage's position within the pipeline.
	Position int `json:"position"`

	// Semantic The stage's semantic (open | won | lost).
	Semantic string `json:"semantic"`

	// WinProbability The stage's win probability (won=100, lost=0, open=0..100).
	WinProbability int `json:"win_probability"`
}

// WebhookPayloadStageUpdated Payload for stage.updated — a BOUNDED delta: UpdateStage's known mutable fields (name, semantic, win_probability) each carried only when this update touched them. A position change is instead published as ONE pipeline.updated with a stage_positions delta (never an N-way stage.updated), so position never appears here.
type WebhookPayloadStageUpdated struct {
	// Name The stage's new name (absent when this update did not touch it).
	Name *string `json:"name,omitempty"`

	// PipelineId The pipeline this stage belongs to.
	PipelineId openapi_types.UUID `json:"pipeline_id"`

	// Semantic The stage's new semantic (absent when this update did not touch it).
	Semantic *string `json:"semantic,omitempty"`

	// WinProbability The stage's new win probability (absent when this update did not touch it).
	WinProbability *int `json:"win_probability,omitempty"`
}

// WebhookPersonMergedRelinkCounts How many child rows on each side were repointed from the merged- away person onto the survivor (people/merge.go relinkCounts).
type WebhookPersonMergedRelinkCounts struct {
	// ActivityLinks activity_link rows relinked.
	ActivityLinks int64 `json:"activity_links"`

	// Emails person_email rows relinked.
	Emails int64 `json:"emails"`

	// Phones person_phone rows relinked.
	Phones int64 `json:"phones"`

	// Relationships relationship edge rows relinked.
	Relationships int64 `json:"relationships"`
}

// WebhookPipelineCreatedStage One initial stage as declared on a pipeline.created event — the stage's own stage.created is NOT separately emitted for these (events.md §5.3b: one pipeline.created carries the whole set).
type WebhookPipelineCreatedStage struct {
	// Name The stage's name.
	Name string `json:"name"`

	// Position The stage's position within the pipeline.
	Position int `json:"position"`

	// Semantic The stage's semantic (open | won | lost).
	Semantic string `json:"semantic"`
}

func (WebhookPayloadActivityArchived) EventType() string { return "activity.archived" }

func (WebhookPayloadActivityArchived) EntityType() string { return "activity" }

func (WebhookPayloadActivityCaptured) EventType() string { return "activity.captured" }

func (WebhookPayloadActivityCaptured) EntityType() string { return "activity" }

func (WebhookPayloadActivityUpdated) EventType() string { return "activity.updated" }

func (WebhookPayloadActivityUpdated) EntityType() string { return "activity" }

func (WebhookPayloadConsentChanged) EventType() string { return "consent.changed" }

func (WebhookPayloadConsentChanged) EntityType() string { return "dynamic" }

func (WebhookPayloadDealArchived) EventType() string { return "deal.archived" }

func (WebhookPayloadDealArchived) EntityType() string { return "deal" }

func (WebhookPayloadDealCreated) EventType() string { return "deal.created" }

func (WebhookPayloadDealCreated) EntityType() string { return "deal" }

func (WebhookPayloadDealOwnerChanged) EventType() string { return "deal.owner_changed" }

func (WebhookPayloadDealOwnerChanged) EntityType() string { return "deal" }

func (WebhookPayloadDealRestored) EventType() string { return "deal.restored" }

func (WebhookPayloadDealRestored) EntityType() string { return "deal" }

func (WebhookPayloadDealStageChanged) EventType() string { return "deal.stage_changed" }

func (WebhookPayloadDealStageChanged) EntityType() string { return "deal" }

func (WebhookPayloadDealUpdated) EventType() string { return "deal.updated" }

func (WebhookPayloadDealUpdated) EntityType() string { return "deal" }

func (WebhookPayloadEngagementReply) EventType() string { return "engagement.reply" }

func (WebhookPayloadEngagementReply) EntityType() string { return "activity" }

func (WebhookPayloadLeadCreated) EventType() string { return "lead.created" }

func (WebhookPayloadLeadCreated) EntityType() string { return "lead" }

func (WebhookPayloadLeadDisqualified) EventType() string { return "lead.disqualified" }

func (WebhookPayloadLeadDisqualified) EntityType() string { return "lead" }

func (WebhookPayloadLeadPromoted) EventType() string { return "lead.promoted" }

func (WebhookPayloadLeadPromoted) EntityType() string { return "lead" }

func (WebhookPayloadLeadUpdated) EventType() string { return "lead.updated" }

func (WebhookPayloadLeadUpdated) EntityType() string { return "lead" }

func (WebhookPayloadOfferAccepted) EventType() string { return "offer.accepted" }

func (WebhookPayloadOfferAccepted) EntityType() string { return "offer" }

func (WebhookPayloadOfferCreated) EventType() string { return "offer.created" }

func (WebhookPayloadOfferCreated) EntityType() string { return "offer" }

func (WebhookPayloadOfferRejected) EventType() string { return "offer.rejected" }

func (WebhookPayloadOfferRejected) EntityType() string { return "offer" }

func (WebhookPayloadOfferSent) EventType() string { return "offer.sent" }

func (WebhookPayloadOfferSent) EntityType() string { return "offer" }

func (WebhookPayloadOfferSuperseded) EventType() string { return "offer.superseded" }

func (WebhookPayloadOfferSuperseded) EntityType() string { return "offer" }

func (WebhookPayloadOrganizationArchived) EventType() string { return "organization.archived" }

func (WebhookPayloadOrganizationArchived) EntityType() string { return "organization" }

func (WebhookPayloadOrganizationCreated) EventType() string { return "organization.created" }

func (WebhookPayloadOrganizationCreated) EntityType() string { return "organization" }

func (WebhookPayloadOrganizationMerged) EventType() string { return "organization.merged" }

func (WebhookPayloadOrganizationMerged) EntityType() string { return "organization" }

func (WebhookPayloadOrganizationUpdated) EventType() string { return "organization.updated" }

func (WebhookPayloadOrganizationUpdated) EntityType() string { return "organization" }

func (WebhookPayloadPersonArchived) EventType() string { return "person.archived" }

func (WebhookPayloadPersonArchived) EntityType() string { return "person" }

func (WebhookPayloadPersonCreated) EventType() string { return "person.created" }

func (WebhookPayloadPersonCreated) EntityType() string { return "person" }

func (WebhookPayloadPersonMerged) EventType() string { return "person.merged" }

func (WebhookPayloadPersonMerged) EntityType() string { return "person" }

func (WebhookPayloadPersonRestored) EventType() string { return "person.restored" }

func (WebhookPayloadPersonRestored) EntityType() string { return "person" }

func (WebhookPayloadPersonUpdated) EventType() string { return "person.updated" }

func (WebhookPayloadPersonUpdated) EntityType() string { return "person" }

func (WebhookPayloadPipelineArchived) EventType() string { return "pipeline.archived" }

func (WebhookPayloadPipelineArchived) EntityType() string { return "pipeline" }

func (WebhookPayloadPipelineCreated) EventType() string { return "pipeline.created" }

func (WebhookPayloadPipelineCreated) EntityType() string { return "pipeline" }

func (WebhookPayloadPipelineUpdated) EventType() string { return "pipeline.updated" }

func (WebhookPayloadPipelineUpdated) EntityType() string { return "pipeline" }

func (WebhookPayloadRetentionApplied) EventType() string { return "retention.applied" }

func (WebhookPayloadRetentionApplied) EntityType() string { return "dynamic" }

func (WebhookPayloadSignalDetected) EventType() string { return "signal.detected" }

func (WebhookPayloadSignalDetected) EntityType() string { return "signal" }

func (WebhookPayloadSignalResolved) EventType() string { return "signal.resolved" }

func (WebhookPayloadSignalResolved) EntityType() string { return "signal" }

func (WebhookPayloadStageArchived) EventType() string { return "stage.archived" }

func (WebhookPayloadStageArchived) EntityType() string { return "stage" }

func (WebhookPayloadStageCreated) EventType() string { return "stage.created" }

func (WebhookPayloadStageCreated) EntityType() string { return "stage" }

func (WebhookPayloadStageUpdated) EventType() string { return "stage.updated" }

func (WebhookPayloadStageUpdated) EntityType() string { return "stage" }

// WebhookPayloadVersions maps every subscribable event type carrying a
// WebhookPayload<Event> schema to that schema's x-version extension
// (default 1 when absent). It is the single generated source of truth for
// both the coverage gate (every subscribable event type must be a key here)
// and the version gate (VersionOf(type) must equal this map's value).
var WebhookPayloadVersions = map[string]int{
	"activity.archived":     1,
	"activity.captured":     1,
	"activity.updated":      1,
	"consent.changed":       1,
	"deal.archived":         1,
	"deal.created":          1,
	"deal.owner_changed":    1,
	"deal.restored":         1,
	"deal.stage_changed":    1,
	"deal.updated":          1,
	"engagement.reply":      1,
	"lead.created":          1,
	"lead.disqualified":     1,
	"lead.promoted":         1,
	"lead.updated":          1,
	"offer.accepted":        1,
	"offer.created":         1,
	"offer.rejected":        1,
	"offer.sent":            1,
	"offer.superseded":      1,
	"organization.archived": 1,
	"organization.created":  1,
	"organization.merged":   1,
	"organization.updated":  1,
	"person.archived":       1,
	"person.created":        1,
	"person.merged":         1,
	"person.restored":       1,
	"person.updated":        1,
	"pipeline.archived":     1,
	"pipeline.created":      1,
	"pipeline.updated":      1,
	"retention.applied":     1,
	"signal.detected":       1,
	"signal.resolved":       1,
	"stage.archived":        1,
	"stage.created":         1,
	"stage.updated":         1,
}
