// Code generated by gen-payloads; DO NOT EDIT.

package crmcontracts

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SubscribableEventType.
const (
	DealArchived         SubscribableEventType = "deal.archived"
	DealCreated          SubscribableEventType = "deal.created"
	DealOwnerChanged     SubscribableEventType = "deal.owner_changed"
	DealRestored         SubscribableEventType = "deal.restored"
	DealStageChanged     SubscribableEventType = "deal.stage_changed"
	DealUpdated          SubscribableEventType = "deal.updated"
	LeadCreated          SubscribableEventType = "lead.created"
	LeadDisqualified     SubscribableEventType = "lead.disqualified"
	LeadPromoted         SubscribableEventType = "lead.promoted"
	LeadUpdated          SubscribableEventType = "lead.updated"
	OfferAccepted        SubscribableEventType = "offer.accepted"
	OfferCreated         SubscribableEventType = "offer.created"
	OfferRejected        SubscribableEventType = "offer.rejected"
	OfferSent            SubscribableEventType = "offer.sent"
	OfferSuperseded      SubscribableEventType = "offer.superseded"
	OrganizationArchived SubscribableEventType = "organization.archived"
	OrganizationCreated  SubscribableEventType = "organization.created"
	OrganizationMerged   SubscribableEventType = "organization.merged"
	OrganizationUpdated  SubscribableEventType = "organization.updated"
	PersonArchived       SubscribableEventType = "person.archived"
	PersonCreated        SubscribableEventType = "person.created"
	PersonMerged         SubscribableEventType = "person.merged"
	PersonRestored       SubscribableEventType = "person.restored"
	PersonUpdated        SubscribableEventType = "person.updated"
	PipelineArchived     SubscribableEventType = "pipeline.archived"
	PipelineCreated      SubscribableEventType = "pipeline.created"
	PipelineUpdated      SubscribableEventType = "pipeline.updated"
	StageArchived        SubscribableEventType = "stage.archived"
	StageCreated         SubscribableEventType = "stage.created"
	StageUpdated         SubscribableEventType = "stage.updated"
)

// Valid indicates whether the value is a known member of the SubscribableEventType enum.
func (e SubscribableEventType) Valid() bool {
	switch e {
	case DealArchived:
		return true
	case DealCreated:
		return true
	case DealOwnerChanged:
		return true
	case DealRestored:
		return true
	case DealStageChanged:
		return true
	case DealUpdated:
		return true
	case LeadCreated:
		return true
	case LeadDisqualified:
		return true
	case LeadPromoted:
		return true
	case LeadUpdated:
		return true
	case OfferAccepted:
		return true
	case OfferCreated:
		return true
	case OfferRejected:
		return true
	case OfferSent:
		return true
	case OfferSuperseded:
		return true
	case OrganizationArchived:
		return true
	case OrganizationCreated:
		return true
	case OrganizationMerged:
		return true
	case OrganizationUpdated:
		return true
	case PersonArchived:
		return true
	case PersonCreated:
		return true
	case PersonMerged:
		return true
	case PersonRestored:
		return true
	case PersonUpdated:
		return true
	case PipelineArchived:
		return true
	case PipelineCreated:
		return true
	case PipelineUpdated:
		return true
	case StageArchived:
		return true
	case StageCreated:
		return true
	case StageUpdated:
		return true
	default:
		return false
	}
}

// SubscribableEventType The closed set of domain events a webhook subscription can select. Phase 4 fills this out family by family; today it carries the pilot event plus the deal family (Task 5a-i), the offer family (Task 5a-ii), the pipeline/stage config family (Task 5a-iii), and the person/organization family (Task 5b-personorg), and the lead family (Task 5b-lead).
type SubscribableEventType string

// WebhookActor Who or what caused the event, as exposed publicly.
type WebhookActor struct {
	// Type Actor kind (e.g. human, agent, connector).
	Type string `json:"type"`
}

// WebhookDeliveryEnvelope The public wrapper around every delivered event payload. This is the exact JSON shape a subscriber receives; it carries no internal metadata.
type WebhookDeliveryEnvelope struct {
	// Actor Who or what caused the event, as exposed publicly.
	Actor WebhookActor `json:"actor"`

	// CorrelationId Correlates all events emitted for one originating request.
	CorrelationId openapi_types.UUID `json:"correlation_id"`

	// Data The typed event payload (one of the WebhookPayload* schemas).
	Data map[string]interface{} `json:"data"`

	// Entity The primary entity the event concerns.
	Entity WebhookEntityRef `json:"entity"`

	// EventId Unique id of this event occurrence.
	EventId openapi_types.UUID `json:"event_id"`

	// OccurredAt When the event occurred (RFC 3339).
	OccurredAt time.Time `json:"occurred_at"`

	// Type The event type (a SubscribableEventType value).
	Type string `json:"type"`

	// Version Schema version of the payload in data.
	Version int `json:"version"`
}

// WebhookEntityRef The primary entity the event concerns.
type WebhookEntityRef struct {
	// Id Stable identifier of the entity.
	Id openapi_types.UUID `json:"id"`

	// Type Entity kind (e.g. deal, person, organization).
	Type string `json:"type"`
}

// WebhookPayloadDealArchived Payload for deal.archived — a deal was archived. Carries no data.
type WebhookPayloadDealArchived struct{}

// WebhookPayloadDealCreated Payload for deal.created — a deal was opened.
type WebhookPayloadDealCreated struct {
	// Name The deal's name at creation.
	Name string `json:"name"`
}

// WebhookPayloadDealOwnerChanged Payload for deal.owner_changed — the deal's owner was reassigned. Emitted instead of (never alongside) deal.updated for the owner_id field (events.md §5.3).
type WebhookPayloadDealOwnerChanged struct {
	// FromOwnerId The previous owner (absent when the deal had none).
	FromOwnerId *openapi_types.UUID `json:"from_owner_id,omitempty"`

	// ToOwnerId The new owner.
	ToOwnerId openapi_types.UUID `json:"to_owner_id"`
}

// WebhookPayloadDealRestored Payload for deal.restored. Never emitted today (no restore path exists for deal); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadDealRestored struct{}

// WebhookPayloadDealStageChanged Payload for deal.stage_changed — a deal advanced between stages. Carries the amount/win-probability snapshot frozen at the moment of the move so consumers (the trajectory view, the overnight stalled/forecast sweep, the automation trigger keyed on to_status) never need a read-back.
type WebhookPayloadDealStageChanged struct {
	// AmountMinorAtChange The deal's amount, frozen at the moment of the move.
	AmountMinorAtChange *int64 `json:"amount_minor_at_change,omitempty"`

	// CurrencyAtChange The deal's currency, frozen at the moment of the move.
	CurrencyAtChange *string `json:"currency_at_change,omitempty"`

	// FromStageId Stage the deal left (absent on first placement).
	FromStageId *openapi_types.UUID `json:"from_stage_id,omitempty"`

	// FromStatus Deal status before the move (open | won | lost).
	FromStatus string `json:"from_status"`

	// ToStageId Stage the deal entered.
	ToStageId openapi_types.UUID `json:"to_stage_id"`

	// ToStatus Deal status after the move (open | won | lost) — the field the automation trigger keys on (automation/handlers_event.go).
	ToStatus string `json:"to_status"`

	// WinProbability The target stage's win probability, frozen at the moment of the move.
	WinProbability int `json:"win_probability"`
}

// WebhookPayloadDealUpdated Payload for deal.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, an accepted-offer amount sync, a close-date-correction note, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadDealUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadLeadCreated Payload for lead.created — a lead was created. Two emit sites: a direct create (people/lead.go) that sets no fields, and the capture auto-create engine (capture/sink.go) that names its originating source system; source_system is therefore optional.
type WebhookPayloadLeadCreated struct {
	// SourceSystem The originating source system (capture auto-create only; absent on a direct create).
	SourceSystem *string `json:"source_system,omitempty"`
}

// WebhookPayloadLeadDisqualified Payload for lead.disqualified — a lead was disqualified. Carries no data.
type WebhookPayloadLeadDisqualified struct{}

// WebhookPayloadLeadPromoted Payload for lead.promoted — the lead's genuine-engagement promotion into the context graph (events.md §5.5); its own verb, never a lead.updated, since neither person.created nor person.updated on its own says a lead crossed this line.
type WebhookPayloadLeadPromoted struct {
	// DedupeOutcome Whether promotion created a new person or merged into an existing one: created or merged.
	DedupeOutcome string `json:"dedupe_outcome"`

	// EvidenceRef The inbound activity that evidenced the trigger (absent for a human_qualify with no linked activity).
	EvidenceRef *openapi_types.UUID `json:"evidence_ref,omitempty"`

	// PromotedPersonId The person this lead promoted into (fresh or an existing survivor).
	PromotedPersonId openapi_types.UUID `json:"promoted_person_id"`

	// Trigger The genuine-engagement trigger that authorized promotion: inbound_reply, meeting_booked, meeting_held, or human_qualify.
	Trigger string `json:"trigger"`
}

// WebhookPayloadLeadUpdated Payload for lead.updated — an OPEN envelope: emit sites carry divergent shapes (a flat column patch that includes runtime cf_* custom-field columns, and behavioral-recompute/routing deltas), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadLeadUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadOfferAccepted Payload for offer.accepted — a sent offer was accepted. The deal's headline amount is synced from this offer's gross in the same transaction (see deal.updated on the paired deal entity).
type WebhookPayloadOfferAccepted struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// GrossMinor The offer's gross total, now also the deal's amount.
	GrossMinor *int64 `json:"gross_minor,omitempty"`

	// OfferId The accepted offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`
}

// WebhookPayloadOfferCreated Payload for offer.created — a new Angebot revision was opened (either the first revision, via CreateOffer, or a fresh draft revision minted by RegenerateOffer).
type WebhookPayloadOfferCreated struct {
	// CapturedBy The principal that created this revision.
	CapturedBy string `json:"captured_by"`

	// Currency The offer's currency.
	Currency string `json:"currency"`

	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// OfferId The created offer revision.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number (1 for a first offer).
	Revision int `json:"revision"`

	// Source Where this offer originated (e.g. manual, ai).
	Source string `json:"source"`
}

// WebhookPayloadOfferRejected Payload for offer.rejected — a sent offer was rejected.
type WebhookPayloadOfferRejected struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// OfferId The rejected offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Reason The optional rejection reason (absent when none was given).
	Reason *string `json:"reason,omitempty"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`
}

// WebhookPayloadOfferSent Payload for offer.sent — a draft offer left the workspace. Carries the FX rate frozen at send time (RT-PR-C2) so consumers never need a read-back for the native-currency-to-base conversion.
type WebhookPayloadOfferSent struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// FxRateToBase Native→base rate frozen at send (RT-PR-C2). Decimal-as-string to avoid float rounding.
	FxRateToBase string `json:"fx_rate_to_base"`

	// GrossMinor The offer's gross total at send time.
	GrossMinor *int64 `json:"gross_minor,omitempty"`

	// OfferId The sent offer.
	OfferId openapi_types.UUID `json:"offer_id"`

	// Revision This offer's revision number.
	Revision *int `json:"revision,omitempty"`

	// ValidUntil The offer's validity date (absent when unset).
	ValidUntil *openapi_types.Date `json:"valid_until,omitempty"`
}

// WebhookPayloadOfferSuperseded Payload for offer.superseded — a sent offer was regenerated into a fresh draft revision (B-E03.19) and marked superseded; the new revision arrives as its own offer.created event.
type WebhookPayloadOfferSuperseded struct {
	// DealId The deal this offer belongs to.
	DealId openapi_types.UUID `json:"deal_id"`

	// FromRevision The superseded revision number.
	FromRevision *int `json:"from_revision,omitempty"`

	// OfferId The superseded (prior) offer revision.
	OfferId openapi_types.UUID `json:"offer_id"`

	// ToRevision The new revision number minted by the regenerate.
	ToRevision int `json:"to_revision"`
}

// WebhookPayloadOrganizationArchived Payload for organization.archived — an organization was archived. Carries no data.
type WebhookPayloadOrganizationArchived struct{}

// WebhookPayloadOrganizationCreated Payload for organization.created — a UNION across five emit sites (a direct create, the capture auto-create engine, the anchor company save, the site-read confirmation, and the cold-start profile apply), each of which sets only its own subset; every field is therefore optional.
type WebhookPayloadOrganizationCreated struct {
	// Anchor Whether this is the installation's own anchor organization (company save only).
	Anchor *bool `json:"anchor,omitempty"`

	// CapturedBy The principal that created this organization.
	CapturedBy *string `json:"captured_by,omitempty"`

	// Delta The fields the creating site applied (company save / site-read confirmation only).
	Delta *map[string]interface{} `json:"delta,omitempty"`

	// DisplayName The organization's display name at creation (absent when the site never set one).
	DisplayName *string `json:"display_name,omitempty"`

	// PrimaryDomain The organization's primary domain (cold-start apply only).
	PrimaryDomain *string `json:"primary_domain,omitempty"`

	// SiteReadId The site-read that produced this organization (site-read confirmation only).
	SiteReadId *openapi_types.UUID `json:"site_read_id,omitempty"`

	// Source Where this organization originated (e.g. human, site_read).
	Source *string `json:"source,omitempty"`

	// SourceUrl The source page this organization was read from (site-read confirmation only).
	SourceUrl *string `json:"source_url,omitempty"`
}

// WebhookPayloadOrganizationMerged Payload for organization.merged — two organization records collapsed into one (the §1.3 merge); neither organization.updated nor organization.archived can say this, so it is its own verb.
type WebhookPayloadOrganizationMerged struct {
	// MergedFromId The merged-away (source) organization, retired but still fetchable by id.
	MergedFromId openapi_types.UUID `json:"merged_from_id"`

	// MergedIntoId The survivor (target) organization.
	MergedIntoId openapi_types.UUID `json:"merged_into_id"`
}

// WebhookPayloadOrganizationUpdated Payload for organization.updated — an OPEN envelope: eight emit sites carry divergent shapes (a flat column patch, the anchor company save's field delta, the partner extension's nested delta, enrichment/deep-read applies, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadOrganizationUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadPersonArchived Payload for person.archived — a person was archived. Carries no data.
type WebhookPayloadPersonArchived struct{}

// WebhookPayloadPersonCreated Payload for person.created — a person was created.
type WebhookPayloadPersonCreated struct {
	// FullName The person's name at creation.
	FullName string `json:"full_name"`
}

// WebhookPayloadPersonMerged Payload for person.merged — two person records collapsed into one (the §1.3 merge); neither person.updated nor person.archived can say this, so it is its own verb.
type WebhookPayloadPersonMerged struct {
	// MergedFromId The merged-away (source) person, retired but still fetchable by id.
	MergedFromId openapi_types.UUID `json:"merged_from_id"`

	// MergedIntoId The survivor (target) person.
	MergedIntoId openapi_types.UUID `json:"merged_into_id"`

	// Relinked How many child rows on each side were repointed from the merged- away person onto the survivor (people/merge.go relinkCounts).
	Relinked WebhookPersonMergedRelinkCounts `json:"relinked"`
}

// WebhookPayloadPersonRestored Payload for person.restored. Never emitted today (no restore path exists for person); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadPersonRestored struct{}

// WebhookPayloadPersonUpdated Payload for person.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, a lead-promotion conversion note, a signature-enrichment fill, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadPersonUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadPipelineArchived Payload for pipeline.archived. Never emitted today (no archive path exists for pipeline); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadPipelineArchived struct{}

// WebhookPayloadPipelineCreated Payload for pipeline.created — a pipeline was created with its initial stage set in the same transaction.
type WebhookPayloadPipelineCreated struct {
	// IsDefault Whether this pipeline is the workspace default.
	IsDefault bool `json:"is_default"`

	// Name The pipeline's name.
	Name string `json:"name"`

	// Stages The pipeline's initial stages, in the order created.
	Stages []WebhookPipelineCreatedStage `json:"stages"`
}

// WebhookPayloadPipelineUpdated Payload for pipeline.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat name/is_default/position patch from UpdatePipeline, or a stage_positions reorder map from UpdateStage when a stage's position changes), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadPipelineUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched (name, is_default, position, or stage_positions).
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

// WebhookPayloadStageArchived Payload for stage.archived. Never emitted today (no archive path exists for stage); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadStageArchived struct{}

// WebhookPayloadStageCreated Payload for stage.created — a stage was added to a pipeline.
type WebhookPayloadStageCreated struct {
	// Name The stage's name.
	Name string `json:"name"`

	// PipelineId The pipeline this stage belongs to.
	PipelineId openapi_types.UUID `json:"pipeline_id"`

	// Position The stage's position within the pipeline.
	Position int `json:"position"`

	// Semantic The stage's semantic (open | won | lost).
	Semantic string `json:"semantic"`

	// WinProbability The stage's win probability (won=100, lost=0, open=0..100).
	WinProbability int `json:"win_probability"`
}

// WebhookPayloadStageUpdated Payload for stage.updated — a BOUNDED delta: UpdateStage's known mutable fields (name, semantic, win_probability) each carried only when this update touched them. A position change is instead published as ONE pipeline.updated with a stage_positions delta (never an N-way stage.updated), so position never appears here.
type WebhookPayloadStageUpdated struct {
	// Name The stage's new name (absent when this update did not touch it).
	Name *string `json:"name,omitempty"`

	// PipelineId The pipeline this stage belongs to.
	PipelineId openapi_types.UUID `json:"pipeline_id"`

	// Semantic The stage's new semantic (absent when this update did not touch it).
	Semantic *string `json:"semantic,omitempty"`

	// WinProbability The stage's new win probability (absent when this update did not touch it).
	WinProbability *int `json:"win_probability,omitempty"`
}

// WebhookPersonMergedRelinkCounts How many child rows on each side were repointed from the merged- away person onto the survivor (people/merge.go relinkCounts).
type WebhookPersonMergedRelinkCounts struct {
	// ActivityLinks activity_link rows relinked.
	ActivityLinks int64 `json:"activity_links"`

	// Emails person_email rows relinked.
	Emails int64 `json:"emails"`

	// Phones person_phone rows relinked.
	Phones int64 `json:"phones"`

	// Relationships relationship edge rows relinked.
	Relationships int64 `json:"relationships"`
}

// WebhookPipelineCreatedStage One initial stage as declared on a pipeline.created event — the stage's own stage.created is NOT separately emitted for these (events.md §5.3b: one pipeline.created carries the whole set).
type WebhookPipelineCreatedStage struct {
	// Name The stage's name.
	Name string `json:"name"`

	// Position The stage's position within the pipeline.
	Position int `json:"position"`

	// Semantic The stage's semantic (open | won | lost).
	Semantic string `json:"semantic"`
}

func (WebhookPayloadDealArchived) EventType() string { return "deal.archived" }

func (WebhookPayloadDealArchived) EntityType() string { return "deal" }

func (WebhookPayloadDealCreated) EventType() string { return "deal.created" }

func (WebhookPayloadDealCreated) EntityType() string { return "deal" }

func (WebhookPayloadDealOwnerChanged) EventType() string { return "deal.owner_changed" }

func (WebhookPayloadDealOwnerChanged) EntityType() string { return "deal" }

func (WebhookPayloadDealRestored) EventType() string { return "deal.restored" }

func (WebhookPayloadDealRestored) EntityType() string { return "deal" }

func (WebhookPayloadDealStageChanged) EventType() string { return "deal.stage_changed" }

func (WebhookPayloadDealStageChanged) EntityType() string { return "deal" }

func (WebhookPayloadDealUpdated) EventType() string { return "deal.updated" }

func (WebhookPayloadDealUpdated) EntityType() string { return "deal" }

func (WebhookPayloadLeadCreated) EventType() string { return "lead.created" }

func (WebhookPayloadLeadCreated) EntityType() string { return "lead" }

func (WebhookPayloadLeadDisqualified) EventType() string { return "lead.disqualified" }

func (WebhookPayloadLeadDisqualified) EntityType() string { return "lead" }

func (WebhookPayloadLeadPromoted) EventType() string { return "lead.promoted" }

func (WebhookPayloadLeadPromoted) EntityType() string { return "lead" }

func (WebhookPayloadLeadUpdated) EventType() string { return "lead.updated" }

func (WebhookPayloadLeadUpdated) EntityType() string { return "lead" }

func (WebhookPayloadOfferAccepted) EventType() string { return "offer.accepted" }

func (WebhookPayloadOfferAccepted) EntityType() string { return "offer" }

func (WebhookPayloadOfferCreated) EventType() string { return "offer.created" }

func (WebhookPayloadOfferCreated) EntityType() string { return "offer" }

func (WebhookPayloadOfferRejected) EventType() string { return "offer.rejected" }

func (WebhookPayloadOfferRejected) EntityType() string { return "offer" }

func (WebhookPayloadOfferSent) EventType() string { return "offer.sent" }

func (WebhookPayloadOfferSent) EntityType() string { return "offer" }

func (WebhookPayloadOfferSuperseded) EventType() string { return "offer.superseded" }

func (WebhookPayloadOfferSuperseded) EntityType() string { return "offer" }

func (WebhookPayloadOrganizationArchived) EventType() string { return "organization.archived" }

func (WebhookPayloadOrganizationArchived) EntityType() string { return "organization" }

func (WebhookPayloadOrganizationCreated) EventType() string { return "organization.created" }

func (WebhookPayloadOrganizationCreated) EntityType() string { return "organization" }

func (WebhookPayloadOrganizationMerged) EventType() string { return "organization.merged" }

func (WebhookPayloadOrganizationMerged) EntityType() string { return "organization" }

func (WebhookPayloadOrganizationUpdated) EventType() string { return "organization.updated" }

func (WebhookPayloadOrganizationUpdated) EntityType() string { return "organization" }

func (WebhookPayloadPersonArchived) EventType() string { return "person.archived" }

func (WebhookPayloadPersonArchived) EntityType() string { return "person" }

func (WebhookPayloadPersonCreated) EventType() string { return "person.created" }

func (WebhookPayloadPersonCreated) EntityType() string { return "person" }

func (WebhookPayloadPersonMerged) EventType() string { return "person.merged" }

func (WebhookPayloadPersonMerged) EntityType() string { return "person" }

func (WebhookPayloadPersonRestored) EventType() string { return "person.restored" }

func (WebhookPayloadPersonRestored) EntityType() string { return "person" }

func (WebhookPayloadPersonUpdated) EventType() string { return "person.updated" }

func (WebhookPayloadPersonUpdated) EntityType() string { return "person" }

func (WebhookPayloadPipelineArchived) EventType() string { return "pipeline.archived" }

func (WebhookPayloadPipelineArchived) EntityType() string { return "pipeline" }

func (WebhookPayloadPipelineCreated) EventType() string { return "pipeline.created" }

func (WebhookPayloadPipelineCreated) EntityType() string { return "pipeline" }

func (WebhookPayloadPipelineUpdated) EventType() string { return "pipeline.updated" }

func (WebhookPayloadPipelineUpdated) EntityType() string { return "pipeline" }

func (WebhookPayloadStageArchived) EventType() string { return "stage.archived" }

func (WebhookPayloadStageArchived) EntityType() string { return "stage" }

func (WebhookPayloadStageCreated) EventType() string { return "stage.created" }

func (WebhookPayloadStageCreated) EntityType() string { return "stage" }

func (WebhookPayloadStageUpdated) EventType() string { return "stage.updated" }

func (WebhookPayloadStageUpdated) EntityType() string { return "stage" }

// WebhookPayloadVersions maps every subscribable event type carrying a
// WebhookPayload<Event> schema to that schema's x-version extension
// (default 1 when absent). It is the single generated source of truth for
// both the coverage gate (every subscribable event type must be a key here)
// and the version gate (VersionOf(type) must equal this map's value).
var WebhookPayloadVersions = map[string]int{
	"deal.archived":         1,
	"deal.created":          1,
	"deal.owner_changed":    1,
	"deal.restored":         1,
	"deal.stage_changed":    1,
	"deal.updated":          1,
	"lead.created":          1,
	"lead.disqualified":     1,
	"lead.promoted":         1,
	"lead.updated":          1,
	"offer.accepted":        1,
	"offer.created":         1,
	"offer.rejected":        1,
	"offer.sent":            1,
	"offer.superseded":      1,
	"organization.archived": 1,
	"organization.created":  1,
	"organization.merged":   1,
	"organization.updated":  1,
	"person.archived":       1,
	"person.created":        1,
	"person.merged":         1,
	"person.restored":       1,
	"person.updated":        1,
	"pipeline.archived":     1,
	"pipeline.created":      1,
	"pipeline.updated":      1,
	"stage.archived":        1,
	"stage.created":         1,
	"stage.updated":         1,
}
