// Code generated by gen-payloads; DO NOT EDIT.

package crmcontracts

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SubscribableEventType.
const (
	DealArchived     SubscribableEventType = "deal.archived"
	DealCreated      SubscribableEventType = "deal.created"
	DealOwnerChanged SubscribableEventType = "deal.owner_changed"
	DealRestored     SubscribableEventType = "deal.restored"
	DealStageChanged SubscribableEventType = "deal.stage_changed"
	DealUpdated      SubscribableEventType = "deal.updated"
)

// Valid indicates whether the value is a known member of the SubscribableEventType enum.
func (e SubscribableEventType) Valid() bool {
	switch e {
	case DealArchived:
		return true
	case DealCreated:
		return true
	case DealOwnerChanged:
		return true
	case DealRestored:
		return true
	case DealStageChanged:
		return true
	case DealUpdated:
		return true
	default:
		return false
	}
}

// SubscribableEventType The closed set of domain events a webhook subscription can select. Phase 4 fills this out family by family; today it carries the pilot event plus the deal family (Task 5a-i).
type SubscribableEventType string

// WebhookActor Who or what caused the event, as exposed publicly.
type WebhookActor struct {
	// Type Actor kind (e.g. human, agent, connector).
	Type string `json:"type"`
}

// WebhookDeliveryEnvelope The public wrapper around every delivered event payload. This is the exact JSON shape a subscriber receives; it carries no internal metadata.
type WebhookDeliveryEnvelope struct {
	// Actor Who or what caused the event, as exposed publicly.
	Actor WebhookActor `json:"actor"`

	// CorrelationId Correlates all events emitted for one originating request.
	CorrelationId openapi_types.UUID `json:"correlation_id"`

	// Data The typed event payload (one of the WebhookPayload* schemas).
	Data map[string]interface{} `json:"data"`

	// Entity The primary entity the event concerns.
	Entity WebhookEntityRef `json:"entity"`

	// EventId Unique id of this event occurrence.
	EventId openapi_types.UUID `json:"event_id"`

	// OccurredAt When the event occurred (RFC 3339).
	OccurredAt time.Time `json:"occurred_at"`

	// Type The event type (a SubscribableEventType value).
	Type string `json:"type"`

	// Version Schema version of the payload in data.
	Version int `json:"version"`
}

// WebhookEntityRef The primary entity the event concerns.
type WebhookEntityRef struct {
	// Id Stable identifier of the entity.
	Id openapi_types.UUID `json:"id"`

	// Type Entity kind (e.g. deal, person, organization).
	Type string `json:"type"`
}

// WebhookPayloadDealArchived Payload for deal.archived — a deal was archived. Carries no data.
type WebhookPayloadDealArchived struct{}

// WebhookPayloadDealCreated Payload for deal.created — a deal was opened.
type WebhookPayloadDealCreated struct {
	// Name The deal's name at creation.
	Name string `json:"name"`
}

// WebhookPayloadDealOwnerChanged Payload for deal.owner_changed — the deal's owner was reassigned. Emitted instead of (never alongside) deal.updated for the owner_id field (events.md §5.3).
type WebhookPayloadDealOwnerChanged struct {
	// FromOwnerId The previous owner (absent when the deal had none).
	FromOwnerId *openapi_types.UUID `json:"from_owner_id,omitempty"`

	// ToOwnerId The new owner.
	ToOwnerId openapi_types.UUID `json:"to_owner_id"`
}

// WebhookPayloadDealRestored Payload for deal.restored. Never emitted today (no restore path exists for deal); the schema is published so the type is a valid subscription target and the coverage gate can name it explicitly rather than silently omitting it.
type WebhookPayloadDealRestored struct{}

// WebhookPayloadDealStageChanged Payload for deal.stage_changed — a deal advanced between stages. Carries the amount/win-probability snapshot frozen at the moment of the move so consumers (the trajectory view, the overnight stalled/forecast sweep, the automation trigger keyed on to_status) never need a read-back.
type WebhookPayloadDealStageChanged struct {
	// AmountMinorAtChange The deal's amount, frozen at the moment of the move.
	AmountMinorAtChange *int64 `json:"amount_minor_at_change,omitempty"`

	// CurrencyAtChange The deal's currency, frozen at the moment of the move.
	CurrencyAtChange *string `json:"currency_at_change,omitempty"`

	// FromStageId Stage the deal left (absent on first placement).
	FromStageId *openapi_types.UUID `json:"from_stage_id,omitempty"`

	// FromStatus Deal status before the move (open | won | lost).
	FromStatus string `json:"from_status"`

	// ToStageId Stage the deal entered.
	ToStageId openapi_types.UUID `json:"to_stage_id"`

	// ToStatus Deal status after the move (open | won | lost) — the field the automation trigger keys on (automation/handlers_event.go).
	ToStatus string `json:"to_status"`

	// WinProbability The target stage's win probability, frozen at the moment of the move.
	WinProbability int `json:"win_probability"`
}

// WebhookPayloadDealUpdated Payload for deal.updated — an OPEN envelope: its emit sites carry divergent shapes (a flat column patch, an accepted-offer amount sync, a close-date-correction note, a relationship delta), so the honest shape is a change-set map rather than a fixed field list.
type WebhookPayloadDealUpdated struct {
	// ChangedFields Field name → new value for whatever this update touched, incl. runtime cf_* custom fields.
	ChangedFields map[string]interface{} `json:"changed_fields"`
}

func (WebhookPayloadDealArchived) EventType() string { return "deal.archived" }

func (WebhookPayloadDealArchived) EntityType() string { return "deal" }

func (WebhookPayloadDealCreated) EventType() string { return "deal.created" }

func (WebhookPayloadDealCreated) EntityType() string { return "deal" }

func (WebhookPayloadDealOwnerChanged) EventType() string { return "deal.owner_changed" }

func (WebhookPayloadDealOwnerChanged) EntityType() string { return "deal" }

func (WebhookPayloadDealRestored) EventType() string { return "deal.restored" }

func (WebhookPayloadDealRestored) EntityType() string { return "deal" }

func (WebhookPayloadDealStageChanged) EventType() string { return "deal.stage_changed" }

func (WebhookPayloadDealStageChanged) EntityType() string { return "deal" }

func (WebhookPayloadDealUpdated) EventType() string { return "deal.updated" }

func (WebhookPayloadDealUpdated) EntityType() string { return "deal" }

// WebhookPayloadVersions maps every subscribable event type carrying a
// WebhookPayload<Event> schema to that schema's x-version extension
// (default 1 when absent). It is the single generated source of truth for
// both the coverage gate (every subscribable event type must be a key here)
// and the version gate (VersionOf(type) must equal this map's value).
var WebhookPayloadVersions = map[string]int{
	"deal.archived":      1,
	"deal.created":       1,
	"deal.owner_changed": 1,
	"deal.restored":      1,
	"deal.stage_changed": 1,
	"deal.updated":       1,
}
