// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package zalopersonal

// The Go port of Zalo's crypto is checked against vectors generated by RUNNING
// zca-js's own functions (its src/utils.ts, driven by crypto-js) over fixed
// inputs. This is the only part of the protocol that can be verified without a
// live Zalo account, and it is also the part where a silent mismatch would look
// like an unexplained server-side rejection rather than a bug — a wrong
// signature or a wrong key returns an opaque error code, never "your AES is
// wrong".

import (
	"crypto/aes"
	"testing"
)

const (
	vectorAPIType         = 30
	vectorIMEI            = "6f4a9a4c-1a2b-4c3d-8e9f-000000000001-7b1a0e4d0f1c2b3a4d5e6f7a8b9c0d1e"
	vectorFirstLaunchTime = 1755300000000
	vectorZcidExt         = "a1b2c3d4e5f6"

	vectorZcid = "23DB26D57EB064F3422E5FE7AF697DFFC7D98E90E8CD8F4E51291AB0A2EAC52975969D89DFB3E79AF6DAC779BF5514A5" +
		"62242F103E1FD8D8D4F297547662B0C753D5B818BDC8EE4CAF5147D5AE6D2D54289A7DE0498DFDB2CD5380CE09D5D271"
	vectorEncryptKey = "054B989E2D2D7B6F425E1259E03D2DD9"

	vectorLoginParamsJSON = `{"computer_name":"Web","imei":"6f4a9a4c-1a2b-4c3d-8e9f-000000000001-7b1a0e4d0f1c2b3a4d5e6f7a8b9c0d1e","language":"vi","ts":1755300000000}`
	vectorLoginParams     = "3EHsMU9D7G81gX8vUfsKm1zdMLQUEs+YdsN4yjCF7ZvYYzMPXKnYn8hJ4OM80pSVh4VqTODvrrT5AdObd7fX1EVTc9nDmlaU/" +
		"rSO1QkY4oVHBqODUYfVVjkoZ3/YdeIGqonyMX4ngyuGQFdMToohxtRYD1jHTTovaPfoJ2VxhOWftD9lLawHlb57/gIp4XJK"

	vectorSignKey = "2f46dc4a084eac5ee45d40bafff04b23"

	vectorSessionKey        = "c2VjcmV0LWtleS0xMjM0NQ=="
	vectorSessionPlaintext  = `{"message":"xin chào","toid":"123456789","ttl":0}`
	vectorSessionCiphertext = "eleA6XBGEOLwWlthvzWtgJbNjEP93iMJwKE5clRTE/t0W2WRQDAjRmawQpSm7urzVlxo/Oppxe/3tyBOs37Wzw=="
)

func TestZcidMatchesTheReferenceImplementation(t *testing.T) {
	got, err := encodeAESHex(zcidKey, "30,"+vectorIMEI+",1755300000000")
	if err != nil {
		t.Fatalf("encode zcid: %v", err)
	}
	if got != vectorZcid {
		t.Errorf("zcid mismatch\n got %s\nwant %s", got, vectorZcid)
	}
}

func TestEncryptKeyDerivationMatchesTheReferenceImplementation(t *testing.T) {
	p := &paramsEncryptor{zcid: vectorZcid, zcidExt: vectorZcidExt, encVer: "v2"}
	if err := p.deriveEncryptKey(); err != nil {
		t.Fatalf("derive encrypt key: %v", err)
	}
	if p.encryptKey != vectorEncryptKey {
		t.Errorf("encrypt key mismatch\n got %s\nwant %s", p.encryptKey, vectorEncryptKey)
	}
}

func TestLoginParamsEncryptionMatchesTheReferenceImplementation(t *testing.T) {
	got, err := encodeAESBase64(vectorEncryptKey, vectorLoginParamsJSON)
	if err != nil {
		t.Fatalf("encrypt login params: %v", err)
	}
	if got != vectorLoginParams {
		t.Errorf("login params mismatch\n got %s\nwant %s", got, vectorLoginParams)
	}
}

func TestLoginResponseDecryptsWhatTheReferenceImplementationEncrypted(t *testing.T) {
	plain, err := decryptLoginResp(vectorEncryptKey, vectorLoginParams)
	if err != nil {
		t.Fatalf("decrypt login response: %v", err)
	}
	if string(plain) != vectorLoginParamsJSON {
		t.Errorf("round trip mismatch\n got %s\nwant %s", plain, vectorLoginParamsJSON)
	}
}

func TestSignKeyMatchesTheReferenceImplementation(t *testing.T) {
	params := map[string]string{
		"zcid":           vectorZcid,
		"zcid_ext":       vectorZcidExt,
		"enc_ver":        "v2",
		"params":         vectorLoginParams,
		"type":           "30",
		"client_version": "671",
	}
	if got := getSignKey("getlogininfo", params); got != vectorSignKey {
		t.Errorf("signkey mismatch\n got %s\nwant %s", got, vectorSignKey)
	}
}

func TestSessionEncryptionMatchesTheReferenceImplementation(t *testing.T) {
	got, err := encodeAES(vectorSessionKey, vectorSessionPlaintext)
	if err != nil {
		t.Fatalf("encrypt session payload: %v", err)
	}
	if got != vectorSessionCiphertext {
		t.Errorf("ciphertext mismatch\n got %s\nwant %s", got, vectorSessionCiphertext)
	}

	// Non-ASCII survives the round trip: Vietnamese message bodies are the
	// normal case here, not an edge case.
	plain, err := decodeAES(vectorSessionKey, vectorSessionCiphertext)
	if err != nil {
		t.Fatalf("decrypt session payload: %v", err)
	}
	if string(plain) != vectorSessionPlaintext {
		t.Errorf("plaintext mismatch\n got %s\nwant %s", plain, vectorSessionPlaintext)
	}
}

func TestParamsEncryptorProducesAUsableKeyFromFreshRandomness(t *testing.T) {
	// The derivation reads 8 + 12 + 12 characters out of two values it just
	// minted; a short random extension would silently produce a short key.
	for i := 0; i < 50; i++ {
		p, err := newParamsEncryptor(vectorAPIType, vectorIMEI, vectorFirstLaunchTime)
		if err != nil {
			t.Fatalf("new params encryptor: %v", err)
		}
		if len(p.encryptKey) != 32 {
			t.Fatalf("encrypt key is %d chars, want 32 (from zcid_ext %q)", len(p.encryptKey), p.zcidExt)
		}
		if _, err := encodeAESBase64(p.encryptKey, `{"probe":1}`); err != nil {
			t.Fatalf("key from zcid_ext %q is not a usable AES key: %v", p.zcidExt, err)
		}
	}
}

// TestTheSessionSchemeDecodesItsKeyBeforeUsingIt pins this file's one real
// hazard. Both schemes take a string, and both strings are plausible AES key
// lengths, so feeding the session key to the login scheme does not fail — it
// silently encrypts under 24 ASCII bytes instead of the 16 the base64 decodes
// to, and the server answers an opaque rejection that names nothing.
func TestTheSessionSchemeDecodesItsKeyBeforeUsingIt(t *testing.T) {
	got, err := encodeAES(vectorSessionKey, vectorSessionPlaintext)
	if err != nil {
		t.Fatalf("session encrypt: %v", err)
	}

	const decodedKey = "secret-key-12345" // what vectorSessionKey base64-decodes to
	want, err := encodeAESBase64(decodedKey, vectorSessionPlaintext)
	if err != nil {
		t.Fatalf("login-scheme encrypt under the decoded key: %v", err)
	}
	if got != want {
		t.Error("the session scheme did not use the base64-DECODED key bytes")
	}

	raw, err := encodeAESBase64(vectorSessionKey, vectorSessionPlaintext)
	if err != nil {
		t.Fatalf("login-scheme encrypt under the raw key: %v", err)
	}
	if raw == got {
		t.Error("using the session key raw produced the same ciphertext as decoding it, so this test proves nothing")
	}
}

func TestMalformedCiphertextIsReportedRatherThanReturnedAsGarbage(t *testing.T) {
	// A truncated body is what a proxy or a challenge page produces, and it
	// must not decode to plausible-looking bytes.
	if _, err := decodeAES(vectorSessionKey, "AAAA"); err == nil {
		t.Error("a ciphertext that is not a whole number of blocks decrypted successfully")
	}
	if _, err := decodeAES(vectorSessionKey, "not base64 at all!!"); err == nil {
		t.Error("a non-base64 payload decrypted successfully")
	}
	if _, err := decryptLoginResp(vectorEncryptKey, "not base64 at all!!"); err == nil {
		t.Error("a non-base64 login response decrypted successfully")
	}
}

func TestPaddingThatCouldNotHaveBeenWrittenIsRejected(t *testing.T) {
	// PKCS#7 unpadding is where a wrong key first shows up: the plaintext is
	// noise and the last byte is a length that cannot be right.
	if _, err := pkcs7Unpad([]byte{}); err == nil {
		t.Error("empty input was unpadded")
	}
	block := make([]byte, 16)
	block[15] = 0
	if _, err := pkcs7Unpad(block); err == nil {
		t.Error("a zero padding byte was accepted")
	}
	block[15] = 99
	if _, err := pkcs7Unpad(block); err == nil {
		t.Error("a padding byte larger than the block was accepted")
	}
}

// TestPaddingIsAlwaysAWholeBlockAndNamesItsOwnLength pins the invariant the pad
// guard asserts: for ANY input length the pad is 1..blockSize bytes, every one
// of them equal to that count, and the result is a whole number of blocks. It
// is what makes the pad length expressible as a single byte at all — the
// property PKCS#7 is built on, and the one a different block size would break.
func TestPaddingIsAlwaysAWholeBlockAndNamesItsOwnLength(t *testing.T) {
	for size := 0; size <= 3*aes.BlockSize; size++ {
		padded, err := pkcs7Pad(make([]byte, size))
		if err != nil {
			t.Fatalf("pad %d bytes: %v", size, err)
		}
		if len(padded)%aes.BlockSize != 0 {
			t.Fatalf("padding %d bytes gave %d, which is not a whole number of blocks", size, len(padded))
		}

		n := len(padded) - size
		if n < 1 || n > aes.BlockSize {
			t.Fatalf("padding %d bytes added %d bytes, outside 1..%d", size, n, aes.BlockSize)
		}
		for i := size; i < len(padded); i++ {
			if int(padded[i]) != n {
				t.Fatalf("padding %d bytes: byte %d is %d, want the pad length %d", size, i, padded[i], n)
			}
		}

		unpadded, err := pkcs7Unpad(padded)
		if err != nil {
			t.Fatalf("unpad what pkcs7Pad produced for %d bytes: %v", size, err)
		}
		if len(unpadded) != size {
			t.Fatalf("round trip of %d bytes came back %d bytes", size, len(unpadded))
		}
	}
}
