// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

// Turning the inbox on.
//
// Every other record type this tool writes goes through the product's API.
// Captured mail cannot: there is no create endpoint for it, because a message
// arrives through the capture pipeline or it does not exist. So the demo had
// companies, deals, contracts and invoices behind an empty inbox — and with it
// an empty reply join, an empty thread view, and "who on our team knows this
// contact" answering nobody.
//
// What this phase writes is ONE ROW PER SEAT: a capture_connection naming the
// offline_demo provider. The messages themselves are generated by that
// connector inside the worker and land through the real sink, so the threads,
// participants and audit trail are the product's own rather than this tool's.
//
// SQL rather than the API, for the same reason the teams and seats are:
// POST /connectors/{provider}/connect takes a provider from a closed enum that
// does not include this one, deliberately — a demo generator is not something
// an operator should be able to connect from the UI.

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// seedCommsConnections gives every seat a mailbox the offline demo connector
// will fill.
//
// `scopes` carries what the connector declared — `read`, its Descriptor's
// only scope. An empty array looks harmless and is not: the connector
// principal is built from these, so the activity write is refused with no
// scope to create one, and the messages land in raw_capture while the inbox
// stays empty. That failure is silent, which is what made it expensive.
//
// The seat's own id is written into `auth`, which is the opaque credential
// bundle the registry hands the connector. There is no vault ref because there
// is no secret: the generator reads the local database and talks to nobody, so
// a sealed credential would protect an empty room. imap carries its mailbox
// owner the same way.
func seedCommsConnections(dsn string, cfg demoConfig, mode runMode) (int, error) {
	if mode == modeDryRun || dsn == "" {
		return 0, nil
	}
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, dsn)
	if err != nil {
		return 0, fmt.Errorf("connecting to provision the mailboxes: %w", err)
	}
	defer func() { _ = conn.Close(ctx) }() //craft:ignore swallowed-errors closing a seed connection has no failure the caller can act on

	// The workspace is read once and passed explicitly. capture_connection
	// still carries workspace_id NOT NULL, and the seeder's own connection
	// sets no app.workspace_id GUC — the product's inserts get theirs from a
	// request context this tool does not have.
	var workspace string
	if err := conn.QueryRow(ctx, `SELECT id::text FROM workspace LIMIT 1`).Scan(&workspace); err != nil {
		return 0, fmt.Errorf("resolving the workspace for the mailboxes: %w", err)
	}

	created := 0
	for _, user := range cfg.Users {
		var userID string
		err := conn.QueryRow(ctx,
			`SELECT id::text FROM app_user WHERE lower(email) = lower($1)`, user.Email).Scan(&userID)
		if err == pgx.ErrNoRows {
			continue // a seat the run has not created yet
		}
		if err != nil {
			return created, fmt.Errorf("looking up the seat %s: %w", user.Email, err)
		}

		// workspace_id is set from the GUC the way every tenant write is; the
		// seeder's other SQL phases do the same.
		tag, err := conn.Exec(ctx, `
			INSERT INTO capture_connection
			       (workspace_id, provider, user_id, scopes, status, account_label, auth)
			VALUES ($1::uuid, 'offline_demo', $2::uuid, '{read}', 'connected', $3, $4::bytea)
			ON CONFLICT (user_id, provider) DO NOTHING`,
			workspace, userID, user.Email, []byte(userID))
		if err != nil {
			return created, fmt.Errorf("provisioning the mailbox for %s: %w", user.Email, err)
		}
		created += int(tag.RowsAffected())
	}
	if created > 0 {
		fmt.Printf("mailboxes:     %d connected — threads arrive with the next capture sweep\n", created)
	}
	return created, nil
}
