// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package mailmap

// What a captured message is allowed to become. Two rules, deliberately
// separate because they pull opposite ways on the same headers:
//
//   - SkipReason decides what never reaches the timeline at all. It is NARROW:
//     ADR-0072 §1 keeps a transactional sender's message and suppresses only the
//     person/company derivation, so the tier gate has to see the mail it judges.
//   - isMachineTouched decides what may vouch for an address. It is WIDE, and
//     only ever withholds evidence: an autoresponder's reply is genuinely
//     owner-authored and genuinely in Sent, so nothing downstream could tell it
//     from correspondence the owner chose.
//
// One answer cannot serve both, and the headers they read are the same ones.

import (
	"strings"

	"github.com/emersion/go-message/mail"
)

// SkipReason names why a message is intentionally dropped, or reports that
// it should be captured. The rule set keeps automated/system noise off the
// timeline: no stable id, no sender, an auto-reply, or the delivery system
// itself.
func (m Message) SkipReason() (string, bool) {
	if m.messageID == "" {
		return "no Message-ID", true
	}
	if m.from == "" {
		return "no From address", true
	}
	if m.autoReply {
		return autoReplied, true
	}
	if isDeliverySystemSender(m.from) {
		return "delivery-system sender", true
	}
	return "", false
}

// isDeliverySystemSender flags mail from the message-transport system itself —
// a bounce, a DSN, a postmaster notice. There is no correspondent behind it and
// nothing on the other end to have a relationship with, so it is dropped before
// anything is written.
//
// Deliberately NARROWER than "looks automated". A no-reply or notifications
// address is a real organization writing to the workspace — a signed envelope,
// an invoice, a shipping notice — and ADR-0072 §1 is explicit that such a
// message keeps its place on the timeline while the tier gate suppresses the
// person and company derivation. Dropping it here would make that promise false
// and would starve the T2 corroboration rule (CAP-PARAM-6), which exists to
// recognize exactly these machine localparts, of the mail it judges.
func isDeliverySystemSender(addr string) bool {
	local, _, found := strings.Cut(strings.ToLower(addr), "@")
	if !found {
		return false
	}
	// BATV/prvs tags sit before any separator a normalization would strip. The
	// scheme signs the RETURN PATH, which this never sees — matching From means
	// a relay that rewrites From with a tag has its mail dropped. Rare, and it
	// costs a timeline row rather than granting anything.
	if strings.HasPrefix(local, "prvs=") || strings.HasPrefix(local, "msprvs1=") {
		return true
	}
	// VERP encodes the original recipient into the bounce address
	// (`bounces-12345@`, `bounce+tag@`), so the trailing tag is dropped before
	// matching. `_` is stripped for parity with the T2 registry's own reading
	// of these localparts (CAP-PARAM-6) — one spelling, two rules.
	local, _, _ = strings.Cut(local, "+")
	local = strings.NewReplacer(".", "", "-", "", "_", "").Replace(local)
	local = strings.TrimRight(local, "0123456789")
	switch local {
	case "mailerdaemon", "postmaster", "bounce", "bounces":
		return true
	}
	return false
}

// The two RFC 3834 values that mean a person's mail reaches the tier gate:
// `no` is not automatic at all, and `auto-generated` is mail a system
// originated on its own — an invoice, a notice, a signed envelope — as opposed
// to mail it generated in reply to something we sent.
const (
	notAutomatic  = "no"
	autoGenerated = "auto-generated"
	// autoReplied is the legacy Precedence spelling and the reason SkipReason
	// gives. RFC 3834's own keyword is `auto-replied`, which the switches carry
	// separately.
	autoReplied = "auto-reply"
)

// headerKeyword is the ONE reading of a structured header value: RFC 3834 §5
// allows parameters after a semicolon (`auto-replied; owner-email=…`) and RFC
// 5322 allows comments around the value (`auto-generated (invoice)`), so the
// keyword is what precedes the first semicolon once comments are gone. Both
// rules read it the same way — two readings would let a value mean one thing to
// the drop and another to the veto.
func headerKeyword(value string) (keyword string, readable bool) {
	stripped, wellFormed := stripHeaderComments(value)
	if !wellFormed {
		return "", false
	}
	k, _, _ := strings.Cut(stripped, ";")
	return strings.TrimSpace(k), true
}

// reachesGate reports whether an Auto-Submitted value names mail the tier gate
// should judge: not automatic at all, or a system's own notice.
func reachesGate(autoSubmitted string) bool {
	keyword, readable := headerKeyword(autoSubmitted)
	if !readable {
		// Unreadable is not permission. A value whose comment was never closed
		// could have said anything before it was swallowed.
		return false
	}
	return strings.EqualFold(keyword, notAutomatic) || strings.EqualFold(keyword, autoGenerated)
}

// isAutoReplyPrecedence reports whether a legacy Precedence value names a reply.
// Shared by both rules so a new spelling cannot be added to one and forgotten in
// the other — forgetting the wide one is the failure this split exists to stop.
func isAutoReplyPrecedence(value string) bool {
	keyword, readable := headerKeyword(value)
	if !readable {
		return false // Precedence decides nothing on its own; the veto handles it.
	}
	switch strings.ToLower(keyword) {
	case "auto_reply", autoReplied, "auto_replied", "auto-replied":
		return true
	}
	return false
}

func isAutoReply(autoSubmitted, precedence []string) bool {
	for _, v := range autoSubmitted {
		// Every occurrence is read, not the topmost: a relay that PREPENDS its
		// own `auto-generated` would otherwise mask the responder's
		// `auto-replied` sitting underneath it.
		if !reachesGate(v) {
			return true
		}
	}
	for _, v := range precedence {
		if isAutoReplyPrecedence(v) {
			return true
		}
	}
	return false
}

// isMachineTouched reports whether ANY machine hand shows on this message —
// including the bulk-family markers a newsletter carries, which isAutoReply
// deliberately lets through so the tier gate can judge them.
//
// The two questions are separate because they pull opposite ways on the same
// headers: the drop must be narrow so the tier gate sees transactional mail,
// and the veto must be wide because it only ever withholds evidence. A single
// answer cannot satisfy both.
func isMachineTouched(autoSubmitted, precedence []string, autoresponderHeader bool) bool {
	if autoresponderHeader {
		return true
	}
	for _, v := range autoSubmitted {
		// The KEYWORD, exactly as the drop rule reads it: `no; owner-email=…`
		// is legal RFC 3834 and still means a person wrote this.
		keyword, readable := headerKeyword(v)
		if !readable || !strings.EqualFold(keyword, notAutomatic) {
			return true
		}
	}
	for _, v := range precedence {
		if isAutoReplyPrecedence(v) {
			return true
		}
		keyword, readable := headerKeyword(v)
		if !readable {
			return true
		}
		switch strings.ToLower(keyword) {
		case "bulk", "list", "junk":
			return true
		}
	}
	return false
}

// stripHeaderComments removes RFC 5322 comments — parenthesized runs, which may
// nest and may contain quoted pairs. Header values are attacker-shaped text, so
// this walks the bytes rather than trusting a pattern: an unclosed parenthesis
// swallows the rest, which keeps a malformed value from resolving to a keyword
// it does not carry.
//
// A `(` inside a quoted-string is NOT distinguished from a real comment. That
// is safe for both callers, which read only the keyword before the first
// semicolon, and it fails toward swallowing rather than inventing a keyword.
func stripHeaderComments(value string) (stripped string, wellFormed bool) {
	var out strings.Builder
	depth := 0
	for i := 0; i < len(value); i++ {
		switch c := value[i]; {
		case c == '\\' && depth > 0 && i+1 < len(value):
			i++ // quoted-pair inside a comment: the escaped byte is comment text
		case c == '(':
			depth++
		case c == ')' && depth > 0:
			depth--
		default:
			if depth == 0 {
				out.WriteByte(c)
			}
		}
	}
	// depth > 0 means a comment was opened and never closed: whatever it
	// swallowed is unknown, so the caller must not read the survivors as the
	// value. Reporting it is the difference between "the value is `no`" and
	// "the value might have been anything".
	return strings.TrimSpace(out.String()), depth == 0
}

// hasAutoresponderHeader reports the legacy vendor markers a responder sets
// when it sets nothing standard — the shape that predates RFC 3834 and still
// ships in Exim recipes and older groupware.
func hasAutoresponderHeader(header mail.Header) bool {
	for _, name := range machineHandledHeaders {
		if header.Has(name) {
			return true
		}
	}
	return false
}

// machineHandledHeaders are the markers that say a machine handled or authored
// this message where no RFC 3834 value does. The first two are the legacy
// autoresponder spellings that predate that RFC and still ship in Exim recipes
// and older groupware; X-Loop is the most common homegrown one. The List-*
// pair is the modern spelling of what `Precedence: list` says, and landing the
// two on opposite sides of the same question is the split's own defect class.
//
// All of them only ever WITHHOLD attestation. A message the owner truly wrote
// loses nothing by not vouching for an address unless that address is already
// transactional-suppressed, so the wide reading costs little and the narrow one
// costs a spare nobody chose.
var machineHandledHeaders = []string{
	"X-Autoreply", "X-Autorespond", "X-Loop", "List-Id", "List-Unsubscribe",
}
