-- 0236: the staged message keeps its markup alongside its text.
--
-- comms_outbound snapshots what is about to be transmitted, and a retry
-- rebuilds the message from that snapshot alone — so a body shape the column
-- cannot hold is a body shape the product cannot send, whatever the renderer
-- downstream is capable of.
--
-- html_body is NULL for a plain-text send, which is every send today. It never
-- replaces body: a message carrying both goes out as multipart/alternative with
-- the plain part first, so a client that cannot render HTML still receives the
-- words. That is also why the column is nullable rather than defaulted to '' —
-- "there is no markup" and "the markup is empty" are different messages, and
-- only the first one may be sent as a single text/plain part.
ALTER TABLE comms_outbound ADD COLUMN html_body text NULL;
