-- 0237: the staged message remembers who it is from, by name.
--
-- The From header carried a bare address, so every message this product sent
-- arrived from the LOCAL PART of the mailbox — a mail from lars@gradion.com
-- showed up as "lars". The name the CRM already holds (app_user.display_name)
-- never reached the wire.
--
-- It is snapshotted here rather than resolved at transmit time for the same
-- reason every other wire field is: a retry rebuilds the message from this row
-- alone, and a sender who renames themselves between the first attempt and the
-- second must not change what the recipient sees on a message already in
-- flight.
--
-- NULL is a sender with no name on file, which renders the bare address exactly
-- as before.
ALTER TABLE comms_outbound ADD COLUMN from_name text NULL;
