-- 0238: a staged delivery remembers its blind copies.
--
-- comms_outbound is the retry snapshot: the dispatcher rebuilds the message
-- from this row alone, so an addressee the column cannot hold is an addressee
-- the retry silently drops. A bcc'd recipient who received the first attempt
-- and not the second is the shape that failure takes.
--
-- Stored beside cc rather than folded into it, because the two differ in
-- exactly one way that matters: cc is rendered into a header every recipient
-- reads and bcc is not. One column holding both would make "blind" a property
-- of the rendering code rather than of the data, and the next reader of that
-- code would have no way to tell which addresses were which.
--
-- The privacy scrub clears it with recipients and cc (privacy/deliveries.go):
-- a blind copy is still a person's address, and an erasure that left it would
-- keep the one recipient list nobody else could see.
ALTER TABLE comms_outbound ADD COLUMN bcc jsonb NULL;
