-- A proposal a human is asked to confirm has to be checkable, and the only
-- thing that makes it checkable is the material it was read out of. The wire
-- contract has declared Approval.evidence[] since the surface was written, but
-- nothing has ever populated it because there was nowhere to put it: a reviewer
-- could see WHAT was proposed and never WHERE it came from, which turns a
-- confirmation into a vote of confidence in the model.
--
-- evidence is per-claim, not per-approval prose: each element carries the
-- snippet it read, the record it read it from, and — for a source whose body is
-- line-addressed, a meeting transcript today — the 1-based line numbers within
-- it (ADR-0058). Line numbers are positions in the source's stored body, not a
-- second copy of it, so they stay true as long as the body does.
--
-- jsonb, not a child table: evidence has no lifecycle of its own. It is
-- immutable once staged, read only with the approval that carries it, and dies
-- with it (ADR-0036 — the staged row IS the authority object, and a second
-- object with its own lifecycle is what produces "approved but never
-- executed"). Nullable because every approval staged before this column
-- existed genuinely has none, and an empty array would claim it was read
-- and found nothing.
ALTER TABLE approval ADD COLUMN evidence jsonb NULL;
