-- Irreversible by design: `mcp`, `ui` and `manual` are one word now, and the
-- row no longer carries which of the three it was.
--
-- Nothing else carries it either. captured_by records WHO wrote the row — the
-- person, or the passport acting for them — not which surface they used, so a
-- row written by a person through an assistant and one written by that person
-- through a form are now identical in the database. That distinction is gone,
-- deliberately: `source` is meant to say where a row came FROM, and "a person
-- asked us to write it down" is one origin however they asked.
--
-- If a later feature needs the channel back it needs a column that means the
-- channel, populated going forward. A down migration that guessed would be
-- worse than one that does nothing.
SELECT 1;
