// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// Package mcp defines the governed tool contract (interfaces.md §2,
// 03b Layer 1). A tool registers a name, the Passport scope it requires,
// its autonomy tier, and JSON-schema in/out bound to a crm.yaml operation.
// The registry's admission gate — scope ∧ tier (∧ the read/full seat
// ceiling) — runs BEFORE Handle, so per-call policy lives in the typed
// model, never ad-hoc inside a handler. (Per-agent quota/budget is
// specified but not yet enforced here; it joins this gate when the budget
// layer lands.)
package mcp

import (
	"context"
	"encoding/json"

	"github.com/gradionhq/margince/backend/internal/shared/kernel/principal"
)

// Tool is a single governed MCP tool, exposed identically to every
// compliant agent (BYO Claude/Cursor/Copilot or the first-party runner).
type Tool interface {
	Spec() ToolSpec
	// Handle runs only after admission. Validation is by the handler's typed
	// decode (decodeArgs into a strict struct), NOT a generic check against
	// Spec().InputSchema: InputSchema/OutputSchema are client-facing
	// documentation (what tools/list advertises), so any required-field or
	// range rule that must actually hold has to be enforced in the decode +
	// its tests, not left to the schema alone.
	Handle(ctx context.Context, in json.RawMessage) (json.RawMessage, error)
}

// ToolSpec is the registration shape, versioned and contract-bound to
// crm.yaml (one source of truth for wire shape).
type ToolSpec struct {
	Name string
	// Title is the human-readable display name a client shows in place of
	// Name (the protocol's precedence is title > annotations.title > name).
	// It is written, not derived from Name: a title generated by
	// un-snake-casing the identifier is the identifier again, which is
	// exactly what the field exists to improve on.
	Title string
	// Description is what the tool is FOR, in the caller's terms: the outcome
	// it produces and the intent that reaches for it, the limits that decide
	// whether it can produce it, when a neighbour is the better call, and what
	// to keep from its result for the follow-up call.
	//
	// It is WRITTEN, not derived. Governance — the autonomy tier, the passport
	// scope, whether the call leaves the workspace — is already answered by the
	// fields below, and each surface that serves this text appends its own
	// reading of them. A description that only restated governance is exactly
	// what this field replaces: it explains how a tool is policed to a model
	// whose question is which tool to call.
	Description   string
	Version       string
	RequiredScope principal.Scope
	Tier          RiskTier
	// TierResolver is non-nil iff Tier == TierDynamic; the admission gate
	// calls it with the validated args plus the resolved pipeline context.
	TierResolver TierResolver
	// InputSchema/OutputSchema are client-facing documentation advertised by
	// tools/list; they are NOT generically validated (M2) — handlers decode
	// into strict typed structs and enforce their own invariants.
	InputSchema  json.RawMessage
	OutputSchema json.RawMessage
	OpenAPIOp    string // the crm.yaml operationId (or logical op family) this maps to
	Egress       bool   // true if the tool reaches outside the workspace (send_email, webhooks)
}

// ReadOnly reports whether the tool only reads — the protocol's
// readOnlyHint.
//
// DERIVED from RequiredScope rather than declared, because the scope model
// already answers this question and the gate already enforces that answer. A
// second, hand-set copy could disagree with the scope actually enforced, and
// the hint is the half that would be believed.
//
// ScopeRead and nothing else. Draft is NOT read-only: the scope covers both
// draft_email, which returns a proposal and writes nothing, and
// draft_follow_ups_for, which persists a draft activity on the deal's
// timeline through the same provider write path every other tool rides. One
// scope, two behaviours — so the scope cannot answer the question for it, and
// the conservative half is the only honest one. Reporting a tool that writes
// as read-only is a false claim; reporting draft_email as writing costs it a
// hint the protocol defaults to false anyway.
func (s ToolSpec) ReadOnly() bool {
	return s.RequiredScope == principal.ScopeRead
}

// RiskTier is the autonomy class (A34/ADR-0026). AutoExecute and ConfirmationRequired are
// static — the declared value is the tool's whole tier. Dynamic means the
// effective tier depends on the call's arguments and MUST carry a
// TierResolver (today only advance_deal/progress_deal: 🟢 open→open,
// 🟡 to won/lost).
type RiskTier int

// The three autonomy tiers. AutoExecute and ConfirmationRequired are the
// static values; Dynamic resolves to one of them per call (see RiskTier).
const (
	TierAutoExecute RiskTier = iota
	TierConfirmationRequired
	TierDynamic
)

// TierResolver maps one call to its effective static tier. The input
// carries the validated args plus the target stage and pipeline, because
// won/lost is a property of the stage's semantic, not of the request
// arguments (a custom pipeline's renamed "Won" stage still resolves 🟡).
// Invariant: a resolver may only ever RAISE to TierConfirmationRequired — it never
// returns TierDynamic and never resolves an always-🟡 floor case to the auto-execute tier.
type TierResolver func(in TierResolverInput) RiskTier

// TierResolverInput is what the admission gate hands a resolver.
type TierResolverInput struct {
	Args json.RawMessage
	// SourceStageSemantic is the resolved semantic of the stage the record is
	// currently IN, and TargetStageSemantic the one it moves to: "open" |
	// "won" | "lost".
	//
	// Both endpoints, because the risk is not a property of the destination.
	// Moving a won deal back to an open stage is a reopen — it clears the close
	// date, the lost reason and the FX rate frozen at close, and takes revenue
	// out of a reported quarter — and a resolver shown only the target sees an
	// ordinary open-stage move.
	SourceStageSemantic string
	TargetStageSemantic string
	PipelineID          string
}

// Registry admits and dispatches tools. Registration is init()-time,
// one file per tool; a duplicate name fails fast at boot.
type Registry interface {
	Register(t Tool)
	// Invoke runs the admission gate (scope ∧ tier ∧ seat ceiling) and then
	// the tool. A 🟡 call without a valid approval token returns
	// apperrors.ErrRequiresApproval with the staged approval reference.
	Invoke(ctx context.Context, name string, in json.RawMessage) (json.RawMessage, error)
	Specs() []ToolSpec
}
