// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

// Command gen-payloads compiles isolated, components-only OpenAPI documents
// into typed Go structs — the public contract for outbound event/webhook
// payloads. It reuses the oapi-codegen LIBRARY (not the CLI) over each source
// so the payload files stay isolated from api/crm.yaml: crm.yaml's webhooks:
// block is silently pruned by kin-openapi, and flipping global skip-prune
// there trips a pre-existing ApprovalToken name collision. An isolated file
// carries only our schemas, so generating every component is safe with no
// synthetic-path trick.
//
// For every schema carrying x-event-type / x-entity-type, the generator also
// projects EventType()/EntityType() methods onto the generated struct, so an
// emit site and its schema cannot drift without failing to compile.
//
// The generator is config-driven (config.go): a family is one slice entry,
// nothing here is webhook-specific.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
)

func main() {
	root, err := backendRoot()
	if err != nil {
		log.Fatalf("gen-payloads: %v", err)
	}
	for _, g := range groups {
		if err := generateGroup(root, g); err != nil {
			log.Fatalf("gen-payloads: %s: %v", g.Source, err)
		}
	}
	fmt.Printf("gen-payloads: %d group(s) generated\n", len(groups))
}

// generateGroup compiles one group's Source file into its Out file.
func generateGroup(root string, g group) error {
	src, err := os.ReadFile(filepath.Join(root, g.Source)) // #nosec G304 -- build-time tool, config-driven source path
	if err != nil {
		return fmt.Errorf("reading source: %w", err)
	}
	out, err := generateSource(src, g.Package)
	if err != nil {
		return err
	}
	dst := filepath.Join(root, g.Out)
	if err := os.WriteFile(dst, []byte(out), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", g.Out, err)
	}
	return nil
}

// generateSource is the generator core, kept file-IO-free so it is exercised
// directly by the unit test: normalize the 3.1 source into codegen's 3.0
// subset, emit models with oapi-codegen, then append the event/entity-type
// methods and re-stamp our own banner.
func generateSource(specYAML []byte, pkg string) (string, error) {
	normalized, err := downgradeToOpenAPI30(specYAML)
	if err != nil {
		return "", err
	}

	loader := openapi3.NewLoader()
	spec, err := loader.LoadFromData(normalized)
	if err != nil {
		return "", fmt.Errorf("loading spec: %w", err)
	}

	// SkipPrune: the source is isolated (only our schemas), so pruning by
	// path-reachability would delete every component — there are no paths.
	// Keeping every component is exactly what we want and is safe here.
	body, err := codegen.Generate(spec, codegen.Configuration{
		PackageName: pkg,
		Generate:    codegen.GenerateOptions{Models: true},
		OutputOptions: codegen.OutputOptions{
			SkipPrune: true,
		},
	})
	if err != nil {
		return "", fmt.Errorf("codegen: %w", err)
	}

	methods, err := eventMethods(spec)
	if err != nil {
		return "", err
	}

	assembled := restampBanner(body, pkg)
	if methods != "" {
		assembled += "\n" + methods
	}

	formatted, err := format.Source([]byte(assembled))
	if err != nil {
		return "", fmt.Errorf("formatting generated source: %w", err)
	}
	return string(formatted), nil
}

const banner = "// Code generated by gen-payloads; DO NOT EDIT.\n"

// restampBanner drops oapi-codegen's own header (which embeds a build version
// that is not stable across environments) and replaces it with our fixed,
// drift-safe banner, keeping the generated package clause and body verbatim.
func restampBanner(body, pkg string) string {
	pkgClause := "package " + pkg
	lines := strings.Split(body, "\n")
	for i, ln := range lines {
		if ln == pkgClause {
			rest := strings.Join(lines[i:], "\n")
			return banner + "\n" + rest
		}
	}
	// No recognizable package clause: fall back to prepending the banner so
	// the failure surfaces at compile time rather than silently mis-stamping.
	return banner + "\n" + body
}

// eventMethods returns the sorted EventType()/EntityType() method block for
// every schema carrying x-event-type / x-entity-type. The Go type name is the
// component name (the source authors them as valid PascalCase identifiers,
// which is exactly what oapi-codegen emits for such names).
func eventMethods(spec *openapi3.T) (string, error) {
	if spec.Components == nil {
		return "", nil
	}
	names := make([]string, 0, len(spec.Components.Schemas))
	for name := range spec.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	for _, name := range names {
		ref := spec.Components.Schemas[name]
		if ref == nil || ref.Value == nil {
			continue
		}
		ext := ref.Value.Extensions
		eventType, hasEvent, err := stringExtension(ext, "x-event-type", name)
		if err != nil {
			return "", err
		}
		entityType, hasEntity, err := stringExtension(ext, "x-entity-type", name)
		if err != nil {
			return "", err
		}
		if !hasEvent && !hasEntity {
			continue
		}
		if hasEvent != hasEntity {
			return "", fmt.Errorf("schema %q must declare both x-event-type and x-entity-type or neither", name)
		}
		// A blank line between each method keeps gofmt from column-aligning
		// adjacent single-line declarations (which would widen the ` { ` gap).
		fmt.Fprintf(&b, "func (%s) EventType() string { return %q }\n\n", name, eventType)
		fmt.Fprintf(&b, "func (%s) EntityType() string { return %q }\n\n", name, entityType)
	}
	return b.String(), nil
}

// stringExtension reads an x- extension as a string. kin-openapi decodes
// extensions into map[string]any via encoding/json, so a scalar string lands
// as a Go string; json.RawMessage is tolerated for forward-compatibility.
func stringExtension(ext map[string]any, key, schema string) (string, bool, error) {
	raw, ok := ext[key]
	if !ok {
		return "", false, nil
	}
	switch v := raw.(type) {
	case string:
		return v, true, nil
	case json.RawMessage:
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			return "", false, fmt.Errorf("schema %q: %s must be a string: %w", schema, key, err)
		}
		return s, true, nil
	default:
		return "", false, fmt.Errorf("schema %q: %s must be a string, got %T", schema, key, raw)
	}
}

// backendRoot walks up from the working directory to the backend Go module
// root (the directory whose go.mod declares the backend module). The
// //go:generate directive runs from internal/contracts, but resolving the
// module root explicitly keeps the tool runnable from anywhere.
func backendRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	const want = "module github.com/gradionhq/margince/backend"
	for {
		gomod := filepath.Join(dir, "go.mod")
		if data, err := os.ReadFile(gomod); err == nil { // #nosec G304 -- walking to locate the module root
			first := string(data)
			if i := strings.IndexByte(first, '\n'); i >= 0 {
				first = first[:i]
			}
			if strings.TrimSpace(first) == want {
				return dir, nil
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not locate the backend module root (%q) above the working directory", want)
		}
		dir = parent
	}
}
