// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"fmt"
	"go/format"
	"strings"
)

// emitKinds renders internal/compose/jobkinds_gen.go: the closed set of args
// types a worker may be registered under, the one registration entry point
// constrained to it, and the role assertions that used to be a hand-written
// list beside them. All three come from the same source as the spec table, so
// the set, the roles and the declaration cannot drift apart.
//
// Kinds arrive already sorted, so every emitted list is byte-stable.
func emitKinds(c contract, contractHash string) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-jobs from api/jobs.yaml. DO NOT EDIT.\n\n")
	b.WriteString("package compose\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/riverqueue/river\"\n\n")
	b.WriteString("\t\"github.com/gradionhq/margince/backend/internal/platform/jobs\"\n")
	b.WriteString(")\n\n")

	b.WriteString("// jobContractHash is the sha256 of api/jobs.yaml this file was generated\n")
	b.WriteString("// from — the same fingerprint jobs.JobContractHash carries, so a stale\n")
	b.WriteString("// half of the pair is visible without diffing the two tables.\n")
	fmt.Fprintf(&b, "const jobContractHash = %q\n\n", contractHash)

	writeDeclaredSet(&b, c)
	writeAddDeclaredWorker(&b)
	writeRoleAssertions(&b, c)

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("formatting the generated kind set: %w", err)
	}
	return string(formatted), nil
}

// writeDeclaredSet renders the type-set constraint. It is a union rather than
// a marker interface on purpose: a marker is something a new type can declare
// for itself, and the whole point is that a kind api/jobs.yaml has never heard
// of cannot be registered at all.
func writeDeclaredSet(b *strings.Builder, c contract) {
	b.WriteString("// declaredJobArgs is every args type api/jobs.yaml declares, and nothing\n")
	b.WriteString("// else. A job kind the file has never heard of cannot satisfy it, so it\n")
	b.WriteString("// cannot be passed to addDeclaredWorker below.\n")
	b.WriteString("//\n")
	b.WriteString("// Registration does not route through that function yet — the runner has\n")
	b.WriteString("// its own unconstrained helper — so what the set buys today is a closed\n")
	b.WriteString("// list the compiler checks, not a gate every registration has to pass. The\n")
	b.WriteString("// commit that routes registration through it is what makes an undeclared\n")
	b.WriteString("// kind unbuildable.\n")
	b.WriteString("type declaredJobArgs interface {\n")
	b.WriteString("\triver.JobArgs\n\n")
	for i, name := range c.sortedKinds() {
		sep := " |"
		if i == len(c.Kinds)-1 {
			sep = ""
		}
		fmt.Fprintf(b, "\t%s%s\n", c.Kinds[name].GoType, sep)
	}
	b.WriteString("}\n\n")
}

// writeAddDeclaredWorker renders the single registration entry point.
//
// The body is still River's own AddWorker. jobs.Govern now exists and the
// runner's own helper already supplies the declared timeout through it; what
// is left for the commit that adopts this function is to narrow the parameter
// to jobs.WorkOnly[T] and make the closed constraint above the one every
// registration has to pass.
func writeAddDeclaredWorker(b *strings.Builder) {
	b.WriteString("// addDeclaredWorker registers one worker for a DECLARED kind: its type\n")
	b.WriteString("// parameter is constrained to the set above, so a kind api/jobs.yaml does\n")
	b.WriteString("// not declare cannot be passed to it.\n")
	b.WriteString("//\n")
	b.WriteString("// It is not yet the only way in. The runner registers through a helper of\n")
	b.WriteString("// its own whose type parameter is unconstrained, so an undeclared kind can\n")
	b.WriteString("// still be registered around this function; the commit that moves every\n")
	b.WriteString("// registration onto it is what makes the declared set the set this build\n")
	b.WriteString("// can actually work.\n")
	b.WriteString("func addDeclaredWorker[T declaredJobArgs](workers *river.Workers, w river.Worker[T]) {\n")
	b.WriteString("\triver.AddWorker(workers, w)\n")
	b.WriteString("}\n\n")
}

// writeRoleAssertions renders the compile-time role markers. They are
// load-bearing — jobs.WorkspaceScoped is what binds a job's workspace, and the
// fleet-report gate reads both markers — so a misspelled accessor or a marker
// on the wrong type is a build error at the args type, which is where a
// contributor will actually see it.
func writeRoleAssertions(b *strings.Builder, c contract) {
	b.WriteString("// The declared dispatchers: each enumerates the fleet and enqueues, and does\n")
	b.WriteString("// no tenant work of its own.\n")
	b.WriteString("var (\n")
	for _, name := range c.sortedKinds() {
		if def := c.Kinds[name]; def.Role == roleDispatcher {
			fmt.Fprintf(b, "\t_ jobs.FleetWide = %s{}\n", def.GoType)
		}
	}
	b.WriteString(")\n\n")

	b.WriteString("// The declared workspace-scoped kinds: each carries exactly one tenant's\n")
	b.WriteString("// pass and says which in its own args.\n")
	b.WriteString("var (\n")
	for _, name := range c.sortedKinds() {
		if def := c.Kinds[name]; def.Role == roleWorkspace {
			fmt.Fprintf(b, "\t_ jobs.WorkspaceScoped = %s{}\n", def.GoType)
		}
	}
	b.WriteString(")\n")
}
