// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"fmt"
	"go/format"
	"strings"
	"time"
)

// emitSpecs renders internal/platform/jobs/specs_gen.go: the kind-keyed Spec
// table SpecFor, Declared and MustBeTotal are built on. It carries no compose
// identifier — platform never learns what a kind's worker does, only what the
// contract says about it.
//
// Kinds arrive already sorted, so the map literal is byte-stable across runs.
func emitSpecs(c contract, contractHash string) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-jobs from api/jobs.yaml. DO NOT EDIT.\n\n")
	b.WriteString("package jobs\n\n")
	b.WriteString("import \"time\"\n\n")

	b.WriteString("// JobContractHash is the sha256 of api/jobs.yaml at generation time: a\n")
	b.WriteString("// build fingerprint a census can compare against a freshly hashed\n")
	b.WriteString("// contract file to catch a stale generated table.\n")
	fmt.Fprintf(&b, "const JobContractHash = %q\n\n", contractHash)

	b.WriteString("// specs is every declared kind. A kind absent from this table is a kind\n")
	b.WriteString("// nobody declared, which MustBeTotal refuses at boot rather than letting it\n")
	b.WriteString("// run on River's one-minute default.\n")
	b.WriteString("var specs = map[string]Spec{\n")
	for _, name := range c.sortedKinds() {
		writeSpec(&b, name, c.Kinds[name])
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("formatting the generated spec table: %w", err)
	}
	return string(formatted), nil
}

// writeSpec renders one map entry. Every field the entry does not declare is
// left off rather than written as its zero: the reader of a generated table
// should be able to see what the contract actually said.
func writeSpec(b *strings.Builder, name string, def kindDef) {
	fmt.Fprintf(b, "\t%q: {\n", name)
	fmt.Fprintf(b, "\t\tKind: %q,\n", name)
	fmt.Fprintf(b, "\t\tRole: %s,\n", roleConst(def.Role))
	fmt.Fprintf(b, "\t\tQueue: %q,\n", def.Queue)
	fmt.Fprintf(b, "\t\tTimeout: %s,\n", timeoutLiteral(*def.Timeout))
	if def.MaxAttempts != nil {
		fmt.Fprintf(b, "\t\tMaxAttempts: %d,\n", *def.MaxAttempts)
	}
	if def.FansOutTo != "" {
		fmt.Fprintf(b, "\t\tFanOutUnit: %s,\n", unitConst(def.FanOutUnit))
		fmt.Fprintf(b, "\t\tFanOutTo: %q,\n", def.FansOutTo)
	}
	fmt.Fprintf(b, "\t\tOptsOwner: %s,\n", optsConst(def.OptsOwner))
	if lit := cadenceLiteral(def.Cadence); lit != "" {
		fmt.Fprintf(b, "\t\tCadence: %s,\n", lit)
	}
	if lit := registrationLiteral(def.Registration); lit != "" {
		fmt.Fprintf(b, "\t\tRegistration: %s,\n", lit)
	}
	b.WriteString("\t},\n")
}

func roleConst(role string) string {
	if role == roleDispatcher {
		return "Dispatcher"
	}
	return "Workspace"
}

func unitConst(unit string) string {
	switch unit {
	case unitConnection:
		return "FanOutConnection"
	case unitBuild:
		return "FanOutBuild"
	default:
		return "FanOutWorkspace"
	}
}

func optsConst(owner string) string {
	switch owner {
	case optsFanOut:
		return "OptsFanOut"
	case optsArgs:
		return "OptsArgs"
	default:
		return "OptsCaller"
	}
}

// timeoutLiteral renders the policy. A {derived: …} entry keeps BOTH its
// resolved duration (what Govern hands River) and the constant name (what the
// census compares against), so the declaration tracks the upstream constant
// instead of freezing a copy of its value.
func timeoutLiteral(t timeoutDef) string {
	switch {
	case t.None:
		return "TimeoutPolicy{None: true}"
	case t.Operator != "":
		return "TimeoutPolicy{FromOperator: true}"
	case t.Derived != "":
		return fmt.Sprintf("TimeoutPolicy{Fixed: %s, DerivedFrom: %q}", goDuration(t.Fixed), t.Derived)
	default:
		return fmt.Sprintf("TimeoutPolicy{Fixed: %s}", goDuration(t.Fixed))
	}
}

// cadenceLiteral returns "" for a kind with no schedule — a workspace kind, or
// the one dispatcher a human's confirm enqueues.
func cadenceLiteral(c *cadenceDef) string {
	if c == nil || c.OnDemand {
		return ""
	}
	fields := make([]string, 0, 2)
	if c.Fixed != 0 {
		fields = append(fields, "Fixed: "+goDuration(c.Fixed))
	}
	if c.Operator != "" {
		fields = append(fields, fmt.Sprintf("OperatorField: %q", c.Operator))
	}
	if c.ScheduleWhenPositive != "" {
		fields = append(fields, fmt.Sprintf("ScheduleWhenPositive: %q", c.ScheduleWhenPositive))
	}
	return "Cadence{" + strings.Join(fields, ", ") + "}"
}

// registrationLiteral returns "" for a kind that registers unconditionally.
func registrationLiteral(r *registrationDef) string {
	if r == nil || len(r.When) == 0 {
		return ""
	}
	quoted := make([]string, 0, len(r.When))
	for _, field := range r.When {
		quoted = append(quoted, fmt.Sprintf("%q", field))
	}
	lit := "Registration{When: []string{" + strings.Join(quoted, ", ") + "}"
	if r.Absent == absentRegistersAnyway {
		lit += ", AbsentRegistersAnyway: true"
	}
	return lit + "}"
}

// goDuration renders a duration as the Go source a human would have written.
// The ladder is deterministic — the same duration always renders the same way
// — which is what keeps the drift gate from firing on a re-run.
func goDuration(d time.Duration) string {
	switch {
	case d == 0:
		return "0"
	case d%time.Hour == 0:
		return fmt.Sprintf("%d * time.Hour", d/time.Hour)
	case d%time.Minute == 0:
		return fmt.Sprintf("%d * time.Minute", d/time.Minute)
	case d%time.Second == 0:
		return fmt.Sprintf("%d * time.Second", d/time.Second)
	default:
		return fmt.Sprintf("%d * time.Nanosecond", d)
	}
}
