#!/usr/bin/env bash
# Regenerates docs/adr/README.md from the records themselves.
#
# The index is generated because a hand-maintained one drifts: the previous
# system kept an index and the records in two places and they disagreed about
# which decisions were live. Here the record is the only input, so the index
# cannot claim something the tree does not contain.
#
# Run: make adr-index (or this script directly). The gate in
# backend/adrindex_test.go fails when the committed index is stale.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
adr_dir="$repo_root/docs/adr"

# Writes to docs/adr/README.md by default. An argument redirects the output,
# which is how the staleness gate compares without touching the tree it checks:
# a check that rewrites the file it is checking corrupts the worktree whenever
# it fails partway, and two packages testing at once race on that one file.
out="${1:-$adr_dir/README.md}"

{
  echo "# Decision records"
  echo
  echo "Why the product is built the way it is. A record carries the reasoning;"
  echo "the code and its tests carry the behaviour."
  echo
  echo "**A record can be superseded.** When the decision changes, write the"
  echo "replacement in the same pull request as the code that changes, and mark the"
  echo "old one superseded so a reader lands on the live answer. A record that is"
  echo "silently wrong is worse than no record."
  echo
  echo "New records continue from the highest number here. Take that number from"
  echo "\`origin/main\` rather than from a branch — a stale branch shows a number as"
  echo "free when somebody else has already taken it."
  echo
  echo "This file is generated by \`scripts/gen-adr-index.sh\`. Do not edit it."
  echo
  echo "| Record | Decision | Status |"
  echo "|---|---|---|"

  for f in "$adr_dir"/ADR-*.md; do
    [ -e "$f" ] || continue
    base="$(basename "$f" .md)"
    num="${base#ADR-}"; num="${num%%-*}"
    # The title is the H1 with the "ADR-NNNN — " prefix stripped.
    title="$(grep -m1 '^# ' "$f" | sed 's/^# //; s/^ADR-[0-9]* — //')"
    # A status may wrap onto following lines — a record that names which half
    # of it is built usually does. Take every line from the marker up to the
    # blank line that ends the metadata block, and collapse it into one cell so
    # the table does not truncate the qualifier mid-sentence.
    status="$(awk '/^\*\*Status:\*\*/{f=1} f{if ($0 ~ /^\*\*Decided:\*\*/ || $0 == "") exit; print}' "$f" \
      | sed 's/^\*\*Status:\*\* //' | tr '\n' ' ' | sed 's/  */ /g; s/ *$//')"
    printf '| [ADR-%s](%s.md) | %s | %s |\n' "$num" "$base" "$title" "${status:-—}"
  done
} > "$out"

echo "OK: $(basename "$out") regenerated ($(ls "$adr_dir"/ADR-*.md 2>/dev/null | wc -l | tr -d ' ') records)"
