// Package crm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package crm

import (
	"time"
)

// Defines values for ActivityCaptureLabel.
const (
	ActivityCaptureLabelCommitment  ActivityCaptureLabel = "commitment"
	ActivityCaptureLabelLessThannil ActivityCaptureLabel = "<nil>"
	ActivityCaptureLabelMeeting     ActivityCaptureLabel = "meeting"
	ActivityCaptureLabelNoise       ActivityCaptureLabel = "noise"
)

// Valid indicates whether the value is a known member of the ActivityCaptureLabel enum.
func (e ActivityCaptureLabel) Valid() bool {
	switch e {
	case ActivityCaptureLabelCommitment:
		return true
	case ActivityCaptureLabelLessThannil:
		return true
	case ActivityCaptureLabelMeeting:
		return true
	case ActivityCaptureLabelNoise:
		return true
	default:
		return false
	}
}

// Defines values for ActivityDirection.
const (
	ActivityDirectionInbound     ActivityDirection = "inbound"
	ActivityDirectionLessThannil ActivityDirection = "<nil>"
	ActivityDirectionOutbound    ActivityDirection = "outbound"
)

// Valid indicates whether the value is a known member of the ActivityDirection enum.
func (e ActivityDirection) Valid() bool {
	switch e {
	case ActivityDirectionInbound:
		return true
	case ActivityDirectionLessThannil:
		return true
	case ActivityDirectionOutbound:
		return true
	default:
		return false
	}
}

// Defines values for ActivityKind.
const (
	ActivityKindCall     ActivityKind = "call"
	ActivityKindEmail    ActivityKind = "email"
	ActivityKindMeeting  ActivityKind = "meeting"
	ActivityKindNote     ActivityKind = "note"
	ActivityKindTask     ActivityKind = "task"
	ActivityKindTelegram ActivityKind = "telegram"
	ActivityKindWhatsapp ActivityKind = "whatsapp"
)

// Valid indicates whether the value is a known member of the ActivityKind enum.
func (e ActivityKind) Valid() bool {
	switch e {
	case ActivityKindCall:
		return true
	case ActivityKindEmail:
		return true
	case ActivityKindMeeting:
		return true
	case ActivityKindNote:
		return true
	case ActivityKindTask:
		return true
	case ActivityKindTelegram:
		return true
	case ActivityKindWhatsapp:
		return true
	default:
		return false
	}
}

// Defines values for ActivityMeetingStatus.
const (
	ActivityMeetingStatusBooked      ActivityMeetingStatus = "booked"
	ActivityMeetingStatusCanceled    ActivityMeetingStatus = "canceled"
	ActivityMeetingStatusHeld        ActivityMeetingStatus = "held"
	ActivityMeetingStatusLessThannil ActivityMeetingStatus = "<nil>"
	ActivityMeetingStatusNoShow      ActivityMeetingStatus = "no_show"
)

// Valid indicates whether the value is a known member of the ActivityMeetingStatus enum.
func (e ActivityMeetingStatus) Valid() bool {
	switch e {
	case ActivityMeetingStatusBooked:
		return true
	case ActivityMeetingStatusCanceled:
		return true
	case ActivityMeetingStatusHeld:
		return true
	case ActivityMeetingStatusLessThannil:
		return true
	case ActivityMeetingStatusNoShow:
		return true
	default:
		return false
	}
}

// Defines values for ActivityLinkEntityType.
const (
	ActivityLinkEntityTypeDeal         ActivityLinkEntityType = "deal"
	ActivityLinkEntityTypeLead         ActivityLinkEntityType = "lead"
	ActivityLinkEntityTypeOrganization ActivityLinkEntityType = "organization"
	ActivityLinkEntityTypePerson       ActivityLinkEntityType = "person"
	ActivityLinkEntityTypeProject      ActivityLinkEntityType = "project"
)

// Valid indicates whether the value is a known member of the ActivityLinkEntityType enum.
func (e ActivityLinkEntityType) Valid() bool {
	switch e {
	case ActivityLinkEntityTypeDeal:
		return true
	case ActivityLinkEntityTypeLead:
		return true
	case ActivityLinkEntityTypeOrganization:
		return true
	case ActivityLinkEntityTypePerson:
		return true
	case ActivityLinkEntityTypeProject:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestDirection.
const (
	CreateActivityRequestDirectionInbound     CreateActivityRequestDirection = "inbound"
	CreateActivityRequestDirectionLessThannil CreateActivityRequestDirection = "<nil>"
	CreateActivityRequestDirectionOutbound    CreateActivityRequestDirection = "outbound"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestDirection enum.
func (e CreateActivityRequestDirection) Valid() bool {
	switch e {
	case CreateActivityRequestDirectionInbound:
		return true
	case CreateActivityRequestDirectionLessThannil:
		return true
	case CreateActivityRequestDirectionOutbound:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestKind.
const (
	CreateActivityRequestKindCall     CreateActivityRequestKind = "call"
	CreateActivityRequestKindEmail    CreateActivityRequestKind = "email"
	CreateActivityRequestKindMeeting  CreateActivityRequestKind = "meeting"
	CreateActivityRequestKindNote     CreateActivityRequestKind = "note"
	CreateActivityRequestKindTask     CreateActivityRequestKind = "task"
	CreateActivityRequestKindTelegram CreateActivityRequestKind = "telegram"
	CreateActivityRequestKindWhatsapp CreateActivityRequestKind = "whatsapp"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestKind enum.
func (e CreateActivityRequestKind) Valid() bool {
	switch e {
	case CreateActivityRequestKindCall:
		return true
	case CreateActivityRequestKindEmail:
		return true
	case CreateActivityRequestKindMeeting:
		return true
	case CreateActivityRequestKindNote:
		return true
	case CreateActivityRequestKindTask:
		return true
	case CreateActivityRequestKindTelegram:
		return true
	case CreateActivityRequestKindWhatsapp:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestLinksEntityType.
const (
	CreateActivityRequestLinksEntityTypeDeal         CreateActivityRequestLinksEntityType = "deal"
	CreateActivityRequestLinksEntityTypeLead         CreateActivityRequestLinksEntityType = "lead"
	CreateActivityRequestLinksEntityTypeOrganization CreateActivityRequestLinksEntityType = "organization"
	CreateActivityRequestLinksEntityTypePerson       CreateActivityRequestLinksEntityType = "person"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestLinksEntityType enum.
func (e CreateActivityRequestLinksEntityType) Valid() bool {
	switch e {
	case CreateActivityRequestLinksEntityTypeDeal:
		return true
	case CreateActivityRequestLinksEntityTypeLead:
		return true
	case CreateActivityRequestLinksEntityTypeOrganization:
		return true
	case CreateActivityRequestLinksEntityTypePerson:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestMeetingStatus.
const (
	Booked      CreateActivityRequestMeetingStatus = "booked"
	Canceled    CreateActivityRequestMeetingStatus = "canceled"
	Held        CreateActivityRequestMeetingStatus = "held"
	LessThannil CreateActivityRequestMeetingStatus = "<nil>"
	NoShow      CreateActivityRequestMeetingStatus = "no_show"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestMeetingStatus enum.
func (e CreateActivityRequestMeetingStatus) Valid() bool {
	switch e {
	case Booked:
		return true
	case Canceled:
		return true
	case Held:
		return true
	case LessThannil:
		return true
	case NoShow:
		return true
	default:
		return false
	}
}

// Activity A polymorphic timeline item. Mirrors the `activity` table + `activity_link`.
// **Per-kind field constraints** (enforced server-side to match the DB `activity_task_fields`
// CHECK; the OpenAPI cannot express these conditionally): `due_at`/`assignee_id`/`is_done`/
// `done_at` are valid ONLY when `kind=task`; `meeting_status` ONLY when `kind=meeting`;
// `duration_seconds` only for meeting/call; `direction` is null for note/task. Setting a
// disallowed field for the kind returns `422 code: field_not_valid_for_kind` (the API rejects
// what the DB CHECK would reject, rather than 500-ing at write time).
type Activity struct {
	ArchivedAt *time.Time `json:"archived_at,omitempty"`

	// AssigneeId Task only.
	AssigneeId *string `json:"assignee_id,omitempty"`
	Body       *string `json:"body,omitempty"`

	// BulkMailAttested This message carried an RFC 2369 List-Unsubscribe header, so the SENDER declared it bulk. Per message, never per sender: the same address sends a newsletter and a reply, and treating the sender as bulk would bury the reply.
	BulkMailAttested *bool `json:"bulk_mail_attested,omitempty"`

	// CaptureLabel What this message turned out to be, from the batched capture classification. Null means unclassified, which is a backlog state and not a verdict of "ordinary".
	CaptureLabel *ActivityCaptureLabel `json:"capture_label,omitempty"`

	// CapturedBy Server-stamped from the authenticated principal (human:<uuid> | agent:<id> | connector:<name>); never client-supplied.
	CapturedBy *string   `json:"captured_by,omitempty"`
	CreatedAt  time.Time `json:"created_at"`

	// Direction inbound/outbound for email/call; null for note/task.
	Direction *ActivityDirection `json:"direction,omitempty"`
	DoneAt    *time.Time         `json:"done_at,omitempty"`

	// DueAt Task only.
	DueAt *time.Time `json:"due_at,omitempty"`

	// DurationSeconds Meeting/call only.
	DurationSeconds *int   `json:"duration_seconds,omitempty"`
	Id              string `json:"id"`

	// IsDone Task only.
	IsDone *bool        `json:"is_done,omitempty"`
	Kind   ActivityKind `json:"kind"`

	// Links One activity may link to >1 entity (person + deal).
	Links *[]ActivityLink `json:"links,omitempty"`

	// MeetingStatus Set only when kind=meeting.
	MeetingStatus *ActivityMeetingStatus  `json:"meeting_status,omitempty"`
	OccurredAt    time.Time               `json:"occurred_at"`
	Raw           *map[string]interface{} `json:"raw,omitempty"`

	// RemindAt Task only. Reminder-fire time; the B-E16.6 scan reads tasks whose reminder is due, not-done, and un-archived.
	RemindAt *time.Time `json:"remind_at,omitempty"`
	Source   string     `json:"source"`

	// SourceId Provider message/event id — idempotency key part.
	SourceId *string `json:"source_id,omitempty"`

	// SourceSystem gmail/gcal/outlook/transcript — idempotency key part.
	SourceSystem *string `json:"source_system,omitempty"`
	Subject      *string `json:"subject,omitempty"`

	// ThreadKey The provider's own conversation id (Gmail threadId, Graph conversationId, the RFC822 References root), stamped by capture. It is what makes a thread a thread: grouping by subject would merge two unrelated "Re: Update" exchanges and split one that was renamed mid-conversation. Null on anything capture did not thread — a note, a task, a message whose provider offered none.
	ThreadKey *string   `json:"thread_key,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`

	// Version Monotonic row version, incremented by the server on every mutation (data-model §1.3a).
	// Echoed back as the `version` field on every mutable entity. To make a write conditional,
	// send the last-seen value in `If-Match`; a mismatch returns `409 code: version_skew`
	// (ErrVersionSkew) so the client re-reads before retrying. Applies to the native SoR path,
	// not only overlay mode.
	Version *RowVersion `json:"version,omitempty"`
}

// ActivityCaptureLabel What this message turned out to be, from the batched capture classification. Null means unclassified, which is a backlog state and not a verdict of "ordinary".
type ActivityCaptureLabel string

// ActivityDirection inbound/outbound for email/call; null for note/task.
type ActivityDirection string

// ActivityKind defines model for Activity.Kind.
type ActivityKind string

// ActivityMeetingStatus Set only when kind=meeting.
type ActivityMeetingStatus string

// ActivityLink defines model for ActivityLink.
type ActivityLink struct {
	ActivityId *string                `json:"activity_id,omitempty"`
	EntityId   string                 `json:"entity_id"`
	EntityType ActivityLinkEntityType `json:"entity_type"`
	Id         *string                `json:"id,omitempty"`
}

// ActivityLinkEntityType defines model for ActivityLink.EntityType.
type ActivityLinkEntityType string

// CreateActivityRequest defines model for CreateActivityRequest.
type CreateActivityRequest struct {
	AssigneeId      *string                         `json:"assignee_id,omitempty"`
	Body            *string                         `json:"body,omitempty"`
	Direction       *CreateActivityRequestDirection `json:"direction,omitempty"`
	DueAt           *time.Time                      `json:"due_at,omitempty"`
	DurationSeconds *int                            `json:"duration_seconds,omitempty"`
	Kind            CreateActivityRequestKind       `json:"kind"`
	Links           *[]struct {
		EntityId   string                               `json:"entity_id"`
		EntityType CreateActivityRequestLinksEntityType `json:"entity_type"`
	} `json:"links,omitempty"`
	MeetingStatus *CreateActivityRequestMeetingStatus `json:"meeting_status,omitempty"`
	OccurredAt    *time.Time                          `json:"occurred_at,omitempty"`
	Raw           *map[string]interface{}             `json:"raw,omitempty"`

	// RemindAt Task only.
	RemindAt     *time.Time `json:"remind_at,omitempty"`
	Source       string     `json:"source"`
	SourceId     *string    `json:"source_id,omitempty"`
	SourceSystem *string    `json:"source_system,omitempty"`
	Subject      *string    `json:"subject,omitempty"`
}

// CreateActivityRequestDirection defines model for CreateActivityRequest.Direction.
type CreateActivityRequestDirection string

// CreateActivityRequestKind defines model for CreateActivityRequest.Kind.
type CreateActivityRequestKind string

// CreateActivityRequestLinksEntityType defines model for CreateActivityRequest.Links.EntityType.
type CreateActivityRequestLinksEntityType string

// CreateActivityRequestMeetingStatus defines model for CreateActivityRequest.MeetingStatus.
type CreateActivityRequestMeetingStatus string

// RowVersion Monotonic row version, incremented by the server on every mutation (data-model §1.3a).
// Echoed back as the `version` field on every mutable entity. To make a write conditional,
// send the last-seen value in `If-Match`; a mismatch returns `409 code: version_skew`
// (ErrVersionSkew) so the client re-reads before retrying. Applies to the native SoR path,
// not only overlay mode.
type RowVersion = int64
