// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/mod/modfile"

	"github.com/gradionhq/margince/backend/pkg/extension"
)

// compositionModule is the constant import path the role binaries wire
// (backend/go.mod resolves it to the committed vanilla stub; the
// generated go.work overrides it with build/composition/backend).
const compositionModule = "github.com/gradionhq/margince/composition"

// extensionsGenHeader is shared by the vanilla stub and every composed
// output — the vanilla body below it must stay byte-identical to
// composition/extensions_gen.go (held by `-verify` via stubMatchesVanilla).
const extensionsGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (tools/gen-composition). Bare go builds resolve this module's
// committed vanilla stub (composition/ at the repo root) via backend/go.mod's replace;
// composed builds use the generated module under build/composition/ via its go.work.

package composition

import (
`

// extensionsGenSurfaceImport is the one import every lane needs; the
// encoding/json line above it is emitted only when a verb actually carries a
// schema, because an unused import does not compile and the vanilla lane has
// none.
const extensionsGenSurfaceImport = "\t\"github.com/gradionhq/margince/backend/pkg/extension\"\n"

const extensionsGenDoc = `
// Extensions returns the composed extension set for this installation;
// vanilla (an empty extensions/ tree) composes none.
func Extensions() []extension.Extension {
`

// extensionsGenVerbsDoc introduces the contract-derived half of the wiring.
// The literals below it are why the boot needs no file I/O: every refusal in
// compose/extensiontools.go reads a field of one of these values.
const extensionsGenVerbsDoc = `
// Verbs returns every governed operation the enabled units' contract
// fragments declare, read out of the merged contracts at generation time and
// re-emitted here as literals — so a bare role binary, which ships no
// repository, still knows each operation's route, risk tier, requested scope
// and selection prose.
func Verbs() []extension.Verb {
`

// frontendGenHeader is shared by the committed vanilla stub and every composed
// output — the vanilla body below it must stay byte-identical to
// frontend/src/composition/extensions.gen.ts (held by `-verify` via
// stubMatchesVanilla), so the SPA's two lanes differ only in the registry they
// resolve.
//
// Written to be Biome-clean as committed: the vanilla copy lives under
// frontend/src, which `pnpm lint` formats-checks, so a template change that
// drifts from Biome's style breaks the frontend gate rather than the
// composition one.
const frontendGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extensions.gen.ts, through tsconfig's
// "@composition/extensions" alias; a composed lane repoints that alias at
// build/composition/frontend/ — the TypeScript mirror of what GOWORK does for
// the Go lane.
//
// Descriptors only. A unit ships no TSX: what an installation composes into the
// SPA is the set of governed operations its contract fragments publish, read out
// of the MERGED contracts at generation time — the same source the routes, the
// agent tools and the unit manifests derive from, so a screen cannot advertise an
// operation the server does not serve.

/** One governed operation an enabled unit's contract fragment publishes. */
export type ExtensionVerbDescriptor = {
  readonly operationId: string;
  readonly route: string;
  readonly method: string;
  readonly title: string;
  readonly version: string;
  /**
   * The RBAC object the operation gates on, or "" when it gates on none.
   *
   * A plain string, not a union: this file is generated, and the generator
   * cannot enumerate what a unit will declare. app/extensions.ts narrows it
   * into the capability vocabulary, which is where the ext_ grammar is
   * checked once.
   */
  readonly rbacObject: string;
};

/** One enabled extension unit, as the composed installation publishes it. */
export type ExtensionDescriptor = {
  readonly name: string;
  readonly verbs: readonly ExtensionVerbDescriptor[];
};

export const extensions: readonly ExtensionDescriptor[] = `

// composedFiles builds every deterministic output of the composition
// (everything except go.work.sum, which only the go command writes),
// keyed by path relative to build/composition/.
func composedFiles(root string) (map[string][]byte, []declaredVerb, error) {
	units, err := scanExtensions(root)
	if err != nil {
		return nil, nil, err
	}
	work, goVersion, err := composedWork(root, units)
	if err != nil {
		return nil, nil, err
	}
	contracts, err := composedContracts(root, units)
	if err != nil {
		return nil, nil, err
	}
	// Read back OUT of the merged contracts, not out of the fragments: the
	// governance the composed program serves is derived from the document a
	// client is handed. See extverbs.go.
	verbs, err := extensionVerbs(units, contracts)
	if err != nil {
		return nil, nil, err
	}
	wiring, err := canonicalGoSource("backend/extensions_gen.go", extensionsGen(units, verbs))
	if err != nil {
		return nil, nil, err
	}
	files := map[string][]byte{
		goWorkFile:                   work,
		"backend/go.mod":             composedGoMod(goVersion),
		"backend/extensions_gen.go":  wiring,
		"frontend/extensions.gen.ts": frontendGen(units, verbs),
	}
	// The effective contracts: base + every enabled unit's fragments. With
	// no fragments each one is its base, byte-identical — see mergeContract.
	for base, content := range contracts {
		files["api/"+base] = content
	}
	return files, verbs, nil
}

// canonicalGoSource parses emitted Go source and requires it to already
// be canonical gofmt: a template bug surfaces at gen time under this
// name instead of at the next go build, and a formatting drift is an
// error rather than silently adopted — the byte-identity gates (stub ==
// vanilla output, regeneration == recorded hashes) depend on the emitter
// producing canonical bytes itself.
func canonicalGoSource(name string, src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("%s: generated source does not parse: %w", name, err)
	}
	if !bytes.Equal(formatted, src) {
		return nil, fmt.Errorf("%s: generated source is not canonical gofmt — fix the emitter, not the output", name)
	}
	return src, nil
}

// composedWork emits the composed workspace: the root go.work members
// (the single source of truth for the core set), the generated
// composition module, and each enabled extension module — sorted, paths
// relative to build/composition/go.work.
func composedWork(root string, units []extensionUnit) ([]byte, string, error) {
	raw, err := os.ReadFile(filepath.Join(root, goWorkFile))
	if err != nil {
		return nil, "", err
	}
	rootWork, err := modfile.ParseWork(goWorkFile, raw, nil)
	if err != nil {
		return nil, "", fmt.Errorf("root go.work: %w", err)
	}
	if rootWork.Go == nil {
		return nil, "", fmt.Errorf("root go.work carries no go directive")
	}
	// Only go + use are carried over; silently dropping a replace,
	// toolchain or godebug directive would make the composed lane resolve
	// differently from the bare one. Support arrives when a directive is
	// actually needed — until then, refuse loudly.
	if len(rootWork.Replace) > 0 || rootWork.Toolchain != nil || len(rootWork.Godebug) > 0 {
		return nil, "", fmt.Errorf("root go.work carries replace/toolchain/godebug directives gen-composition does not compose yet — extend composedWork before using them")
	}
	goVersion := rootWork.Go.Version

	members := []string{"./backend"}
	for _, use := range rootWork.Use {
		members = append(members, path.Join("../..", use.Path))
	}
	for _, u := range units {
		members = append(members, "../../extensions/"+u.Name)
	}
	sort.Strings(members)

	var b strings.Builder
	b.WriteString("// Code generated by gen-composition; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "go %s\n\nuse (\n", goVersion)
	for _, m := range members {
		// AutoQuote: a member path needing quoting (spaces) must stay a
		// valid use directive, not a broken raw token.
		fmt.Fprintf(&b, "\t%s\n", modfile.AutoQuote(m))
	}
	b.WriteString(")\n")
	return []byte(b.String()), goVersion, nil
}

// composedGoMod declares the generated composition module: module + go
// line only — the workspace resolves the backend and extension modules,
// no require/replace needed.
func composedGoMod(goVersion string) []byte {
	return []byte(fmt.Sprintf("// Code generated by gen-composition; DO NOT EDIT.\n\nmodule %s\n\ngo %s\n", compositionModule, goVersion))
}

// extensionsGen emits the composition wiring. The empty set reproduces
// the committed vanilla stub byte-for-byte; a non-empty set constructs
// each unit in sorted-name order under positional import aliases
// (deterministic, collision-free regardless of module path shape), each
// pinned to its extensions/<name> directory — composition.json and the
// boot inventory attribute the unit by that name, so a declaration
// disagreeing with it must not compose under a different identity.
func extensionsGen(units []extensionUnit, verbs []declaredVerb) []byte {
	var b strings.Builder
	b.WriteString(extensionsGenHeader)
	if anySchema(verbs) {
		b.WriteString("\t\"encoding/json\"\n\n")
	}
	b.WriteString(extensionsGenSurfaceImport)
	if len(units) > 0 {
		b.WriteString("\n")
		for i, u := range units {
			fmt.Fprintf(&b, "\text%d %q\n", i, u.ModulePath)
		}
	}
	b.WriteString(")\n")
	b.WriteString(extensionsGenDoc)
	if len(units) == 0 {
		b.WriteString("\treturn nil\n}\n")
		b.WriteString(extensionsGenVerbsDoc)
		b.WriteString("\treturn nil\n}\n")
		return []byte(b.String())
	}
	b.WriteString("\treturn []extension.Extension{\n")
	for i, u := range units {
		fmt.Fprintf(&b, "\t\tmustBe(%q, ext%d.New()),\n", u.Name, i)
	}
	b.WriteString("\t}\n}\n")
	b.WriteString(extensionsGenVerbsDoc)
	writeVerbLiterals(&b, verbs)
	b.WriteString(`
// mustBe pins a unit to its extensions/<name> directory: a declaration
// whose Name disagrees with the directory it shipped in is a wiring
// defect and aborts the boot.
func mustBe(dir string, e extension.Extension) extension.Extension {
	if string(e.Name) != dir {
		panic("composition: extensions/" + dir + " declares Name \"" + string(e.Name) + "\" — the unit name is its directory name")
	}
	return e
}
`)
	return []byte(b.String())
}

// frontendGen emits the SPA's composed registry. The empty set reproduces
// the committed vanilla stub byte-for-byte (held by stubMatchesVanilla), which
// is what makes the two frontend lanes provably the same program over a
// different registry rather than two programs.
//
// A unit ships no TSX — extensions/<name>/frontend/ is still an unbuilt
// capability layer (scan.go's unbuiltCapabilityLayers) and this slice does not
// lift it. What composes into the SPA is the set of governed operations the
// unit's contract fragments publish, read back out of the MERGED contracts by
// extensionVerbs: the same source the routes, the tools and the manifests
// derive from, so a screen cannot advertise an operation the server does not
// serve.
func frontendGen(units []extensionUnit, verbs []declaredVerb) []byte {
	var b strings.Builder
	b.WriteString(frontendGenHeader)
	if len(units) == 0 {
		b.WriteString("[];\n")
		return []byte(b.String())
	}
	b.WriteString("[\n")
	for _, u := range units {
		fmt.Fprintf(&b, "  {\n    name: %s,\n    verbs: [\n", tsString(u.Name))
		for _, d := range verbs {
			if string(d.verb.Unit) != u.Name {
				continue
			}
			writeVerbDescriptor(&b, d.verb)
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString("];\n")
	return []byte(b.String())
}

// writeVerbDescriptor emits one operation. Fields are written unconditionally,
// for the same reason the Go literals are: the emitted file is what a reviewer
// reads to see what an installation publishes to its own UI, and a missing
// line would have to be read as "absent" or as "the empty string" with nothing
// on the page to say which.
func writeVerbDescriptor(b *strings.Builder, v extension.Verb) {
	b.WriteString("      {\n")
	fmt.Fprintf(b, "        operationId: %s,\n", tsString(v.OperationID))
	fmt.Fprintf(b, "        route: %s,\n", tsString(v.Route))
	fmt.Fprintf(b, "        method: %s,\n", tsString(v.Method))
	fmt.Fprintf(b, "        title: %s,\n", tsString(v.Title))
	fmt.Fprintf(b, "        version: %s,\n", tsString(v.Version))
	fmt.Fprintf(b, "        rbacObject: %s,\n", tsString(v.RbacObject))
	b.WriteString("      },\n")
}

// tsString renders a Go string as a TypeScript string literal through
// encoding/json rather than strconv.Quote: JSON's escaping is a strict subset
// of what a TS double-quoted literal accepts (and it escapes <, > and & as
// \uXXXX), whereas Go's own quoting has forms — raw non-ASCII runes carried
// through verbatim — that would put a unit author's prose into the emitted
// source unescaped. A string that cannot be marshalled does not exist: every
// input here has already round-tripped through the merged YAML document.
func tsString(s string) string {
	encoded, err := json.Marshal(s)
	if err != nil {
		panic("gen-composition: a string from the merged contract is not JSON-encodable: " + err.Error())
	}
	return string(encoded)
}

// writeVerbLiterals emits the composed verb set as a Go slice literal. Fields
// are written unconditionally rather than omitted when zero: the emitted
// source is what a reviewer reads to see what an installation publishes, and a
// missing line would have to be read as "absent" or as "the zero value" with
// nothing on the page to say which.
func writeVerbLiterals(b *strings.Builder, verbs []declaredVerb) {
	if len(verbs) == 0 {
		b.WriteString("\treturn nil\n}\n")
		return
	}
	b.WriteString("\treturn []extension.Verb{\n")
	for _, d := range verbs {
		v := d.verb
		b.WriteString("\t\t{\n")
		fmt.Fprintf(b, "\t\t\tUnit:           %q,\n", string(v.Unit))
		fmt.Fprintf(b, "\t\t\tContract:       %q,\n", v.Contract)
		fmt.Fprintf(b, "\t\t\tOperationID:    %q,\n", v.OperationID)
		fmt.Fprintf(b, "\t\t\tRoute:          %q,\n", v.Route)
		fmt.Fprintf(b, "\t\t\tMethod:         %q,\n", v.Method)
		fmt.Fprintf(b, "\t\t\tTool:           %q,\n", v.Tool)
		fmt.Fprintf(b, "\t\t\tTitle:          %q,\n", v.Title)
		fmt.Fprintf(b, "\t\t\tDescription:    %q,\n", v.Description)
		fmt.Fprintf(b, "\t\t\tVersion:        %q,\n", v.Version)
		fmt.Fprintf(b, "\t\t\tTier:           %q,\n", string(v.Tier))
		fmt.Fprintf(b, "\t\t\tRequestedScope: %q,\n", string(v.RequestedScope))
		writeSchemaLiteral(b, "InputSchema", v.InputSchema)
		writeSchemaLiteral(b, "OutputSchema", v.OutputSchema)
		fmt.Fprintf(b, "\t\t\tRbacObject:     %q,\n", v.RbacObject)
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t}\n}\n")
}

// writeSchemaLiteral emits a json.RawMessage field. A nil schema is emitted as
// `nil`, not as an empty literal: the served adapter defaults a missing input
// schema to `{"type":"object"}`, and `json.RawMessage("")` is not that — it is
// a value every JSON decoder rejects.
func writeSchemaLiteral(b *strings.Builder, field string, raw json.RawMessage) {
	if raw == nil {
		fmt.Fprintf(b, "\t\t\t%s:%s nil,\n", field, strings.Repeat(" ", len("RequestedScope")-len(field)))
		return
	}
	fmt.Fprintf(b, "\t\t\t%s:%s json.RawMessage(%q),\n", field, strings.Repeat(" ", len("RequestedScope")-len(field)), string(raw))
}

// anySchema reports whether the emitted literals will mention
// json.RawMessage, which decides whether the generated file imports
// encoding/json at all.
func anySchema(verbs []declaredVerb) bool {
	for _, d := range verbs {
		if d.verb.InputSchema != nil || d.verb.OutputSchema != nil {
			return true
		}
	}
	return false
}
