// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

// The SPA's three composed artifacts: the descriptor registry, the screen
// registry and the copy overlay. Split out of emit.go, which emits the Go
// wiring and the workspace — one file per side of the composition, because the
// frontend's rules are its own (every artifact here must be import-free, so the
// two locations it is written to can stay byte-identical).

import (
	"fmt"
	"sort"
	"strings"

	"github.com/gradionhq/margince/backend/pkg/extension"
)

// frontendGenHeader is shared by the committed vanilla stub and every composed
// output — the vanilla body below it must stay byte-identical to
// frontend/src/composition/extensions.gen.ts (held by `-verify` via
// stubMatchesVanilla), so the SPA's two lanes differ only in the registry they
// resolve.
//
// Written to be Biome-clean as committed: the vanilla copy lives under
// frontend/src, which `pnpm lint` formats-checks, so a template change that
// drifts from Biome's style breaks the frontend gate rather than the
// composition one.
// extScreensGenHeader is the screen registry's preamble, and it carries the
// same Biome-clean discipline the descriptor header does: its vanilla copy
// lives under frontend/src, which `pnpm lint` formats-checks, so a template
// that drifts from Biome's style breaks the frontend gate.
//
// It imports NOTHING, and that is a hard requirement rather than a style: this
// file is written to two locations at different depths — frontend/src/composition/
// and build/composition/frontend/ — and stubMatchesVanilla requires the two to
// be byte-identical, so any relative specifier would have to differ between
// them and could not. A bare specifier is no better: `react` does not resolve
// from build/composition/, which is outside every node_modules on the path.
//
// So the registry is emitted UNTYPED and App.tsx applies ExtensionScreenRegistry
// at the import site. The check is not lost, only moved: a unit whose default
// export is not a component fails that assignment, in core, in the composed
// lane. The descriptor registry solves the same problem the other way, by
// declaring its type inline — which works there because a descriptor is plain
// data and does not need React's types.
const extScreensGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extscreens.gen.ts, through tsconfig's
// "@composition/screens" alias; a composed lane repoints that alias at
// build/composition/frontend/.
//
// Which unit package renders which unit. A unit ships its screen in its own
// frontend/ layer — a pnpm workspace package named @margince-ext/<unit> — and
// this registry is the only place the SPA learns it exists. A composed unit
// absent from this map is not an error: App.tsx falls through to the generic
// published-operations card, which is what a unit with no bespoke screen gets.
`

// extLocalesGenHeader is the copy overlay's preamble. Import-free for the same
// reason extScreensGenHeader is.
const extLocalesGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extlocales.gen.ts, through tsconfig's
// "@composition/copy" alias; a composed lane repoints that alias at
// build/composition/frontend/.
//
// Every enabled unit's own copy, per locale. A unit ships extensions/<name>/
// frontend/i18n/<locale>.json and this merges them, so there is still ONE
// catalogue, one lookup and one missing-key gate — and the strings travel with
// the unit rather than staying behind when it is removed. Core keys win on a
// collision, and a unit's keys are namespaced to the unit, so a unit cannot
// rewrite core copy even if that ordering were ever loosened.
`

// frontendGen emits the SPA's composed registry. The empty set reproduces
// the committed vanilla stub byte-for-byte (held by stubMatchesVanilla), which
// is what makes the two frontend lanes provably the same program over a
// different registry rather than two programs.
//
// DESCRIPTORS, which is a different artifact from the screens: this registry is
// what App.tsx falls back to for a unit with no bespoke screen, and it composes
// for every unit whether or not one exists. The screens are extScreensGen's.
// What composes here is the set of governed operations the unit's contract
// fragments publish, read back out of the MERGED contracts by
// extensionVerbs: the same source the routes, the tools and the manifests
// derive from, so a screen cannot advertise an operation the server does not
// serve.
func frontendGen(units []extensionUnit, verbs []declaredVerb) []byte {
	var b strings.Builder
	b.WriteString(frontendGenHeader)
	if len(units) == 0 {
		b.WriteString("[];\n")
		return []byte(b.String())
	}
	b.WriteString("[\n")
	for _, u := range units {
		fmt.Fprintf(&b, "  {\n    name: %s,\n    verbs: [\n", tsString(u.Name))
		for _, d := range verbs {
			if string(d.verb.Unit) != u.Name {
				continue
			}
			writeVerbDescriptor(&b, d.verb)
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString("];\n")
	return []byte(b.String())
}

// extScreensGen emits the SPA's composed SCREEN registry: which unit package
// renders which unit. The empty set reproduces the committed vanilla stub
// byte-for-byte (held by stubMatchesVanilla), like every other artifact here.
//
// It is separate from frontendGen because the two answer different questions
// and a unit may have either without the other: the descriptor registry says
// what a unit PUBLISHES and exists for every unit, while this says what RENDERS
// it and exists only for a unit that ships a frontend package. A unit with none
// falls through to the generic published-operations card, which is what de,
// yogi and crm-hello do.
//
// Import order follows unit order, which scanExtensions has already sorted by
// name, so this file is a function of the enabled set rather than of the order
// the filesystem happened to hand directories over.
func extScreensGen(units []extensionUnit) []byte {
	var imports, entries strings.Builder
	for _, u := range units {
		if u.Frontend == nil {
			continue
		}
		ident := screenIdent(u.Name)
		fmt.Fprintf(&imports, "import %s from %s;\n", ident, tsString(u.Frontend.Export))
		fmt.Fprintf(&entries, "  %s: %s,\n", tsString(u.Name), ident)
	}
	var b strings.Builder
	b.WriteString(extScreensGenHeader)
	b.WriteString(imports.String())
	if entries.Len() == 0 {
		b.WriteString("\nexport const extensionScreens = {};\n")
		return []byte(b.String())
	}
	b.WriteString("\nexport const extensionScreens = {\n")
	b.WriteString(entries.String())
	b.WriteString("};\n")
	return []byte(b.String())
}

// extLocalesGen emits the merged copy overlay: every enabled unit's strings,
// per locale, in one object the catalogue spreads over its own.
//
// Emitted UNTYPED and import-free for the reason extScreensGen is: this file is
// written to two locations at different depths and stubMatchesVanilla requires
// them byte-identical, so it can carry no relative specifier. The catalogue
// applies the type where it consumes it.
//
// Locales and keys are both emitted in sorted order, so the file is a function
// of the enabled set rather than of map iteration.
func extLocalesGen(merged map[string]map[string]string) []byte {
	var b strings.Builder
	b.WriteString(extLocalesGenHeader)
	if len(merged) == 0 {
		b.WriteString("\nexport const extensionCopy = {};\n")
		return []byte(b.String())
	}
	b.WriteString("\nexport const extensionCopy = {\n")
	locales := make([]string, 0, len(merged))
	for locale := range merged {
		locales = append(locales, locale)
	}
	sort.Strings(locales)
	for _, locale := range locales {
		fmt.Fprintf(&b, "  %s: {\n", tsString(locale))
		for _, key := range sortedKeys(merged[locale]) {
			fmt.Fprintf(&b, "    %s: %s,\n", tsString(key), tsString(merged[locale][key]))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n")
	return []byte(b.String())
}

// writeVerbDescriptor emits one operation. Fields are written unconditionally,
// for the same reason the Go literals are: the emitted file is what a reviewer
// reads to see what an installation publishes to its own UI, and a missing
// line would have to be read as "absent" or as "the empty string" with nothing
// on the page to say which.
func writeVerbDescriptor(b *strings.Builder, v extension.Verb) {
	b.WriteString("      {\n")
	fmt.Fprintf(b, "        operationId: %s,\n", tsString(v.OperationID))
	fmt.Fprintf(b, "        route: %s,\n", tsString(v.Route))
	fmt.Fprintf(b, "        method: %s,\n", tsString(v.Method))
	fmt.Fprintf(b, "        title: %s,\n", tsString(v.Title))
	fmt.Fprintf(b, "        version: %s,\n", tsString(v.Version))
	fmt.Fprintf(b, "        rbacObject: %s,\n", tsString(v.RbacObject))
	b.WriteString("      },\n")
}
