// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

// The SPA's composed artifact: the descriptor registry. Split out of emit.go,
// which emits the Go wiring and the workspace — one file per side of the
// composition, because the frontend's rules are its own (the artifact here must
// be import-free, so the two locations it is written to can stay
// byte-identical).

import (
	"fmt"
	"strings"

	"github.com/gradionhq/margince/backend/pkg/extension"
)

// frontendGenHeader is shared by the committed vanilla stub and every composed
// output — the vanilla body below it must stay byte-identical to
// frontend/src/composition/extensions.gen.ts (held by `-verify` via
// stubMatchesVanilla), so the SPA's two lanes differ only in the registry they
// resolve.
//
// Written to be Biome-clean as committed: the vanilla copy lives under
// frontend/src, which `pnpm lint` formats-checks, so a template change that
// drifts from Biome's style breaks the frontend gate rather than the
// composition one.
const frontendGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (backend/tools/gen-composition). The DEFAULT (vanilla) lane
// resolves the committed empty-tree copy of this file, at
// frontend/src/composition/extensions.gen.ts, through tsconfig's
// "@composition/extensions" alias; a composed lane repoints that alias at
// build/composition/frontend/ — the TypeScript mirror of what GOWORK does for
// the Go lane.
//
// Descriptors only. A unit ships no TSX: what an installation composes into the
// SPA is the set of governed operations its contract fragments publish, read out
// of the MERGED contracts at generation time — the same source the routes, the
// agent tools and the unit manifests derive from, so a screen cannot advertise an
// operation the server does not serve.

/** One governed operation an enabled unit's contract fragment publishes. */
export type ExtensionVerbDescriptor = {
  readonly operationId: string;
  readonly route: string;
  readonly method: string;
  readonly title: string;
  readonly version: string;
  /**
   * The RBAC object the operation gates on, or "" when it gates on none.
   *
   * A plain string, not a union: this file is generated, and the generator
   * cannot enumerate what a unit will declare. app/extensions.ts narrows it
   * into the capability vocabulary, which is where the ext_ grammar is
   * checked once.
   */
  readonly rbacObject: string;
};

/** One enabled extension unit, as the composed installation publishes it. */
export type ExtensionDescriptor = {
  readonly name: string;
  readonly verbs: readonly ExtensionVerbDescriptor[];
};

export const extensions: readonly ExtensionDescriptor[] = `

// frontendGen emits the SPA's composed registry. The empty set reproduces
// the committed vanilla stub byte-for-byte (held by stubMatchesVanilla), which
// is what makes the two frontend lanes provably the same program over a
// different registry rather than two programs.
//
// DESCRIPTORS, and nothing else: a unit ships no TSX, so what composes here is
// the set of governed operations the unit's contract fragments publish, read
// back out of the MERGED contracts by extensionVerbs — the same source the
// routes, the tools and the manifests derive from, so the SPA cannot advertise
// an operation the server does not serve.
func frontendGen(units []extensionUnit, verbs []declaredVerb) []byte {
	var b strings.Builder
	b.WriteString(frontendGenHeader)
	if len(units) == 0 {
		b.WriteString("[];\n")
		return []byte(b.String())
	}
	b.WriteString("[\n")
	for _, u := range units {
		fmt.Fprintf(&b, "  {\n    name: %s,\n    verbs: [\n", tsString(u.Name))
		for _, d := range verbs {
			if string(d.verb.Unit) != u.Name {
				continue
			}
			writeVerbDescriptor(&b, d.verb)
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString("];\n")
	return []byte(b.String())
}

// writeVerbDescriptor emits one operation. Fields are written unconditionally,
// for the same reason the Go literals are: the emitted file is what a reviewer
// reads to see what an installation publishes to its own UI, and a missing
// line would have to be read as "absent" or as "the empty string" with nothing
// on the page to say which.
func writeVerbDescriptor(b *strings.Builder, v extension.Verb) {
	b.WriteString("      {\n")
	fmt.Fprintf(b, "        operationId: %s,\n", tsString(v.OperationID))
	fmt.Fprintf(b, "        route: %s,\n", tsString(v.Route))
	fmt.Fprintf(b, "        method: %s,\n", tsString(v.Method))
	fmt.Fprintf(b, "        title: %s,\n", tsString(v.Title))
	fmt.Fprintf(b, "        version: %s,\n", tsString(v.Version))
	fmt.Fprintf(b, "        rbacObject: %s,\n", tsString(v.RbacObject))
	b.WriteString("      },\n")
}
