// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: 2026 Gradion

package main

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/mod/modfile"
)

// compositionModule is the constant import path the role binaries wire
// (backend/go.mod resolves it to the committed vanilla stub; the
// generated go.work overrides it with build/composition/backend).
const compositionModule = "github.com/gradionhq/margince/composition"

// extensionsGenHeader is shared by the vanilla stub and every composed
// output — the vanilla body below it must stay byte-identical to
// composition/extensions_gen.go (held by `-verify` via stubMatchesVanilla).
const extensionsGenHeader = `// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.
// Regenerate: make gen (tools/gen-composition). Bare go builds resolve this module's
// committed vanilla stub (composition/ at the repo root) via backend/go.mod's replace;
// composed builds use the generated module under build/composition/ via its go.work.

package composition

import (
	"github.com/gradionhq/margince/backend/pkg/extension"
`

const extensionsGenDoc = `
// Extensions returns the composed extension set for this installation;
// vanilla (an empty extensions/ tree) composes none.
func Extensions() []extension.Extension {
`

// composedFiles builds every deterministic output of the composition
// (everything except go.work.sum, which only the go command writes),
// keyed by path relative to build/composition/.
func composedFiles(root string) (map[string][]byte, error) {
	units, err := scanExtensions(root)
	if err != nil {
		return nil, err
	}
	work, goVersion, err := composedWork(root, units)
	if err != nil {
		return nil, err
	}
	contract, err := os.ReadFile(filepath.Join(root, "backend", "api", "crm.yaml"))
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		"go.work":                    work,
		"backend/go.mod":             composedGoMod(goVersion),
		"backend/extensions_gen.go":  extensionsGen(units),
		"frontend/extensions.gen.ts": frontendGen(),
		// The effective contract: base + extension fragments/overlays once
		// the contract slice lands; until then the base, byte-identical.
		"api/crm.yaml": contract,
	}, nil
}

// composedWork emits the composed workspace: the root go.work members
// (the single source of truth for the core set), the generated
// composition module, and each enabled extension module — sorted, paths
// relative to build/composition/go.work.
func composedWork(root string, units []extensionUnit) ([]byte, string, error) {
	raw, err := os.ReadFile(filepath.Join(root, "go.work"))
	if err != nil {
		return nil, "", err
	}
	rootWork, err := modfile.ParseWork("go.work", raw, nil)
	if err != nil {
		return nil, "", fmt.Errorf("root go.work: %w", err)
	}
	if rootWork.Go == nil {
		return nil, "", fmt.Errorf("root go.work carries no go directive")
	}
	goVersion := rootWork.Go.Version

	members := []string{"./backend"}
	for _, use := range rootWork.Use {
		members = append(members, path.Join("../..", use.Path))
	}
	for _, u := range units {
		members = append(members, "../../extensions/"+u.Name)
	}
	sort.Strings(members)

	var b strings.Builder
	b.WriteString("// Code generated by gen-composition; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "go %s\n\nuse (\n", goVersion)
	for _, m := range members {
		fmt.Fprintf(&b, "\t%s\n", m)
	}
	b.WriteString(")\n")
	return []byte(b.String()), goVersion, nil
}

// composedGoMod declares the generated composition module: module + go
// line only — the workspace resolves the backend and extension modules,
// no require/replace needed.
func composedGoMod(goVersion string) []byte {
	return []byte(fmt.Sprintf("// Code generated by gen-composition; DO NOT EDIT.\n\nmodule %s\n\ngo %s\n", compositionModule, goVersion))
}

// extensionsGen emits the composition wiring. The empty set reproduces
// the committed vanilla stub byte-for-byte; a non-empty set constructs
// each unit in sorted-name order under positional import aliases
// (deterministic, collision-free regardless of module path shape).
func extensionsGen(units []extensionUnit) []byte {
	var b strings.Builder
	b.WriteString(extensionsGenHeader)
	if len(units) > 0 {
		b.WriteString("\n")
		for i, u := range units {
			fmt.Fprintf(&b, "\text%d %q\n", i, u.ModulePath)
		}
	}
	b.WriteString(")\n")
	b.WriteString(extensionsGenDoc)
	if len(units) == 0 {
		b.WriteString("\treturn nil\n}\n")
		return []byte(b.String())
	}
	b.WriteString("\treturn []extension.Extension{\n")
	for i := range units {
		fmt.Fprintf(&b, "\t\text%d.New(),\n", i)
	}
	b.WriteString("\t}\n}\n")
	return []byte(b.String())
}

func frontendGen() []byte {
	return []byte("// Code generated by gen-composition from the enabled set under extensions/; DO NOT EDIT.\n\nexport const extensions = [] as const;\n")
}
